package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * ApoOtr generated by hbm2java
 */
public class ApoOtr  implements java.io.Serializable {


     private int apoOtrId;
     private Cal cal;
     private String apoOtrDes;
     private Float apoOtrLimInf;
     private Float apoOtrLimSup;
     private Integer apoOtrOrdPre;
     private Float apoOtrPto;
     private Float apoOtrWoe;
     private String apoOtrDesLar;

    public ApoOtr() {
    }

	
    public ApoOtr(int apoOtrId) {
        this.apoOtrId = apoOtrId;
    }
    public ApoOtr(int apoOtrId, Cal cal, String apoOtrDes, Float apoOtrLimInf, Float apoOtrLimSup, Integer apoOtrOrdPre, Float apoOtrPto, Float apoOtrWoe, String apoOtrDesLar) {
       this.apoOtrId = apoOtrId;
       this.cal = cal;
       this.apoOtrDes = apoOtrDes;
       this.apoOtrLimInf = apoOtrLimInf;
       this.apoOtrLimSup = apoOtrLimSup;
       this.apoOtrOrdPre = apoOtrOrdPre;
       this.apoOtrPto = apoOtrPto;
       this.apoOtrWoe = apoOtrWoe;
       this.apoOtrDesLar = apoOtrDesLar;
    }
   
    public int getApoOtrId() {
        return this.apoOtrId;
    }
    
    public void setApoOtrId(int apoOtrId) {
        this.apoOtrId = apoOtrId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getApoOtrDes() {
        return this.apoOtrDes;
    }
    
    public void setApoOtrDes(String apoOtrDes) {
        this.apoOtrDes = apoOtrDes;
    }
    public Float getApoOtrLimInf() {
        return this.apoOtrLimInf;
    }
    
    public void setApoOtrLimInf(Float apoOtrLimInf) {
        this.apoOtrLimInf = apoOtrLimInf;
    }
    public Float getApoOtrLimSup() {
        return this.apoOtrLimSup;
    }
    
    public void setApoOtrLimSup(Float apoOtrLimSup) {
        this.apoOtrLimSup = apoOtrLimSup;
    }
    public Integer getApoOtrOrdPre() {
        return this.apoOtrOrdPre;
    }
    
    public void setApoOtrOrdPre(Integer apoOtrOrdPre) {
        this.apoOtrOrdPre = apoOtrOrdPre;
    }
    public Float getApoOtrPto() {
        return this.apoOtrPto;
    }
    
    public void setApoOtrPto(Float apoOtrPto) {
        this.apoOtrPto = apoOtrPto;
    }
    public Float getApoOtrWoe() {
        return this.apoOtrWoe;
    }
    
    public void setApoOtrWoe(Float apoOtrWoe) {
        this.apoOtrWoe = apoOtrWoe;
    }
    public String getApoOtrDesLar() {
        return this.apoOtrDesLar;
    }
    
    public void setApoOtrDesLar(String apoOtrDesLar) {
        this.apoOtrDesLar = apoOtrDesLar;
    }




}


