package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BhrMenIng generated by hbm2java
 */
public class BhrMenIng  implements java.io.Serializable {


     private int bhrMenIngId;
     private Integer calId;
     private String bhrMenIngDes;
     private Float bhrMenIngLimInf;
     private Float bhrMenIngLimSup;
     private Integer bhrMenIngOrdPre;
     private Float bhrMenIngPto;
     private Float bhrMenIngWoe;
     private String bhrMenIngDesLar;
     private Set cliBhrs = new HashSet(0);

    public BhrMenIng() {
    }

	
    public BhrMenIng(int bhrMenIngId) {
        this.bhrMenIngId = bhrMenIngId;
    }
    public BhrMenIng(int bhrMenIngId, Integer calId, String bhrMenIngDes, Float bhrMenIngLimInf, Float bhrMenIngLimSup, Integer bhrMenIngOrdPre, Float bhrMenIngPto, Float bhrMenIngWoe, String bhrMenIngDesLar, Set cliBhrs) {
       this.bhrMenIngId = bhrMenIngId;
       this.calId = calId;
       this.bhrMenIngDes = bhrMenIngDes;
       this.bhrMenIngLimInf = bhrMenIngLimInf;
       this.bhrMenIngLimSup = bhrMenIngLimSup;
       this.bhrMenIngOrdPre = bhrMenIngOrdPre;
       this.bhrMenIngPto = bhrMenIngPto;
       this.bhrMenIngWoe = bhrMenIngWoe;
       this.bhrMenIngDesLar = bhrMenIngDesLar;
       this.cliBhrs = cliBhrs;
    }
   
    public int getBhrMenIngId() {
        return this.bhrMenIngId;
    }
    
    public void setBhrMenIngId(int bhrMenIngId) {
        this.bhrMenIngId = bhrMenIngId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getBhrMenIngDes() {
        return this.bhrMenIngDes;
    }
    
    public void setBhrMenIngDes(String bhrMenIngDes) {
        this.bhrMenIngDes = bhrMenIngDes;
    }
    public Float getBhrMenIngLimInf() {
        return this.bhrMenIngLimInf;
    }
    
    public void setBhrMenIngLimInf(Float bhrMenIngLimInf) {
        this.bhrMenIngLimInf = bhrMenIngLimInf;
    }
    public Float getBhrMenIngLimSup() {
        return this.bhrMenIngLimSup;
    }
    
    public void setBhrMenIngLimSup(Float bhrMenIngLimSup) {
        this.bhrMenIngLimSup = bhrMenIngLimSup;
    }
    public Integer getBhrMenIngOrdPre() {
        return this.bhrMenIngOrdPre;
    }
    
    public void setBhrMenIngOrdPre(Integer bhrMenIngOrdPre) {
        this.bhrMenIngOrdPre = bhrMenIngOrdPre;
    }
    public Float getBhrMenIngPto() {
        return this.bhrMenIngPto;
    }
    
    public void setBhrMenIngPto(Float bhrMenIngPto) {
        this.bhrMenIngPto = bhrMenIngPto;
    }
    public Float getBhrMenIngWoe() {
        return this.bhrMenIngWoe;
    }
    
    public void setBhrMenIngWoe(Float bhrMenIngWoe) {
        this.bhrMenIngWoe = bhrMenIngWoe;
    }
    public String getBhrMenIngDesLar() {
        return this.bhrMenIngDesLar;
    }
    
    public void setBhrMenIngDesLar(String bhrMenIngDesLar) {
        this.bhrMenIngDesLar = bhrMenIngDesLar;
    }
    public Set getCliBhrs() {
        return this.cliBhrs;
    }
    
    public void setCliBhrs(Set cliBhrs) {
        this.cliBhrs = cliBhrs;
    }




}


