package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BhrPagPtlCnt generated by hbm2java
 */
public class BhrPagPtlCnt  implements java.io.Serializable {


     private int bhrPagPtlCntId;
     private Integer calId;
     private String bhrPagPtlCntDes;
     private Float bhrPagPtlCntLimInf;
     private Float bhrPagPtlCntLimSup;
     private Integer bhrPagPtlCntOrdPre;
     private Float bhrPagPtlCntPto;
     private Float bhrPagPtlCntWoe;
     private String bhrPagPtlCntDesLar;
     private Set cliBhrs = new HashSet(0);

    public BhrPagPtlCnt() {
    }

	
    public BhrPagPtlCnt(int bhrPagPtlCntId) {
        this.bhrPagPtlCntId = bhrPagPtlCntId;
    }
    public BhrPagPtlCnt(int bhrPagPtlCntId, Integer calId, String bhrPagPtlCntDes, Float bhrPagPtlCntLimInf, Float bhrPagPtlCntLimSup, Integer bhrPagPtlCntOrdPre, Float bhrPagPtlCntPto, Float bhrPagPtlCntWoe, String bhrPagPtlCntDesLar, Set cliBhrs) {
       this.bhrPagPtlCntId = bhrPagPtlCntId;
       this.calId = calId;
       this.bhrPagPtlCntDes = bhrPagPtlCntDes;
       this.bhrPagPtlCntLimInf = bhrPagPtlCntLimInf;
       this.bhrPagPtlCntLimSup = bhrPagPtlCntLimSup;
       this.bhrPagPtlCntOrdPre = bhrPagPtlCntOrdPre;
       this.bhrPagPtlCntPto = bhrPagPtlCntPto;
       this.bhrPagPtlCntWoe = bhrPagPtlCntWoe;
       this.bhrPagPtlCntDesLar = bhrPagPtlCntDesLar;
       this.cliBhrs = cliBhrs;
    }
   
    public int getBhrPagPtlCntId() {
        return this.bhrPagPtlCntId;
    }
    
    public void setBhrPagPtlCntId(int bhrPagPtlCntId) {
        this.bhrPagPtlCntId = bhrPagPtlCntId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getBhrPagPtlCntDes() {
        return this.bhrPagPtlCntDes;
    }
    
    public void setBhrPagPtlCntDes(String bhrPagPtlCntDes) {
        this.bhrPagPtlCntDes = bhrPagPtlCntDes;
    }
    public Float getBhrPagPtlCntLimInf() {
        return this.bhrPagPtlCntLimInf;
    }
    
    public void setBhrPagPtlCntLimInf(Float bhrPagPtlCntLimInf) {
        this.bhrPagPtlCntLimInf = bhrPagPtlCntLimInf;
    }
    public Float getBhrPagPtlCntLimSup() {
        return this.bhrPagPtlCntLimSup;
    }
    
    public void setBhrPagPtlCntLimSup(Float bhrPagPtlCntLimSup) {
        this.bhrPagPtlCntLimSup = bhrPagPtlCntLimSup;
    }
    public Integer getBhrPagPtlCntOrdPre() {
        return this.bhrPagPtlCntOrdPre;
    }
    
    public void setBhrPagPtlCntOrdPre(Integer bhrPagPtlCntOrdPre) {
        this.bhrPagPtlCntOrdPre = bhrPagPtlCntOrdPre;
    }
    public Float getBhrPagPtlCntPto() {
        return this.bhrPagPtlCntPto;
    }
    
    public void setBhrPagPtlCntPto(Float bhrPagPtlCntPto) {
        this.bhrPagPtlCntPto = bhrPagPtlCntPto;
    }
    public Float getBhrPagPtlCntWoe() {
        return this.bhrPagPtlCntWoe;
    }
    
    public void setBhrPagPtlCntWoe(Float bhrPagPtlCntWoe) {
        this.bhrPagPtlCntWoe = bhrPagPtlCntWoe;
    }
    public String getBhrPagPtlCntDesLar() {
        return this.bhrPagPtlCntDesLar;
    }
    
    public void setBhrPagPtlCntDesLar(String bhrPagPtlCntDesLar) {
        this.bhrPagPtlCntDesLar = bhrPagPtlCntDesLar;
    }
    public Set getCliBhrs() {
        return this.cliBhrs;
    }
    
    public void setCliBhrs(Set cliBhrs) {
        this.cliBhrs = cliBhrs;
    }




}


