package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BurAnt generated by hbm2java
 */
public class BurAnt  implements java.io.Serializable {


     private int burAntId;
     private Cal cal;
     private String burAntDes;
     private Float burAntLimInf;
     private Float burAntLimSup;
     private Integer burAntOrdPre;
     private Float burAntPto;
     private Float burAntWoe;
     private String burAntDesLar;
     private Set cliMtas = new HashSet(0);

    public BurAnt() {
    }

	
    public BurAnt(int burAntId) {
        this.burAntId = burAntId;
    }
    public BurAnt(int burAntId, Cal cal, String burAntDes, Float burAntLimInf, Float burAntLimSup, Integer burAntOrdPre, Float burAntPto, Float burAntWoe, String burAntDesLar, Set cliMtas) {
       this.burAntId = burAntId;
       this.cal = cal;
       this.burAntDes = burAntDes;
       this.burAntLimInf = burAntLimInf;
       this.burAntLimSup = burAntLimSup;
       this.burAntOrdPre = burAntOrdPre;
       this.burAntPto = burAntPto;
       this.burAntWoe = burAntWoe;
       this.burAntDesLar = burAntDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getBurAntId() {
        return this.burAntId;
    }
    
    public void setBurAntId(int burAntId) {
        this.burAntId = burAntId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getBurAntDes() {
        return this.burAntDes;
    }
    
    public void setBurAntDes(String burAntDes) {
        this.burAntDes = burAntDes;
    }
    public Float getBurAntLimInf() {
        return this.burAntLimInf;
    }
    
    public void setBurAntLimInf(Float burAntLimInf) {
        this.burAntLimInf = burAntLimInf;
    }
    public Float getBurAntLimSup() {
        return this.burAntLimSup;
    }
    
    public void setBurAntLimSup(Float burAntLimSup) {
        this.burAntLimSup = burAntLimSup;
    }
    public Integer getBurAntOrdPre() {
        return this.burAntOrdPre;
    }
    
    public void setBurAntOrdPre(Integer burAntOrdPre) {
        this.burAntOrdPre = burAntOrdPre;
    }
    public Float getBurAntPto() {
        return this.burAntPto;
    }
    
    public void setBurAntPto(Float burAntPto) {
        this.burAntPto = burAntPto;
    }
    public Float getBurAntWoe() {
        return this.burAntWoe;
    }
    
    public void setBurAntWoe(Float burAntWoe) {
        this.burAntWoe = burAntWoe;
    }
    public String getBurAntDesLar() {
        return this.burAntDesLar;
    }
    
    public void setBurAntDesLar(String burAntDesLar) {
        this.burAntDesLar = burAntDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


