package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BurHis generated by hbm2java
 */
public class BurHis  implements java.io.Serializable {


     private int burHisId;
     private Cal cal;
     private String burHisDes;
     private Float burHisLimInf;
     private Float burHisLimSup;
     private Integer burHisOrdPre;
     private Float burHisPto;
     private Float burHisWoe;
     private String burHisDesLar;
     private Set cliMtas = new HashSet(0);

    public BurHis() {
    }

	
    public BurHis(int burHisId) {
        this.burHisId = burHisId;
    }
    public BurHis(int burHisId, Cal cal, String burHisDes, Float burHisLimInf, Float burHisLimSup, Integer burHisOrdPre, Float burHisPto, Float burHisWoe, String burHisDesLar, Set cliMtas) {
       this.burHisId = burHisId;
       this.cal = cal;
       this.burHisDes = burHisDes;
       this.burHisLimInf = burHisLimInf;
       this.burHisLimSup = burHisLimSup;
       this.burHisOrdPre = burHisOrdPre;
       this.burHisPto = burHisPto;
       this.burHisWoe = burHisWoe;
       this.burHisDesLar = burHisDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getBurHisId() {
        return this.burHisId;
    }
    
    public void setBurHisId(int burHisId) {
        this.burHisId = burHisId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getBurHisDes() {
        return this.burHisDes;
    }
    
    public void setBurHisDes(String burHisDes) {
        this.burHisDes = burHisDes;
    }
    public Float getBurHisLimInf() {
        return this.burHisLimInf;
    }
    
    public void setBurHisLimInf(Float burHisLimInf) {
        this.burHisLimInf = burHisLimInf;
    }
    public Float getBurHisLimSup() {
        return this.burHisLimSup;
    }
    
    public void setBurHisLimSup(Float burHisLimSup) {
        this.burHisLimSup = burHisLimSup;
    }
    public Integer getBurHisOrdPre() {
        return this.burHisOrdPre;
    }
    
    public void setBurHisOrdPre(Integer burHisOrdPre) {
        this.burHisOrdPre = burHisOrdPre;
    }
    public Float getBurHisPto() {
        return this.burHisPto;
    }
    
    public void setBurHisPto(Float burHisPto) {
        this.burHisPto = burHisPto;
    }
    public Float getBurHisWoe() {
        return this.burHisWoe;
    }
    
    public void setBurHisWoe(Float burHisWoe) {
        this.burHisWoe = burHisWoe;
    }
    public String getBurHisDesLar() {
        return this.burHisDesLar;
    }
    
    public void setBurHisDesLar(String burHisDesLar) {
        this.burHisDesLar = burHisDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


