package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * CliBur generated by hbm2java
 */
public class CliBur  implements java.io.Serializable {


     private Integer cliBurId;
     private Integer cliId;
     private Integer burAntId;
     private Integer burActId;
     private Integer burHisId;
     private Integer burUsoId;
     private Integer buroPagId;
     private Integer cliBurCveMop;
     private Float cliBurImpMop;
     private String cliBurTpoMop;
     private Float cliBurPagMop;
     private Integer cliBurNumAbi;
     private Integer cliBurMaxAbi;
     private Float cliBurMonAbi;
     private Float cliBurLimAbi;
     private Float cliBurSalAbi;
     private Integer cliBurNumCer;
     private Integer cliBurMaxCer;
     private Integer cliBurMonCer;
     private Float cliBurLimCer;
     private Float cliBurSalCer;
     private Integer cliBurMop;

    public CliBur() {
    }

    public CliBur(Integer cliId, Integer burAntId, Integer burActId, Integer burHisId, Integer burUsoId, Integer buroPagId, Integer cliBurCveMop, Float cliBurImpMop, String cliBurTpoMop, Float cliBurPagMop, Integer cliBurNumAbi, Integer cliBurMaxAbi, Float cliBurMonAbi, Float cliBurLimAbi, Float cliBurSalAbi, Integer cliBurNumCer, Integer cliBurMaxCer, Integer cliBurMonCer, Float cliBurLimCer, Float cliBurSalCer, Integer cliBurMop) {
       this.cliId = cliId;
       this.burAntId = burAntId;
       this.burActId = burActId;
       this.burHisId = burHisId;
       this.burUsoId = burUsoId;
       this.buroPagId = buroPagId;
       this.cliBurCveMop = cliBurCveMop;
       this.cliBurImpMop = cliBurImpMop;
       this.cliBurTpoMop = cliBurTpoMop;
       this.cliBurPagMop = cliBurPagMop;
       this.cliBurNumAbi = cliBurNumAbi;
       this.cliBurMaxAbi = cliBurMaxAbi;
       this.cliBurMonAbi = cliBurMonAbi;
       this.cliBurLimAbi = cliBurLimAbi;
       this.cliBurSalAbi = cliBurSalAbi;
       this.cliBurNumCer = cliBurNumCer;
       this.cliBurMaxCer = cliBurMaxCer;
       this.cliBurMonCer = cliBurMonCer;
       this.cliBurLimCer = cliBurLimCer;
       this.cliBurSalCer = cliBurSalCer;
       this.cliBurMop = cliBurMop;
    }
   
    public Integer getCliBurId() {
        return this.cliBurId;
    }
    
    public void setCliBurId(Integer cliBurId) {
        this.cliBurId = cliBurId;
    }
    public Integer getCliId() {
        return this.cliId;
    }
    
    public void setCliId(Integer cliId) {
        this.cliId = cliId;
    }
    public Integer getBurAntId() {
        return this.burAntId;
    }
    
    public void setBurAntId(Integer burAntId) {
        this.burAntId = burAntId;
    }
    public Integer getBurActId() {
        return this.burActId;
    }
    
    public void setBurActId(Integer burActId) {
        this.burActId = burActId;
    }
    public Integer getBurHisId() {
        return this.burHisId;
    }
    
    public void setBurHisId(Integer burHisId) {
        this.burHisId = burHisId;
    }
    public Integer getBurUsoId() {
        return this.burUsoId;
    }
    
    public void setBurUsoId(Integer burUsoId) {
        this.burUsoId = burUsoId;
    }
    public Integer getBuroPagId() {
        return this.buroPagId;
    }
    
    public void setBuroPagId(Integer buroPagId) {
        this.buroPagId = buroPagId;
    }
    public Integer getCliBurCveMop() {
        return this.cliBurCveMop;
    }
    
    public void setCliBurCveMop(Integer cliBurCveMop) {
        this.cliBurCveMop = cliBurCveMop;
    }
    public Float getCliBurImpMop() {
        return this.cliBurImpMop;
    }
    
    public void setCliBurImpMop(Float cliBurImpMop) {
        this.cliBurImpMop = cliBurImpMop;
    }
    public String getCliBurTpoMop() {
        return this.cliBurTpoMop;
    }
    
    public void setCliBurTpoMop(String cliBurTpoMop) {
        this.cliBurTpoMop = cliBurTpoMop;
    }
    public Float getCliBurPagMop() {
        return this.cliBurPagMop;
    }
    
    public void setCliBurPagMop(Float cliBurPagMop) {
        this.cliBurPagMop = cliBurPagMop;
    }
    public Integer getCliBurNumAbi() {
        return this.cliBurNumAbi;
    }
    
    public void setCliBurNumAbi(Integer cliBurNumAbi) {
        this.cliBurNumAbi = cliBurNumAbi;
    }
    public Integer getCliBurMaxAbi() {
        return this.cliBurMaxAbi;
    }
    
    public void setCliBurMaxAbi(Integer cliBurMaxAbi) {
        this.cliBurMaxAbi = cliBurMaxAbi;
    }
    public Float getCliBurMonAbi() {
        return this.cliBurMonAbi;
    }
    
    public void setCliBurMonAbi(Float cliBurMonAbi) {
        this.cliBurMonAbi = cliBurMonAbi;
    }
    public Float getCliBurLimAbi() {
        return this.cliBurLimAbi;
    }
    
    public void setCliBurLimAbi(Float cliBurLimAbi) {
        this.cliBurLimAbi = cliBurLimAbi;
    }
    public Float getCliBurSalAbi() {
        return this.cliBurSalAbi;
    }
    
    public void setCliBurSalAbi(Float cliBurSalAbi) {
        this.cliBurSalAbi = cliBurSalAbi;
    }
    public Integer getCliBurNumCer() {
        return this.cliBurNumCer;
    }
    
    public void setCliBurNumCer(Integer cliBurNumCer) {
        this.cliBurNumCer = cliBurNumCer;
    }
    public Integer getCliBurMaxCer() {
        return this.cliBurMaxCer;
    }
    
    public void setCliBurMaxCer(Integer cliBurMaxCer) {
        this.cliBurMaxCer = cliBurMaxCer;
    }
    public Integer getCliBurMonCer() {
        return this.cliBurMonCer;
    }
    
    public void setCliBurMonCer(Integer cliBurMonCer) {
        this.cliBurMonCer = cliBurMonCer;
    }
    public Float getCliBurLimCer() {
        return this.cliBurLimCer;
    }
    
    public void setCliBurLimCer(Float cliBurLimCer) {
        this.cliBurLimCer = cliBurLimCer;
    }
    public Float getCliBurSalCer() {
        return this.cliBurSalCer;
    }
    
    public void setCliBurSalCer(Float cliBurSalCer) {
        this.cliBurSalCer = cliBurSalCer;
    }
    public Integer getCliBurMop() {
        return this.cliBurMop;
    }
    
    public void setCliBurMop(Integer cliBurMop) {
        this.cliBurMop = cliBurMop;
    }




}


