package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CliPpr generated by hbm2java
 */
public class CliPpr  implements java.io.Serializable {


     private Integer cliMtaId;
     private Cli cli;
     private IntPi intPi;
     private FtrPpr ftrPpr;
     private Integer calId;
     private Date cliFecNac;
     private Integer cliEdaId;
     private String codPosId;
     private Integer ocpId;
     private Integer edoId;
     private String cliPprMes;

    public CliPpr() {
    }

    public CliPpr(Cli cli, IntPi intPi, FtrPpr ftrPpr, Integer calId, Date cliFecNac, Integer cliEdaId, String codPosId, Integer ocpId, Integer edoId, String cliPprMes) {
       this.cli = cli;
       this.intPi = intPi;
       this.ftrPpr = ftrPpr;
       this.calId = calId;
       this.cliFecNac = cliFecNac;
       this.cliEdaId = cliEdaId;
       this.codPosId = codPosId;
       this.ocpId = ocpId;
       this.edoId = edoId;
       this.cliPprMes = cliPprMes;
    }
   
    public Integer getCliMtaId() {
        return this.cliMtaId;
    }
    
    public void setCliMtaId(Integer cliMtaId) {
        this.cliMtaId = cliMtaId;
    }
    public Cli getCli() {
        return this.cli;
    }
    
    public void setCli(Cli cli) {
        this.cli = cli;
    }
    public IntPi getIntPi() {
        return this.intPi;
    }
    
    public void setIntPi(IntPi intPi) {
        this.intPi = intPi;
    }
    public FtrPpr getFtrPpr() {
        return this.ftrPpr;
    }
    
    public void setFtrPpr(FtrPpr ftrPpr) {
        this.ftrPpr = ftrPpr;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public Date getCliFecNac() {
        return this.cliFecNac;
    }
    
    public void setCliFecNac(Date cliFecNac) {
        this.cliFecNac = cliFecNac;
    }
    public Integer getCliEdaId() {
        return this.cliEdaId;
    }
    
    public void setCliEdaId(Integer cliEdaId) {
        this.cliEdaId = cliEdaId;
    }
    public String getCodPosId() {
        return this.codPosId;
    }
    
    public void setCodPosId(String codPosId) {
        this.codPosId = codPosId;
    }
    public Integer getOcpId() {
        return this.ocpId;
    }
    
    public void setOcpId(Integer ocpId) {
        this.ocpId = ocpId;
    }
    public Integer getEdoId() {
        return this.edoId;
    }
    
    public void setEdoId(Integer edoId) {
        this.edoId = edoId;
    }
    public String getCliPprMes() {
        return this.cliPprMes;
    }
    
    public void setCliPprMes(String cliPprMes) {
        this.cliPprMes = cliPprMes;
    }




}


