package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * ConBar generated by hbm2java
 */
public class ConBar  implements java.io.Serializable {


     private int conBarId;
     private Cal cal;
     private String conBarDes;
     private Float conBarLimInf;
     private Float conBarLimSup;
     private Integer conBarOrdPre;
     private Float conBarPto;
     private Float conBarWoe;
     private String conBarDesLar;

    public ConBar() {
    }

	
    public ConBar(int conBarId) {
        this.conBarId = conBarId;
    }
    public ConBar(int conBarId, Cal cal, String conBarDes, Float conBarLimInf, Float conBarLimSup, Integer conBarOrdPre, Float conBarPto, Float conBarWoe, String conBarDesLar) {
       this.conBarId = conBarId;
       this.cal = cal;
       this.conBarDes = conBarDes;
       this.conBarLimInf = conBarLimInf;
       this.conBarLimSup = conBarLimSup;
       this.conBarOrdPre = conBarOrdPre;
       this.conBarPto = conBarPto;
       this.conBarWoe = conBarWoe;
       this.conBarDesLar = conBarDesLar;
    }
   
    public int getConBarId() {
        return this.conBarId;
    }
    
    public void setConBarId(int conBarId) {
        this.conBarId = conBarId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getConBarDes() {
        return this.conBarDes;
    }
    
    public void setConBarDes(String conBarDes) {
        this.conBarDes = conBarDes;
    }
    public Float getConBarLimInf() {
        return this.conBarLimInf;
    }
    
    public void setConBarLimInf(Float conBarLimInf) {
        this.conBarLimInf = conBarLimInf;
    }
    public Float getConBarLimSup() {
        return this.conBarLimSup;
    }
    
    public void setConBarLimSup(Float conBarLimSup) {
        this.conBarLimSup = conBarLimSup;
    }
    public Integer getConBarOrdPre() {
        return this.conBarOrdPre;
    }
    
    public void setConBarOrdPre(Integer conBarOrdPre) {
        this.conBarOrdPre = conBarOrdPre;
    }
    public Float getConBarPto() {
        return this.conBarPto;
    }
    
    public void setConBarPto(Float conBarPto) {
        this.conBarPto = conBarPto;
    }
    public Float getConBarWoe() {
        return this.conBarWoe;
    }
    
    public void setConBarWoe(Float conBarWoe) {
        this.conBarWoe = conBarWoe;
    }
    public String getConBarDesLar() {
        return this.conBarDesLar;
    }
    
    public void setConBarDesLar(String conBarDesLar) {
        this.conBarDesLar = conBarDesLar;
    }




}


