package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * ConRed generated by hbm2java
 */
public class ConRed  implements java.io.Serializable {


     private int conRedId;
     private Cal cal;
     private String conRedDes;
     private Float conRedLimInf;
     private Float conRedLimSup;
     private Integer conRedOrdPre;
     private Float conRedPto;
     private Float conRedWoe;
     private String conRedDesLar;

    public ConRed() {
    }

	
    public ConRed(int conRedId) {
        this.conRedId = conRedId;
    }
    public ConRed(int conRedId, Cal cal, String conRedDes, Float conRedLimInf, Float conRedLimSup, Integer conRedOrdPre, Float conRedPto, Float conRedWoe, String conRedDesLar) {
       this.conRedId = conRedId;
       this.cal = cal;
       this.conRedDes = conRedDes;
       this.conRedLimInf = conRedLimInf;
       this.conRedLimSup = conRedLimSup;
       this.conRedOrdPre = conRedOrdPre;
       this.conRedPto = conRedPto;
       this.conRedWoe = conRedWoe;
       this.conRedDesLar = conRedDesLar;
    }
   
    public int getConRedId() {
        return this.conRedId;
    }
    
    public void setConRedId(int conRedId) {
        this.conRedId = conRedId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getConRedDes() {
        return this.conRedDes;
    }
    
    public void setConRedDes(String conRedDes) {
        this.conRedDes = conRedDes;
    }
    public Float getConRedLimInf() {
        return this.conRedLimInf;
    }
    
    public void setConRedLimInf(Float conRedLimInf) {
        this.conRedLimInf = conRedLimInf;
    }
    public Float getConRedLimSup() {
        return this.conRedLimSup;
    }
    
    public void setConRedLimSup(Float conRedLimSup) {
        this.conRedLimSup = conRedLimSup;
    }
    public Integer getConRedOrdPre() {
        return this.conRedOrdPre;
    }
    
    public void setConRedOrdPre(Integer conRedOrdPre) {
        this.conRedOrdPre = conRedOrdPre;
    }
    public Float getConRedPto() {
        return this.conRedPto;
    }
    
    public void setConRedPto(Float conRedPto) {
        this.conRedPto = conRedPto;
    }
    public Float getConRedWoe() {
        return this.conRedWoe;
    }
    
    public void setConRedWoe(Float conRedWoe) {
        this.conRedWoe = conRedWoe;
    }
    public String getConRedDesLar() {
        return this.conRedDesLar;
    }
    
    public void setConRedDesLar(String conRedDesLar) {
        this.conRedDesLar = conRedDesLar;
    }




}


