package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * ConUce generated by hbm2java
 */
public class ConUce  implements java.io.Serializable {


     private int conUceId;
     private Cal cal;
     private String conUceDes;
     private Float conUceLimInf;
     private Float conUceLimSup;
     private Integer conUceOrdPre;
     private Float conUcePto;
     private Float conUceWoe;
     private String conUceDesLar;

    public ConUce() {
    }

	
    public ConUce(int conUceId) {
        this.conUceId = conUceId;
    }
    public ConUce(int conUceId, Cal cal, String conUceDes, Float conUceLimInf, Float conUceLimSup, Integer conUceOrdPre, Float conUcePto, Float conUceWoe, String conUceDesLar) {
       this.conUceId = conUceId;
       this.cal = cal;
       this.conUceDes = conUceDes;
       this.conUceLimInf = conUceLimInf;
       this.conUceLimSup = conUceLimSup;
       this.conUceOrdPre = conUceOrdPre;
       this.conUcePto = conUcePto;
       this.conUceWoe = conUceWoe;
       this.conUceDesLar = conUceDesLar;
    }
   
    public int getConUceId() {
        return this.conUceId;
    }
    
    public void setConUceId(int conUceId) {
        this.conUceId = conUceId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getConUceDes() {
        return this.conUceDes;
    }
    
    public void setConUceDes(String conUceDes) {
        this.conUceDes = conUceDes;
    }
    public Float getConUceLimInf() {
        return this.conUceLimInf;
    }
    
    public void setConUceLimInf(Float conUceLimInf) {
        this.conUceLimInf = conUceLimInf;
    }
    public Float getConUceLimSup() {
        return this.conUceLimSup;
    }
    
    public void setConUceLimSup(Float conUceLimSup) {
        this.conUceLimSup = conUceLimSup;
    }
    public Integer getConUceOrdPre() {
        return this.conUceOrdPre;
    }
    
    public void setConUceOrdPre(Integer conUceOrdPre) {
        this.conUceOrdPre = conUceOrdPre;
    }
    public Float getConUcePto() {
        return this.conUcePto;
    }
    
    public void setConUcePto(Float conUcePto) {
        this.conUcePto = conUcePto;
    }
    public Float getConUceWoe() {
        return this.conUceWoe;
    }
    
    public void setConUceWoe(Float conUceWoe) {
        this.conUceWoe = conUceWoe;
    }
    public String getConUceDesLar() {
        return this.conUceDesLar;
    }
    
    public void setConUceDesLar(String conUceDesLar) {
        this.conUceDesLar = conUceDesLar;
    }




}


