package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * CreHip generated by hbm2java
 */
public class CreHip  implements java.io.Serializable {


     private int creHipId;
     private Cal cal;
     private String creHipDes;
     private Float creHipLimInf;
     private Float creHipLimSup;
     private Integer creHipOrdPre;
     private Float creHipPto;
     private Float creHipWoe;
     private String creHipDesLar;

    public CreHip() {
    }

	
    public CreHip(int creHipId) {
        this.creHipId = creHipId;
    }
    public CreHip(int creHipId, Cal cal, String creHipDes, Float creHipLimInf, Float creHipLimSup, Integer creHipOrdPre, Float creHipPto, Float creHipWoe, String creHipDesLar) {
       this.creHipId = creHipId;
       this.cal = cal;
       this.creHipDes = creHipDes;
       this.creHipLimInf = creHipLimInf;
       this.creHipLimSup = creHipLimSup;
       this.creHipOrdPre = creHipOrdPre;
       this.creHipPto = creHipPto;
       this.creHipWoe = creHipWoe;
       this.creHipDesLar = creHipDesLar;
    }
   
    public int getCreHipId() {
        return this.creHipId;
    }
    
    public void setCreHipId(int creHipId) {
        this.creHipId = creHipId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getCreHipDes() {
        return this.creHipDes;
    }
    
    public void setCreHipDes(String creHipDes) {
        this.creHipDes = creHipDes;
    }
    public Float getCreHipLimInf() {
        return this.creHipLimInf;
    }
    
    public void setCreHipLimInf(Float creHipLimInf) {
        this.creHipLimInf = creHipLimInf;
    }
    public Float getCreHipLimSup() {
        return this.creHipLimSup;
    }
    
    public void setCreHipLimSup(Float creHipLimSup) {
        this.creHipLimSup = creHipLimSup;
    }
    public Integer getCreHipOrdPre() {
        return this.creHipOrdPre;
    }
    
    public void setCreHipOrdPre(Integer creHipOrdPre) {
        this.creHipOrdPre = creHipOrdPre;
    }
    public Float getCreHipPto() {
        return this.creHipPto;
    }
    
    public void setCreHipPto(Float creHipPto) {
        this.creHipPto = creHipPto;
    }
    public Float getCreHipWoe() {
        return this.creHipWoe;
    }
    
    public void setCreHipWoe(Float creHipWoe) {
        this.creHipWoe = creHipWoe;
    }
    public String getCreHipDesLar() {
        return this.creHipDesLar;
    }
    
    public void setCreHipDesLar(String creHipDesLar) {
        this.creHipDesLar = creHipDesLar;
    }




}


