package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * DepEco generated by hbm2java
 */
public class DepEco  implements java.io.Serializable {


     private int depEcoId;
     private Cal cal;
     private String depEcoDes;
     private Float depEcoLimInf;
     private Float depEcoLimSup;
     private Integer depEcoOrdPre;
     private Float depEcoPto;
     private Float depEcoWoe;
     private String depEcoDesLar;
     private Set cliMtas = new HashSet(0);

    public DepEco() {
    }

	
    public DepEco(int depEcoId) {
        this.depEcoId = depEcoId;
    }
    public DepEco(int depEcoId, Cal cal, String depEcoDes, Float depEcoLimInf, Float depEcoLimSup, Integer depEcoOrdPre, Float depEcoPto, Float depEcoWoe, String depEcoDesLar, Set cliMtas) {
       this.depEcoId = depEcoId;
       this.cal = cal;
       this.depEcoDes = depEcoDes;
       this.depEcoLimInf = depEcoLimInf;
       this.depEcoLimSup = depEcoLimSup;
       this.depEcoOrdPre = depEcoOrdPre;
       this.depEcoPto = depEcoPto;
       this.depEcoWoe = depEcoWoe;
       this.depEcoDesLar = depEcoDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getDepEcoId() {
        return this.depEcoId;
    }
    
    public void setDepEcoId(int depEcoId) {
        this.depEcoId = depEcoId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getDepEcoDes() {
        return this.depEcoDes;
    }
    
    public void setDepEcoDes(String depEcoDes) {
        this.depEcoDes = depEcoDes;
    }
    public Float getDepEcoLimInf() {
        return this.depEcoLimInf;
    }
    
    public void setDepEcoLimInf(Float depEcoLimInf) {
        this.depEcoLimInf = depEcoLimInf;
    }
    public Float getDepEcoLimSup() {
        return this.depEcoLimSup;
    }
    
    public void setDepEcoLimSup(Float depEcoLimSup) {
        this.depEcoLimSup = depEcoLimSup;
    }
    public Integer getDepEcoOrdPre() {
        return this.depEcoOrdPre;
    }
    
    public void setDepEcoOrdPre(Integer depEcoOrdPre) {
        this.depEcoOrdPre = depEcoOrdPre;
    }
    public Float getDepEcoPto() {
        return this.depEcoPto;
    }
    
    public void setDepEcoPto(Float depEcoPto) {
        this.depEcoPto = depEcoPto;
    }
    public Float getDepEcoWoe() {
        return this.depEcoWoe;
    }
    
    public void setDepEcoWoe(Float depEcoWoe) {
        this.depEcoWoe = depEcoWoe;
    }
    public String getDepEcoDesLar() {
        return this.depEcoDesLar;
    }
    
    public void setDepEcoDesLar(String depEcoDesLar) {
        this.depEcoDesLar = depEcoDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


