package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * Des generated by hbm2java
 */
public class Des  implements java.io.Serializable {


     private int desId;
     private Cal cal;
     private Edo edo;
     private String desDes;

    public Des() {
    }

	
    public Des(int desId) {
        this.desId = desId;
    }
    public Des(int desId, Cal cal, Edo edo, String desDes) {
       this.desId = desId;
       this.cal = cal;
       this.edo = edo;
       this.desDes = desDes;
    }
   
    public int getDesId() {
        return this.desId;
    }
    
    public void setDesId(int desId) {
        this.desId = desId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public Edo getEdo() {
        return this.edo;
    }
    
    public void setEdo(Edo edo) {
        this.edo = edo;
    }
    public String getDesDes() {
        return this.desDes;
    }
    
    public void setDesDes(String desDes) {
        this.desDes = desDes;
    }




}


