package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * DinExt generated by hbm2java
 */
public class DinExt  implements java.io.Serializable {


     private int dinExtId;
     private Cal cal;
     private String dinExtDes;
     private Float dinExtLimInf;
     private Float dinExtLimSup;
     private Integer dinExtOrdPre;
     private Float dinExtPto;
     private Float dinExtWoe;
     private String dinExtDesLar;
     private Set cliMtas = new HashSet(0);

    public DinExt() {
    }

	
    public DinExt(int dinExtId) {
        this.dinExtId = dinExtId;
    }
    public DinExt(int dinExtId, Cal cal, String dinExtDes, Float dinExtLimInf, Float dinExtLimSup, Integer dinExtOrdPre, Float dinExtPto, Float dinExtWoe, String dinExtDesLar, Set cliMtas) {
       this.dinExtId = dinExtId;
       this.cal = cal;
       this.dinExtDes = dinExtDes;
       this.dinExtLimInf = dinExtLimInf;
       this.dinExtLimSup = dinExtLimSup;
       this.dinExtOrdPre = dinExtOrdPre;
       this.dinExtPto = dinExtPto;
       this.dinExtWoe = dinExtWoe;
       this.dinExtDesLar = dinExtDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getDinExtId() {
        return this.dinExtId;
    }
    
    public void setDinExtId(int dinExtId) {
        this.dinExtId = dinExtId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getDinExtDes() {
        return this.dinExtDes;
    }
    
    public void setDinExtDes(String dinExtDes) {
        this.dinExtDes = dinExtDes;
    }
    public Float getDinExtLimInf() {
        return this.dinExtLimInf;
    }
    
    public void setDinExtLimInf(Float dinExtLimInf) {
        this.dinExtLimInf = dinExtLimInf;
    }
    public Float getDinExtLimSup() {
        return this.dinExtLimSup;
    }
    
    public void setDinExtLimSup(Float dinExtLimSup) {
        this.dinExtLimSup = dinExtLimSup;
    }
    public Integer getDinExtOrdPre() {
        return this.dinExtOrdPre;
    }
    
    public void setDinExtOrdPre(Integer dinExtOrdPre) {
        this.dinExtOrdPre = dinExtOrdPre;
    }
    public Float getDinExtPto() {
        return this.dinExtPto;
    }
    
    public void setDinExtPto(Float dinExtPto) {
        this.dinExtPto = dinExtPto;
    }
    public Float getDinExtWoe() {
        return this.dinExtWoe;
    }
    
    public void setDinExtWoe(Float dinExtWoe) {
        this.dinExtWoe = dinExtWoe;
    }
    public String getDinExtDesLar() {
        return this.dinExtDesLar;
    }
    
    public void setDinExtDesLar(String dinExtDesLar) {
        this.dinExtDesLar = dinExtDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


