package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Eda generated by hbm2java
 */
public class Eda  implements java.io.Serializable {


     private int edaId;
     private Cal cal;
     private String edaDes;
     private Float edaLimInf;
     private Float edaLimSup;
     private Integer edaOrdPre;
     private Float edaPto;
     private Float edaWoe;
     private String edaDesLar;
     private Set cliBhrs = new HashSet(0);

    public Eda() {
    }

	
    public Eda(int edaId) {
        this.edaId = edaId;
    }
    public Eda(int edaId, Cal cal, String edaDes, Float edaLimInf, Float edaLimSup, Integer edaOrdPre, Float edaPto, Float edaWoe, String edaDesLar, Set cliBhrs) {
       this.edaId = edaId;
       this.cal = cal;
       this.edaDes = edaDes;
       this.edaLimInf = edaLimInf;
       this.edaLimSup = edaLimSup;
       this.edaOrdPre = edaOrdPre;
       this.edaPto = edaPto;
       this.edaWoe = edaWoe;
       this.edaDesLar = edaDesLar;
       this.cliBhrs = cliBhrs;
    }
   
    public int getEdaId() {
        return this.edaId;
    }
    
    public void setEdaId(int edaId) {
        this.edaId = edaId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getEdaDes() {
        return this.edaDes;
    }
    
    public void setEdaDes(String edaDes) {
        this.edaDes = edaDes;
    }
    public Float getEdaLimInf() {
        return this.edaLimInf;
    }
    
    public void setEdaLimInf(Float edaLimInf) {
        this.edaLimInf = edaLimInf;
    }
    public Float getEdaLimSup() {
        return this.edaLimSup;
    }
    
    public void setEdaLimSup(Float edaLimSup) {
        this.edaLimSup = edaLimSup;
    }
    public Integer getEdaOrdPre() {
        return this.edaOrdPre;
    }
    
    public void setEdaOrdPre(Integer edaOrdPre) {
        this.edaOrdPre = edaOrdPre;
    }
    public Float getEdaPto() {
        return this.edaPto;
    }
    
    public void setEdaPto(Float edaPto) {
        this.edaPto = edaPto;
    }
    public Float getEdaWoe() {
        return this.edaWoe;
    }
    
    public void setEdaWoe(Float edaWoe) {
        this.edaWoe = edaWoe;
    }
    public String getEdaDesLar() {
        return this.edaDesLar;
    }
    
    public void setEdaDesLar(String edaDesLar) {
        this.edaDesLar = edaDesLar;
    }
    public Set getCliBhrs() {
        return this.cliBhrs;
    }
    
    public void setCliBhrs(Set cliBhrs) {
        this.cliBhrs = cliBhrs;
    }




}


