package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * FreDin generated by hbm2java
 */
public class FreDin  implements java.io.Serializable {


     private int freDinId;
     private Cal cal;
     private String freDinDes;
     private Float freDinLimInf;
     private Float freDinLimSup;
     private Integer freDinOrdPre;
     private Float freDinPto;
     private Float freDinWoe;
     private String freDinDesLar;

    public FreDin() {
    }

	
    public FreDin(int freDinId) {
        this.freDinId = freDinId;
    }
    public FreDin(int freDinId, Cal cal, String freDinDes, Float freDinLimInf, Float freDinLimSup, Integer freDinOrdPre, Float freDinPto, Float freDinWoe, String freDinDesLar) {
       this.freDinId = freDinId;
       this.cal = cal;
       this.freDinDes = freDinDes;
       this.freDinLimInf = freDinLimInf;
       this.freDinLimSup = freDinLimSup;
       this.freDinOrdPre = freDinOrdPre;
       this.freDinPto = freDinPto;
       this.freDinWoe = freDinWoe;
       this.freDinDesLar = freDinDesLar;
    }
   
    public int getFreDinId() {
        return this.freDinId;
    }
    
    public void setFreDinId(int freDinId) {
        this.freDinId = freDinId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getFreDinDes() {
        return this.freDinDes;
    }
    
    public void setFreDinDes(String freDinDes) {
        this.freDinDes = freDinDes;
    }
    public Float getFreDinLimInf() {
        return this.freDinLimInf;
    }
    
    public void setFreDinLimInf(Float freDinLimInf) {
        this.freDinLimInf = freDinLimInf;
    }
    public Float getFreDinLimSup() {
        return this.freDinLimSup;
    }
    
    public void setFreDinLimSup(Float freDinLimSup) {
        this.freDinLimSup = freDinLimSup;
    }
    public Integer getFreDinOrdPre() {
        return this.freDinOrdPre;
    }
    
    public void setFreDinOrdPre(Integer freDinOrdPre) {
        this.freDinOrdPre = freDinOrdPre;
    }
    public Float getFreDinPto() {
        return this.freDinPto;
    }
    
    public void setFreDinPto(Float freDinPto) {
        this.freDinPto = freDinPto;
    }
    public Float getFreDinWoe() {
        return this.freDinWoe;
    }
    
    public void setFreDinWoe(Float freDinWoe) {
        this.freDinWoe = freDinWoe;
    }
    public String getFreDinDesLar() {
        return this.freDinDesLar;
    }
    
    public void setFreDinDesLar(String freDinDesLar) {
        this.freDinDesLar = freDinDesLar;
    }




}


