package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * FtrPpr generated by hbm2java
 */
public class FtrPpr  implements java.io.Serializable {


     private int ftrPprId;
     private String ftrPprCls;
     private Float ftrPprMes;
     private Float ftrPprFtr;
     private Set cliPprs = new HashSet(0);

    public FtrPpr() {
    }

	
    public FtrPpr(int ftrPprId) {
        this.ftrPprId = ftrPprId;
    }
    public FtrPpr(int ftrPprId, String ftrPprCls, Float ftrPprMes, Float ftrPprFtr, Set cliPprs) {
       this.ftrPprId = ftrPprId;
       this.ftrPprCls = ftrPprCls;
       this.ftrPprMes = ftrPprMes;
       this.ftrPprFtr = ftrPprFtr;
       this.cliPprs = cliPprs;
    }
   
    public int getFtrPprId() {
        return this.ftrPprId;
    }
    
    public void setFtrPprId(int ftrPprId) {
        this.ftrPprId = ftrPprId;
    }
    public String getFtrPprCls() {
        return this.ftrPprCls;
    }
    
    public void setFtrPprCls(String ftrPprCls) {
        this.ftrPprCls = ftrPprCls;
    }
    public Float getFtrPprMes() {
        return this.ftrPprMes;
    }
    
    public void setFtrPprMes(Float ftrPprMes) {
        this.ftrPprMes = ftrPprMes;
    }
    public Float getFtrPprFtr() {
        return this.ftrPprFtr;
    }
    
    public void setFtrPprFtr(Float ftrPprFtr) {
        this.ftrPprFtr = ftrPprFtr;
    }
    public Set getCliPprs() {
        return this.cliPprs;
    }
    
    public void setCliPprs(Set cliPprs) {
        this.cliPprs = cliPprs;
    }




}


