package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * GtoAlm generated by hbm2java
 */
public class GtoAlm  implements java.io.Serializable {


     private int gtoAlmId;
     private Cal cal;
     private String gtoAlmDes;
     private Float gtoAlmLimInf;
     private Float gtoAlmLimSup;
     private Integer gtoAlmOrdPre;
     private Float gtoAlmPto;
     private Float gtoAlmWoe;
     private String gtoAlmDesLar;

    public GtoAlm() {
    }

	
    public GtoAlm(int gtoAlmId) {
        this.gtoAlmId = gtoAlmId;
    }
    public GtoAlm(int gtoAlmId, Cal cal, String gtoAlmDes, Float gtoAlmLimInf, Float gtoAlmLimSup, Integer gtoAlmOrdPre, Float gtoAlmPto, Float gtoAlmWoe, String gtoAlmDesLar) {
       this.gtoAlmId = gtoAlmId;
       this.cal = cal;
       this.gtoAlmDes = gtoAlmDes;
       this.gtoAlmLimInf = gtoAlmLimInf;
       this.gtoAlmLimSup = gtoAlmLimSup;
       this.gtoAlmOrdPre = gtoAlmOrdPre;
       this.gtoAlmPto = gtoAlmPto;
       this.gtoAlmWoe = gtoAlmWoe;
       this.gtoAlmDesLar = gtoAlmDesLar;
    }
   
    public int getGtoAlmId() {
        return this.gtoAlmId;
    }
    
    public void setGtoAlmId(int gtoAlmId) {
        this.gtoAlmId = gtoAlmId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoAlmDes() {
        return this.gtoAlmDes;
    }
    
    public void setGtoAlmDes(String gtoAlmDes) {
        this.gtoAlmDes = gtoAlmDes;
    }
    public Float getGtoAlmLimInf() {
        return this.gtoAlmLimInf;
    }
    
    public void setGtoAlmLimInf(Float gtoAlmLimInf) {
        this.gtoAlmLimInf = gtoAlmLimInf;
    }
    public Float getGtoAlmLimSup() {
        return this.gtoAlmLimSup;
    }
    
    public void setGtoAlmLimSup(Float gtoAlmLimSup) {
        this.gtoAlmLimSup = gtoAlmLimSup;
    }
    public Integer getGtoAlmOrdPre() {
        return this.gtoAlmOrdPre;
    }
    
    public void setGtoAlmOrdPre(Integer gtoAlmOrdPre) {
        this.gtoAlmOrdPre = gtoAlmOrdPre;
    }
    public Float getGtoAlmPto() {
        return this.gtoAlmPto;
    }
    
    public void setGtoAlmPto(Float gtoAlmPto) {
        this.gtoAlmPto = gtoAlmPto;
    }
    public Float getGtoAlmWoe() {
        return this.gtoAlmWoe;
    }
    
    public void setGtoAlmWoe(Float gtoAlmWoe) {
        this.gtoAlmWoe = gtoAlmWoe;
    }
    public String getGtoAlmDesLar() {
        return this.gtoAlmDesLar;
    }
    
    public void setGtoAlmDesLar(String gtoAlmDesLar) {
        this.gtoAlmDesLar = gtoAlmDesLar;
    }




}


