package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * GtoDiv generated by hbm2java
 */
public class GtoDiv  implements java.io.Serializable {


     private int gtoDivId;
     private Cal cal;
     private String gtoDivDes;
     private Float gtoDivLimInf;
     private Float gtoDivLimSup;
     private Integer gtoDivOrdPre;
     private Float gtoDivPto;
     private Float gtoDivWoe;
     private String gtoDivDesLar;

    public GtoDiv() {
    }

	
    public GtoDiv(int gtoDivId) {
        this.gtoDivId = gtoDivId;
    }
    public GtoDiv(int gtoDivId, Cal cal, String gtoDivDes, Float gtoDivLimInf, Float gtoDivLimSup, Integer gtoDivOrdPre, Float gtoDivPto, Float gtoDivWoe, String gtoDivDesLar) {
       this.gtoDivId = gtoDivId;
       this.cal = cal;
       this.gtoDivDes = gtoDivDes;
       this.gtoDivLimInf = gtoDivLimInf;
       this.gtoDivLimSup = gtoDivLimSup;
       this.gtoDivOrdPre = gtoDivOrdPre;
       this.gtoDivPto = gtoDivPto;
       this.gtoDivWoe = gtoDivWoe;
       this.gtoDivDesLar = gtoDivDesLar;
    }
   
    public int getGtoDivId() {
        return this.gtoDivId;
    }
    
    public void setGtoDivId(int gtoDivId) {
        this.gtoDivId = gtoDivId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoDivDes() {
        return this.gtoDivDes;
    }
    
    public void setGtoDivDes(String gtoDivDes) {
        this.gtoDivDes = gtoDivDes;
    }
    public Float getGtoDivLimInf() {
        return this.gtoDivLimInf;
    }
    
    public void setGtoDivLimInf(Float gtoDivLimInf) {
        this.gtoDivLimInf = gtoDivLimInf;
    }
    public Float getGtoDivLimSup() {
        return this.gtoDivLimSup;
    }
    
    public void setGtoDivLimSup(Float gtoDivLimSup) {
        this.gtoDivLimSup = gtoDivLimSup;
    }
    public Integer getGtoDivOrdPre() {
        return this.gtoDivOrdPre;
    }
    
    public void setGtoDivOrdPre(Integer gtoDivOrdPre) {
        this.gtoDivOrdPre = gtoDivOrdPre;
    }
    public Float getGtoDivPto() {
        return this.gtoDivPto;
    }
    
    public void setGtoDivPto(Float gtoDivPto) {
        this.gtoDivPto = gtoDivPto;
    }
    public Float getGtoDivWoe() {
        return this.gtoDivWoe;
    }
    
    public void setGtoDivWoe(Float gtoDivWoe) {
        this.gtoDivWoe = gtoDivWoe;
    }
    public String getGtoDivDesLar() {
        return this.gtoDivDesLar;
    }
    
    public void setGtoDivDesLar(String gtoDivDesLar) {
        this.gtoDivDesLar = gtoDivDesLar;
    }




}


