package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * GtoLim generated by hbm2java
 */
public class GtoLim  implements java.io.Serializable {


     private int gtoLimId;
     private Cal cal;
     private String gtoLimDes;
     private Float gtoLimLimInf;
     private Float gtoLimLimSup;
     private Integer gtoLimOrdPre;
     private Float gtoLimPto;
     private Float gtoLimWoe;
     private String gtoLimDesLar;

    public GtoLim() {
    }

	
    public GtoLim(int gtoLimId) {
        this.gtoLimId = gtoLimId;
    }
    public GtoLim(int gtoLimId, Cal cal, String gtoLimDes, Float gtoLimLimInf, Float gtoLimLimSup, Integer gtoLimOrdPre, Float gtoLimPto, Float gtoLimWoe, String gtoLimDesLar) {
       this.gtoLimId = gtoLimId;
       this.cal = cal;
       this.gtoLimDes = gtoLimDes;
       this.gtoLimLimInf = gtoLimLimInf;
       this.gtoLimLimSup = gtoLimLimSup;
       this.gtoLimOrdPre = gtoLimOrdPre;
       this.gtoLimPto = gtoLimPto;
       this.gtoLimWoe = gtoLimWoe;
       this.gtoLimDesLar = gtoLimDesLar;
    }
   
    public int getGtoLimId() {
        return this.gtoLimId;
    }
    
    public void setGtoLimId(int gtoLimId) {
        this.gtoLimId = gtoLimId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoLimDes() {
        return this.gtoLimDes;
    }
    
    public void setGtoLimDes(String gtoLimDes) {
        this.gtoLimDes = gtoLimDes;
    }
    public Float getGtoLimLimInf() {
        return this.gtoLimLimInf;
    }
    
    public void setGtoLimLimInf(Float gtoLimLimInf) {
        this.gtoLimLimInf = gtoLimLimInf;
    }
    public Float getGtoLimLimSup() {
        return this.gtoLimLimSup;
    }
    
    public void setGtoLimLimSup(Float gtoLimLimSup) {
        this.gtoLimLimSup = gtoLimLimSup;
    }
    public Integer getGtoLimOrdPre() {
        return this.gtoLimOrdPre;
    }
    
    public void setGtoLimOrdPre(Integer gtoLimOrdPre) {
        this.gtoLimOrdPre = gtoLimOrdPre;
    }
    public Float getGtoLimPto() {
        return this.gtoLimPto;
    }
    
    public void setGtoLimPto(Float gtoLimPto) {
        this.gtoLimPto = gtoLimPto;
    }
    public Float getGtoLimWoe() {
        return this.gtoLimWoe;
    }
    
    public void setGtoLimWoe(Float gtoLimWoe) {
        this.gtoLimWoe = gtoLimWoe;
    }
    public String getGtoLimDesLar() {
        return this.gtoLimDesLar;
    }
    
    public void setGtoLimDesLar(String gtoLimDesLar) {
        this.gtoLimDesLar = gtoLimDesLar;
    }




}


