package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * GtoPer generated by hbm2java
 */
public class GtoPer  implements java.io.Serializable {


     private int gtoPerId;
     private Cal cal;
     private String gtoPerDes;
     private Float gtoPerLimInf;
     private Float gtoPerLimSup;
     private Integer gtoPerOrdPre;
     private Float gtoPerPto;
     private Float gtoPerWoe;
     private String gtoPerDesLar;

    public GtoPer() {
    }

	
    public GtoPer(int gtoPerId) {
        this.gtoPerId = gtoPerId;
    }
    public GtoPer(int gtoPerId, Cal cal, String gtoPerDes, Float gtoPerLimInf, Float gtoPerLimSup, Integer gtoPerOrdPre, Float gtoPerPto, Float gtoPerWoe, String gtoPerDesLar) {
       this.gtoPerId = gtoPerId;
       this.cal = cal;
       this.gtoPerDes = gtoPerDes;
       this.gtoPerLimInf = gtoPerLimInf;
       this.gtoPerLimSup = gtoPerLimSup;
       this.gtoPerOrdPre = gtoPerOrdPre;
       this.gtoPerPto = gtoPerPto;
       this.gtoPerWoe = gtoPerWoe;
       this.gtoPerDesLar = gtoPerDesLar;
    }
   
    public int getGtoPerId() {
        return this.gtoPerId;
    }
    
    public void setGtoPerId(int gtoPerId) {
        this.gtoPerId = gtoPerId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoPerDes() {
        return this.gtoPerDes;
    }
    
    public void setGtoPerDes(String gtoPerDes) {
        this.gtoPerDes = gtoPerDes;
    }
    public Float getGtoPerLimInf() {
        return this.gtoPerLimInf;
    }
    
    public void setGtoPerLimInf(Float gtoPerLimInf) {
        this.gtoPerLimInf = gtoPerLimInf;
    }
    public Float getGtoPerLimSup() {
        return this.gtoPerLimSup;
    }
    
    public void setGtoPerLimSup(Float gtoPerLimSup) {
        this.gtoPerLimSup = gtoPerLimSup;
    }
    public Integer getGtoPerOrdPre() {
        return this.gtoPerOrdPre;
    }
    
    public void setGtoPerOrdPre(Integer gtoPerOrdPre) {
        this.gtoPerOrdPre = gtoPerOrdPre;
    }
    public Float getGtoPerPto() {
        return this.gtoPerPto;
    }
    
    public void setGtoPerPto(Float gtoPerPto) {
        this.gtoPerPto = gtoPerPto;
    }
    public Float getGtoPerWoe() {
        return this.gtoPerWoe;
    }
    
    public void setGtoPerWoe(Float gtoPerWoe) {
        this.gtoPerWoe = gtoPerWoe;
    }
    public String getGtoPerDesLar() {
        return this.gtoPerDesLar;
    }
    
    public void setGtoPerDesLar(String gtoPerDesLar) {
        this.gtoPerDesLar = gtoPerDesLar;
    }




}


