package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * GtoRen generated by hbm2java
 */
public class GtoRen  implements java.io.Serializable {


     private int gtoRenId;
     private Cal cal;
     private String gtoRenDes;
     private Float gtoRenLimInf;
     private Float gtoRenLimSup;
     private Integer gtoRenOrdPre;
     private Float gtoRenPto;
     private Float gtoRenWoe;
     private String gtoRenDesLar;

    public GtoRen() {
    }

	
    public GtoRen(int gtoRenId) {
        this.gtoRenId = gtoRenId;
    }
    public GtoRen(int gtoRenId, Cal cal, String gtoRenDes, Float gtoRenLimInf, Float gtoRenLimSup, Integer gtoRenOrdPre, Float gtoRenPto, Float gtoRenWoe, String gtoRenDesLar) {
       this.gtoRenId = gtoRenId;
       this.cal = cal;
       this.gtoRenDes = gtoRenDes;
       this.gtoRenLimInf = gtoRenLimInf;
       this.gtoRenLimSup = gtoRenLimSup;
       this.gtoRenOrdPre = gtoRenOrdPre;
       this.gtoRenPto = gtoRenPto;
       this.gtoRenWoe = gtoRenWoe;
       this.gtoRenDesLar = gtoRenDesLar;
    }
   
    public int getGtoRenId() {
        return this.gtoRenId;
    }
    
    public void setGtoRenId(int gtoRenId) {
        this.gtoRenId = gtoRenId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoRenDes() {
        return this.gtoRenDes;
    }
    
    public void setGtoRenDes(String gtoRenDes) {
        this.gtoRenDes = gtoRenDes;
    }
    public Float getGtoRenLimInf() {
        return this.gtoRenLimInf;
    }
    
    public void setGtoRenLimInf(Float gtoRenLimInf) {
        this.gtoRenLimInf = gtoRenLimInf;
    }
    public Float getGtoRenLimSup() {
        return this.gtoRenLimSup;
    }
    
    public void setGtoRenLimSup(Float gtoRenLimSup) {
        this.gtoRenLimSup = gtoRenLimSup;
    }
    public Integer getGtoRenOrdPre() {
        return this.gtoRenOrdPre;
    }
    
    public void setGtoRenOrdPre(Integer gtoRenOrdPre) {
        this.gtoRenOrdPre = gtoRenOrdPre;
    }
    public Float getGtoRenPto() {
        return this.gtoRenPto;
    }
    
    public void setGtoRenPto(Float gtoRenPto) {
        this.gtoRenPto = gtoRenPto;
    }
    public Float getGtoRenWoe() {
        return this.gtoRenWoe;
    }
    
    public void setGtoRenWoe(Float gtoRenWoe) {
        this.gtoRenWoe = gtoRenWoe;
    }
    public String getGtoRenDesLar() {
        return this.gtoRenDesLar;
    }
    
    public void setGtoRenDesLar(String gtoRenDesLar) {
        this.gtoRenDesLar = gtoRenDesLar;
    }




}


