package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * GtoSab generated by hbm2java
 */
public class GtoSab  implements java.io.Serializable {


     private int gtoSabId;
     private Cal cal;
     private String gtoSabDes;
     private Float gtoSabLimInf;
     private Float gtoSabLimSup;
     private Integer gtoSabOrdPre;
     private Float gtoSabPto;
     private Float gtoSabWoe;
     private String gtoSabDesLar;

    public GtoSab() {
    }

	
    public GtoSab(int gtoSabId) {
        this.gtoSabId = gtoSabId;
    }
    public GtoSab(int gtoSabId, Cal cal, String gtoSabDes, Float gtoSabLimInf, Float gtoSabLimSup, Integer gtoSabOrdPre, Float gtoSabPto, Float gtoSabWoe, String gtoSabDesLar) {
       this.gtoSabId = gtoSabId;
       this.cal = cal;
       this.gtoSabDes = gtoSabDes;
       this.gtoSabLimInf = gtoSabLimInf;
       this.gtoSabLimSup = gtoSabLimSup;
       this.gtoSabOrdPre = gtoSabOrdPre;
       this.gtoSabPto = gtoSabPto;
       this.gtoSabWoe = gtoSabWoe;
       this.gtoSabDesLar = gtoSabDesLar;
    }
   
    public int getGtoSabId() {
        return this.gtoSabId;
    }
    
    public void setGtoSabId(int gtoSabId) {
        this.gtoSabId = gtoSabId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoSabDes() {
        return this.gtoSabDes;
    }
    
    public void setGtoSabDes(String gtoSabDes) {
        this.gtoSabDes = gtoSabDes;
    }
    public Float getGtoSabLimInf() {
        return this.gtoSabLimInf;
    }
    
    public void setGtoSabLimInf(Float gtoSabLimInf) {
        this.gtoSabLimInf = gtoSabLimInf;
    }
    public Float getGtoSabLimSup() {
        return this.gtoSabLimSup;
    }
    
    public void setGtoSabLimSup(Float gtoSabLimSup) {
        this.gtoSabLimSup = gtoSabLimSup;
    }
    public Integer getGtoSabOrdPre() {
        return this.gtoSabOrdPre;
    }
    
    public void setGtoSabOrdPre(Integer gtoSabOrdPre) {
        this.gtoSabOrdPre = gtoSabOrdPre;
    }
    public Float getGtoSabPto() {
        return this.gtoSabPto;
    }
    
    public void setGtoSabPto(Float gtoSabPto) {
        this.gtoSabPto = gtoSabPto;
    }
    public Float getGtoSabWoe() {
        return this.gtoSabWoe;
    }
    
    public void setGtoSabWoe(Float gtoSabWoe) {
        this.gtoSabWoe = gtoSabWoe;
    }
    public String getGtoSabDesLar() {
        return this.gtoSabDesLar;
    }
    
    public void setGtoSabDesLar(String gtoSabDesLar) {
        this.gtoSabDesLar = gtoSabDesLar;
    }




}


