package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * GtoSot generated by hbm2java
 */
public class GtoSot  implements java.io.Serializable {


     private int gtoSotId;
     private Cal cal;
     private String gtoSotDes;
     private Float gtoSotLimInf;
     private Float gtoSotLimSup;
     private Integer gtoSotOrdPre;
     private Float gtoSotPto;
     private Float gtoSotWoe;
     private String gtoSotDesLar;

    public GtoSot() {
    }

	
    public GtoSot(int gtoSotId) {
        this.gtoSotId = gtoSotId;
    }
    public GtoSot(int gtoSotId, Cal cal, String gtoSotDes, Float gtoSotLimInf, Float gtoSotLimSup, Integer gtoSotOrdPre, Float gtoSotPto, Float gtoSotWoe, String gtoSotDesLar) {
       this.gtoSotId = gtoSotId;
       this.cal = cal;
       this.gtoSotDes = gtoSotDes;
       this.gtoSotLimInf = gtoSotLimInf;
       this.gtoSotLimSup = gtoSotLimSup;
       this.gtoSotOrdPre = gtoSotOrdPre;
       this.gtoSotPto = gtoSotPto;
       this.gtoSotWoe = gtoSotWoe;
       this.gtoSotDesLar = gtoSotDesLar;
    }
   
    public int getGtoSotId() {
        return this.gtoSotId;
    }
    
    public void setGtoSotId(int gtoSotId) {
        this.gtoSotId = gtoSotId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoSotDes() {
        return this.gtoSotDes;
    }
    
    public void setGtoSotDes(String gtoSotDes) {
        this.gtoSotDes = gtoSotDes;
    }
    public Float getGtoSotLimInf() {
        return this.gtoSotLimInf;
    }
    
    public void setGtoSotLimInf(Float gtoSotLimInf) {
        this.gtoSotLimInf = gtoSotLimInf;
    }
    public Float getGtoSotLimSup() {
        return this.gtoSotLimSup;
    }
    
    public void setGtoSotLimSup(Float gtoSotLimSup) {
        this.gtoSotLimSup = gtoSotLimSup;
    }
    public Integer getGtoSotOrdPre() {
        return this.gtoSotOrdPre;
    }
    
    public void setGtoSotOrdPre(Integer gtoSotOrdPre) {
        this.gtoSotOrdPre = gtoSotOrdPre;
    }
    public Float getGtoSotPto() {
        return this.gtoSotPto;
    }
    
    public void setGtoSotPto(Float gtoSotPto) {
        this.gtoSotPto = gtoSotPto;
    }
    public Float getGtoSotWoe() {
        return this.gtoSotWoe;
    }
    
    public void setGtoSotWoe(Float gtoSotWoe) {
        this.gtoSotWoe = gtoSotWoe;
    }
    public String getGtoSotDesLar() {
        return this.gtoSotDesLar;
    }
    
    public void setGtoSotDesLar(String gtoSotDesLar) {
        this.gtoSotDesLar = gtoSotDesLar;
    }




}


