package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * GtoVes generated by hbm2java
 */
public class GtoVes  implements java.io.Serializable {


     private int gtoVesId;
     private Cal cal;
     private String gtoVesDes;
     private Float gtoVesLimInf;
     private Float gtoVesLimSup;
     private Integer gtoVesOrdPre;
     private Float gtoVesPto;
     private Float gtoVesWoe;
     private String gtoVesDesLar;

    public GtoVes() {
    }

	
    public GtoVes(int gtoVesId) {
        this.gtoVesId = gtoVesId;
    }
    public GtoVes(int gtoVesId, Cal cal, String gtoVesDes, Float gtoVesLimInf, Float gtoVesLimSup, Integer gtoVesOrdPre, Float gtoVesPto, Float gtoVesWoe, String gtoVesDesLar) {
       this.gtoVesId = gtoVesId;
       this.cal = cal;
       this.gtoVesDes = gtoVesDes;
       this.gtoVesLimInf = gtoVesLimInf;
       this.gtoVesLimSup = gtoVesLimSup;
       this.gtoVesOrdPre = gtoVesOrdPre;
       this.gtoVesPto = gtoVesPto;
       this.gtoVesWoe = gtoVesWoe;
       this.gtoVesDesLar = gtoVesDesLar;
    }
   
    public int getGtoVesId() {
        return this.gtoVesId;
    }
    
    public void setGtoVesId(int gtoVesId) {
        this.gtoVesId = gtoVesId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoVesDes() {
        return this.gtoVesDes;
    }
    
    public void setGtoVesDes(String gtoVesDes) {
        this.gtoVesDes = gtoVesDes;
    }
    public Float getGtoVesLimInf() {
        return this.gtoVesLimInf;
    }
    
    public void setGtoVesLimInf(Float gtoVesLimInf) {
        this.gtoVesLimInf = gtoVesLimInf;
    }
    public Float getGtoVesLimSup() {
        return this.gtoVesLimSup;
    }
    
    public void setGtoVesLimSup(Float gtoVesLimSup) {
        this.gtoVesLimSup = gtoVesLimSup;
    }
    public Integer getGtoVesOrdPre() {
        return this.gtoVesOrdPre;
    }
    
    public void setGtoVesOrdPre(Integer gtoVesOrdPre) {
        this.gtoVesOrdPre = gtoVesOrdPre;
    }
    public Float getGtoVesPto() {
        return this.gtoVesPto;
    }
    
    public void setGtoVesPto(Float gtoVesPto) {
        this.gtoVesPto = gtoVesPto;
    }
    public Float getGtoVesWoe() {
        return this.gtoVesWoe;
    }
    
    public void setGtoVesWoe(Float gtoVesWoe) {
        this.gtoVesWoe = gtoVesWoe;
    }
    public String getGtoVesDesLar() {
        return this.gtoVesDesLar;
    }
    
    public void setGtoVesDesLar(String gtoVesDesLar) {
        this.gtoVesDesLar = gtoVesDesLar;
    }




}


