package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ing generated by hbm2java
 */
public class Ing  implements java.io.Serializable {


     private int ingId;
     private Cal cal;
     private String ingDes;
     private Float ingLimInf;
     private Float ingLimSup;
     private Integer ingOrdPre;
     private Float ingPto;
     private Float ingWoe;
     private String ingDesLar;
     private Set cliMtas = new HashSet(0);

    public Ing() {
    }

	
    public Ing(int ingId) {
        this.ingId = ingId;
    }
    public Ing(int ingId, Cal cal, String ingDes, Float ingLimInf, Float ingLimSup, Integer ingOrdPre, Float ingPto, Float ingWoe, String ingDesLar, Set cliMtas) {
       this.ingId = ingId;
       this.cal = cal;
       this.ingDes = ingDes;
       this.ingLimInf = ingLimInf;
       this.ingLimSup = ingLimSup;
       this.ingOrdPre = ingOrdPre;
       this.ingPto = ingPto;
       this.ingWoe = ingWoe;
       this.ingDesLar = ingDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getIngId() {
        return this.ingId;
    }
    
    public void setIngId(int ingId) {
        this.ingId = ingId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getIngDes() {
        return this.ingDes;
    }
    
    public void setIngDes(String ingDes) {
        this.ingDes = ingDes;
    }
    public Float getIngLimInf() {
        return this.ingLimInf;
    }
    
    public void setIngLimInf(Float ingLimInf) {
        this.ingLimInf = ingLimInf;
    }
    public Float getIngLimSup() {
        return this.ingLimSup;
    }
    
    public void setIngLimSup(Float ingLimSup) {
        this.ingLimSup = ingLimSup;
    }
    public Integer getIngOrdPre() {
        return this.ingOrdPre;
    }
    
    public void setIngOrdPre(Integer ingOrdPre) {
        this.ingOrdPre = ingOrdPre;
    }
    public Float getIngPto() {
        return this.ingPto;
    }
    
    public void setIngPto(Float ingPto) {
        this.ingPto = ingPto;
    }
    public Float getIngWoe() {
        return this.ingWoe;
    }
    
    public void setIngWoe(Float ingWoe) {
        this.ingWoe = ingWoe;
    }
    public String getIngDesLar() {
        return this.ingDesLar;
    }
    
    public void setIngDesLar(String ingDesLar) {
        this.ingDesLar = ingDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


