package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * MejPar generated by hbm2java
 */
public class MejPar  implements java.io.Serializable {


     private int mejParId;
     private Cal cal;
     private String mejParDes;
     private Float mejParLimInf;
     private Float mejParLimSup;
     private Integer mejParOrdPre;
     private Float mejParPto;
     private Float mejParWoe;
     private String mejParDesLar;

    public MejPar() {
    }

	
    public MejPar(int mejParId) {
        this.mejParId = mejParId;
    }
    public MejPar(int mejParId, Cal cal, String mejParDes, Float mejParLimInf, Float mejParLimSup, Integer mejParOrdPre, Float mejParPto, Float mejParWoe, String mejParDesLar) {
       this.mejParId = mejParId;
       this.cal = cal;
       this.mejParDes = mejParDes;
       this.mejParLimInf = mejParLimInf;
       this.mejParLimSup = mejParLimSup;
       this.mejParOrdPre = mejParOrdPre;
       this.mejParPto = mejParPto;
       this.mejParWoe = mejParWoe;
       this.mejParDesLar = mejParDesLar;
    }
   
    public int getMejParId() {
        return this.mejParId;
    }
    
    public void setMejParId(int mejParId) {
        this.mejParId = mejParId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getMejParDes() {
        return this.mejParDes;
    }
    
    public void setMejParDes(String mejParDes) {
        this.mejParDes = mejParDes;
    }
    public Float getMejParLimInf() {
        return this.mejParLimInf;
    }
    
    public void setMejParLimInf(Float mejParLimInf) {
        this.mejParLimInf = mejParLimInf;
    }
    public Float getMejParLimSup() {
        return this.mejParLimSup;
    }
    
    public void setMejParLimSup(Float mejParLimSup) {
        this.mejParLimSup = mejParLimSup;
    }
    public Integer getMejParOrdPre() {
        return this.mejParOrdPre;
    }
    
    public void setMejParOrdPre(Integer mejParOrdPre) {
        this.mejParOrdPre = mejParOrdPre;
    }
    public Float getMejParPto() {
        return this.mejParPto;
    }
    
    public void setMejParPto(Float mejParPto) {
        this.mejParPto = mejParPto;
    }
    public Float getMejParWoe() {
        return this.mejParWoe;
    }
    
    public void setMejParWoe(Float mejParWoe) {
        this.mejParWoe = mejParWoe;
    }
    public String getMejParDesLar() {
        return this.mejParDesLar;
    }
    
    public void setMejParDesLar(String mejParDesLar) {
        this.mejParDesLar = mejParDesLar;
    }




}


