package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Mig generated by hbm2java
 */
public class Mig  implements java.io.Serializable {


     private int migId;
     private Cal cal;
     private String migDes;
     private Float migLimInf;
     private Float migLimSup;
     private Integer migOrdPre;
     private Float migPto;
     private Float migWoe;
     private String migDesLar;
     private Set cliMtas = new HashSet(0);

    public Mig() {
    }

	
    public Mig(int migId) {
        this.migId = migId;
    }
    public Mig(int migId, Cal cal, String migDes, Float migLimInf, Float migLimSup, Integer migOrdPre, Float migPto, Float migWoe, String migDesLar, Set cliMtas) {
       this.migId = migId;
       this.cal = cal;
       this.migDes = migDes;
       this.migLimInf = migLimInf;
       this.migLimSup = migLimSup;
       this.migOrdPre = migOrdPre;
       this.migPto = migPto;
       this.migWoe = migWoe;
       this.migDesLar = migDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getMigId() {
        return this.migId;
    }
    
    public void setMigId(int migId) {
        this.migId = migId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getMigDes() {
        return this.migDes;
    }
    
    public void setMigDes(String migDes) {
        this.migDes = migDes;
    }
    public Float getMigLimInf() {
        return this.migLimInf;
    }
    
    public void setMigLimInf(Float migLimInf) {
        this.migLimInf = migLimInf;
    }
    public Float getMigLimSup() {
        return this.migLimSup;
    }
    
    public void setMigLimSup(Float migLimSup) {
        this.migLimSup = migLimSup;
    }
    public Integer getMigOrdPre() {
        return this.migOrdPre;
    }
    
    public void setMigOrdPre(Integer migOrdPre) {
        this.migOrdPre = migOrdPre;
    }
    public Float getMigPto() {
        return this.migPto;
    }
    
    public void setMigPto(Float migPto) {
        this.migPto = migPto;
    }
    public Float getMigWoe() {
        return this.migWoe;
    }
    
    public void setMigWoe(Float migWoe) {
        this.migWoe = migWoe;
    }
    public String getMigDesLar() {
        return this.migDesLar;
    }
    
    public void setMigDesLar(String migDesLar) {
        this.migDesLar = migDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


