package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * Mov generated by hbm2java
 */
public class Mov  implements java.io.Serializable {


     private int movId;
     private Cal cal;
     private String movDes;
     private Float movLimInf;
     private Float movLimSup;
     private Integer movOrdPre;
     private Float movPto;
     private Float movWoe;
     private String movDesLar;

    public Mov() {
    }

	
    public Mov(int movId) {
        this.movId = movId;
    }
    public Mov(int movId, Cal cal, String movDes, Float movLimInf, Float movLimSup, Integer movOrdPre, Float movPto, Float movWoe, String movDesLar) {
       this.movId = movId;
       this.cal = cal;
       this.movDes = movDes;
       this.movLimInf = movLimInf;
       this.movLimSup = movLimSup;
       this.movOrdPre = movOrdPre;
       this.movPto = movPto;
       this.movWoe = movWoe;
       this.movDesLar = movDesLar;
    }
   
    public int getMovId() {
        return this.movId;
    }
    
    public void setMovId(int movId) {
        this.movId = movId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getMovDes() {
        return this.movDes;
    }
    
    public void setMovDes(String movDes) {
        this.movDes = movDes;
    }
    public Float getMovLimInf() {
        return this.movLimInf;
    }
    
    public void setMovLimInf(Float movLimInf) {
        this.movLimInf = movLimInf;
    }
    public Float getMovLimSup() {
        return this.movLimSup;
    }
    
    public void setMovLimSup(Float movLimSup) {
        this.movLimSup = movLimSup;
    }
    public Integer getMovOrdPre() {
        return this.movOrdPre;
    }
    
    public void setMovOrdPre(Integer movOrdPre) {
        this.movOrdPre = movOrdPre;
    }
    public Float getMovPto() {
        return this.movPto;
    }
    
    public void setMovPto(Float movPto) {
        this.movPto = movPto;
    }
    public Float getMovWoe() {
        return this.movWoe;
    }
    
    public void setMovWoe(Float movWoe) {
        this.movWoe = movWoe;
    }
    public String getMovDesLar() {
        return this.movDesLar;
    }
    
    public void setMovDesLar(String movDesLar) {
        this.movDesLar = movDesLar;
    }




}


