package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * NumCre generated by hbm2java
 */
public class NumCre  implements java.io.Serializable {


     private int numCreId;
     private Cal cal;
     private String numCreDes;
     private Float numCreLimInf;
     private Float numCreLimSup;
     private Integer numCreOrdPre;
     private Float numCrePto;
     private Float numCreWoe;
     private String numCreDesLar;

    public NumCre() {
    }

	
    public NumCre(int numCreId) {
        this.numCreId = numCreId;
    }
    public NumCre(int numCreId, Cal cal, String numCreDes, Float numCreLimInf, Float numCreLimSup, Integer numCreOrdPre, Float numCrePto, Float numCreWoe, String numCreDesLar) {
       this.numCreId = numCreId;
       this.cal = cal;
       this.numCreDes = numCreDes;
       this.numCreLimInf = numCreLimInf;
       this.numCreLimSup = numCreLimSup;
       this.numCreOrdPre = numCreOrdPre;
       this.numCrePto = numCrePto;
       this.numCreWoe = numCreWoe;
       this.numCreDesLar = numCreDesLar;
    }
   
    public int getNumCreId() {
        return this.numCreId;
    }
    
    public void setNumCreId(int numCreId) {
        this.numCreId = numCreId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getNumCreDes() {
        return this.numCreDes;
    }
    
    public void setNumCreDes(String numCreDes) {
        this.numCreDes = numCreDes;
    }
    public Float getNumCreLimInf() {
        return this.numCreLimInf;
    }
    
    public void setNumCreLimInf(Float numCreLimInf) {
        this.numCreLimInf = numCreLimInf;
    }
    public Float getNumCreLimSup() {
        return this.numCreLimSup;
    }
    
    public void setNumCreLimSup(Float numCreLimSup) {
        this.numCreLimSup = numCreLimSup;
    }
    public Integer getNumCreOrdPre() {
        return this.numCreOrdPre;
    }
    
    public void setNumCreOrdPre(Integer numCreOrdPre) {
        this.numCreOrdPre = numCreOrdPre;
    }
    public Float getNumCrePto() {
        return this.numCrePto;
    }
    
    public void setNumCrePto(Float numCrePto) {
        this.numCrePto = numCrePto;
    }
    public Float getNumCreWoe() {
        return this.numCreWoe;
    }
    
    public void setNumCreWoe(Float numCreWoe) {
        this.numCreWoe = numCreWoe;
    }
    public String getNumCreDesLar() {
        return this.numCreDesLar;
    }
    
    public void setNumCreDesLar(String numCreDesLar) {
        this.numCreDesLar = numCreDesLar;
    }




}


