package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * OpnMap generated by hbm2java
 */
public class OpnMap  implements java.io.Serializable {


     private int opnMapId;
     private Cal cal;
     private String opnMapDes;
     private Float opnMapLimInf;
     private Float opnMapLimSup;
     private Integer opnMapOrdPre;
     private Float opnMapPto;
     private Float opnMapWoe;
     private String opnMapDesLar;

    public OpnMap() {
    }

	
    public OpnMap(int opnMapId) {
        this.opnMapId = opnMapId;
    }
    public OpnMap(int opnMapId, Cal cal, String opnMapDes, Float opnMapLimInf, Float opnMapLimSup, Integer opnMapOrdPre, Float opnMapPto, Float opnMapWoe, String opnMapDesLar) {
       this.opnMapId = opnMapId;
       this.cal = cal;
       this.opnMapDes = opnMapDes;
       this.opnMapLimInf = opnMapLimInf;
       this.opnMapLimSup = opnMapLimSup;
       this.opnMapOrdPre = opnMapOrdPre;
       this.opnMapPto = opnMapPto;
       this.opnMapWoe = opnMapWoe;
       this.opnMapDesLar = opnMapDesLar;
    }
   
    public int getOpnMapId() {
        return this.opnMapId;
    }
    
    public void setOpnMapId(int opnMapId) {
        this.opnMapId = opnMapId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getOpnMapDes() {
        return this.opnMapDes;
    }
    
    public void setOpnMapDes(String opnMapDes) {
        this.opnMapDes = opnMapDes;
    }
    public Float getOpnMapLimInf() {
        return this.opnMapLimInf;
    }
    
    public void setOpnMapLimInf(Float opnMapLimInf) {
        this.opnMapLimInf = opnMapLimInf;
    }
    public Float getOpnMapLimSup() {
        return this.opnMapLimSup;
    }
    
    public void setOpnMapLimSup(Float opnMapLimSup) {
        this.opnMapLimSup = opnMapLimSup;
    }
    public Integer getOpnMapOrdPre() {
        return this.opnMapOrdPre;
    }
    
    public void setOpnMapOrdPre(Integer opnMapOrdPre) {
        this.opnMapOrdPre = opnMapOrdPre;
    }
    public Float getOpnMapPto() {
        return this.opnMapPto;
    }
    
    public void setOpnMapPto(Float opnMapPto) {
        this.opnMapPto = opnMapPto;
    }
    public Float getOpnMapWoe() {
        return this.opnMapWoe;
    }
    
    public void setOpnMapWoe(Float opnMapWoe) {
        this.opnMapWoe = opnMapWoe;
    }
    public String getOpnMapDesLar() {
        return this.opnMapDesLar;
    }
    
    public void setOpnMapDesLar(String opnMapDesLar) {
        this.opnMapDesLar = opnMapDesLar;
    }




}


