package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * ParAso generated by hbm2java
 */
public class ParAso  implements java.io.Serializable {


     private int parAsoId;
     private Integer calId;
     private String parAsoDes;
     private Float parAsoLimInf;
     private Float parAsoLimSup;
     private Integer parAsoOrdPre;
     private Float parAsoPto;
     private Float parAsoWoe;
     private String parAsoDesLar;

    public ParAso() {
    }

	
    public ParAso(int parAsoId) {
        this.parAsoId = parAsoId;
    }
    public ParAso(int parAsoId, Integer calId, String parAsoDes, Float parAsoLimInf, Float parAsoLimSup, Integer parAsoOrdPre, Float parAsoPto, Float parAsoWoe, String parAsoDesLar) {
       this.parAsoId = parAsoId;
       this.calId = calId;
       this.parAsoDes = parAsoDes;
       this.parAsoLimInf = parAsoLimInf;
       this.parAsoLimSup = parAsoLimSup;
       this.parAsoOrdPre = parAsoOrdPre;
       this.parAsoPto = parAsoPto;
       this.parAsoWoe = parAsoWoe;
       this.parAsoDesLar = parAsoDesLar;
    }
   
    public int getParAsoId() {
        return this.parAsoId;
    }
    
    public void setParAsoId(int parAsoId) {
        this.parAsoId = parAsoId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getParAsoDes() {
        return this.parAsoDes;
    }
    
    public void setParAsoDes(String parAsoDes) {
        this.parAsoDes = parAsoDes;
    }
    public Float getParAsoLimInf() {
        return this.parAsoLimInf;
    }
    
    public void setParAsoLimInf(Float parAsoLimInf) {
        this.parAsoLimInf = parAsoLimInf;
    }
    public Float getParAsoLimSup() {
        return this.parAsoLimSup;
    }
    
    public void setParAsoLimSup(Float parAsoLimSup) {
        this.parAsoLimSup = parAsoLimSup;
    }
    public Integer getParAsoOrdPre() {
        return this.parAsoOrdPre;
    }
    
    public void setParAsoOrdPre(Integer parAsoOrdPre) {
        this.parAsoOrdPre = parAsoOrdPre;
    }
    public Float getParAsoPto() {
        return this.parAsoPto;
    }
    
    public void setParAsoPto(Float parAsoPto) {
        this.parAsoPto = parAsoPto;
    }
    public Float getParAsoWoe() {
        return this.parAsoWoe;
    }
    
    public void setParAsoWoe(Float parAsoWoe) {
        this.parAsoWoe = parAsoWoe;
    }
    public String getParAsoDesLar() {
        return this.parAsoDesLar;
    }
    
    public void setParAsoDesLar(String parAsoDesLar) {
        this.parAsoDesLar = parAsoDesLar;
    }




}


