package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ParPlt generated by hbm2java
 */
public class ParPlt  implements java.io.Serializable {


     private int parPltId;
     private Integer calId;
     private String parPltDes;
     private Float parPltLimInf;
     private Float parPltLimSup;
     private Integer parPltOrdPre;
     private Float parPltPto;
     private Float parPltWoe;
     private String parPltDesLar;
     private Set cliMtas = new HashSet(0);

    public ParPlt() {
    }

	
    public ParPlt(int parPltId) {
        this.parPltId = parPltId;
    }
    public ParPlt(int parPltId, Integer calId, String parPltDes, Float parPltLimInf, Float parPltLimSup, Integer parPltOrdPre, Float parPltPto, Float parPltWoe, String parPltDesLar, Set cliMtas) {
       this.parPltId = parPltId;
       this.calId = calId;
       this.parPltDes = parPltDes;
       this.parPltLimInf = parPltLimInf;
       this.parPltLimSup = parPltLimSup;
       this.parPltOrdPre = parPltOrdPre;
       this.parPltPto = parPltPto;
       this.parPltWoe = parPltWoe;
       this.parPltDesLar = parPltDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getParPltId() {
        return this.parPltId;
    }
    
    public void setParPltId(int parPltId) {
        this.parPltId = parPltId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getParPltDes() {
        return this.parPltDes;
    }
    
    public void setParPltDes(String parPltDes) {
        this.parPltDes = parPltDes;
    }
    public Float getParPltLimInf() {
        return this.parPltLimInf;
    }
    
    public void setParPltLimInf(Float parPltLimInf) {
        this.parPltLimInf = parPltLimInf;
    }
    public Float getParPltLimSup() {
        return this.parPltLimSup;
    }
    
    public void setParPltLimSup(Float parPltLimSup) {
        this.parPltLimSup = parPltLimSup;
    }
    public Integer getParPltOrdPre() {
        return this.parPltOrdPre;
    }
    
    public void setParPltOrdPre(Integer parPltOrdPre) {
        this.parPltOrdPre = parPltOrdPre;
    }
    public Float getParPltPto() {
        return this.parPltPto;
    }
    
    public void setParPltPto(Float parPltPto) {
        this.parPltPto = parPltPto;
    }
    public Float getParPltWoe() {
        return this.parPltWoe;
    }
    
    public void setParPltWoe(Float parPltWoe) {
        this.parPltWoe = parPltWoe;
    }
    public String getParPltDesLar() {
        return this.parPltDesLar;
    }
    
    public void setParPltDesLar(String parPltDesLar) {
        this.parPltDesLar = parPltDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


