package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * Pbm generated by hbm2java
 */
public class Pbm  implements java.io.Serializable {


     private int pbmId;
     private Integer calId;
     private String pbmDes;
     private Float pbmLimInf;
     private Float pbmLimSup;
     private Integer pbmOrdPre;
     private Float pbmPto;
     private Float pbmWoe;
     private String pbmDesLar;

    public Pbm() {
    }

	
    public Pbm(int pbmId) {
        this.pbmId = pbmId;
    }
    public Pbm(int pbmId, Integer calId, String pbmDes, Float pbmLimInf, Float pbmLimSup, Integer pbmOrdPre, Float pbmPto, Float pbmWoe, String pbmDesLar) {
       this.pbmId = pbmId;
       this.calId = calId;
       this.pbmDes = pbmDes;
       this.pbmLimInf = pbmLimInf;
       this.pbmLimSup = pbmLimSup;
       this.pbmOrdPre = pbmOrdPre;
       this.pbmPto = pbmPto;
       this.pbmWoe = pbmWoe;
       this.pbmDesLar = pbmDesLar;
    }
   
    public int getPbmId() {
        return this.pbmId;
    }
    
    public void setPbmId(int pbmId) {
        this.pbmId = pbmId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getPbmDes() {
        return this.pbmDes;
    }
    
    public void setPbmDes(String pbmDes) {
        this.pbmDes = pbmDes;
    }
    public Float getPbmLimInf() {
        return this.pbmLimInf;
    }
    
    public void setPbmLimInf(Float pbmLimInf) {
        this.pbmLimInf = pbmLimInf;
    }
    public Float getPbmLimSup() {
        return this.pbmLimSup;
    }
    
    public void setPbmLimSup(Float pbmLimSup) {
        this.pbmLimSup = pbmLimSup;
    }
    public Integer getPbmOrdPre() {
        return this.pbmOrdPre;
    }
    
    public void setPbmOrdPre(Integer pbmOrdPre) {
        this.pbmOrdPre = pbmOrdPre;
    }
    public Float getPbmPto() {
        return this.pbmPto;
    }
    
    public void setPbmPto(Float pbmPto) {
        this.pbmPto = pbmPto;
    }
    public Float getPbmWoe() {
        return this.pbmWoe;
    }
    
    public void setPbmWoe(Float pbmWoe) {
        this.pbmWoe = pbmWoe;
    }
    public String getPbmDesLar() {
        return this.pbmDesLar;
    }
    
    public void setPbmDesLar(String pbmDesLar) {
        this.pbmDesLar = pbmDesLar;
    }




}


