package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ptm generated by hbm2java
 */
public class Ptm  implements java.io.Serializable {


     private int ptmId;
     private Integer calId;
     private String ptmDes;
     private Float ptmLimInf;
     private Float ptmLimSup;
     private Integer ptmOrdPre;
     private Float ptmPto;
     private Float ptmWoe;
     private String ptmDesLar;
     private Set cliMtas = new HashSet(0);

    public Ptm() {
    }

	
    public Ptm(int ptmId) {
        this.ptmId = ptmId;
    }
    public Ptm(int ptmId, Integer calId, String ptmDes, Float ptmLimInf, Float ptmLimSup, Integer ptmOrdPre, Float ptmPto, Float ptmWoe, String ptmDesLar, Set cliMtas) {
       this.ptmId = ptmId;
       this.calId = calId;
       this.ptmDes = ptmDes;
       this.ptmLimInf = ptmLimInf;
       this.ptmLimSup = ptmLimSup;
       this.ptmOrdPre = ptmOrdPre;
       this.ptmPto = ptmPto;
       this.ptmWoe = ptmWoe;
       this.ptmDesLar = ptmDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getPtmId() {
        return this.ptmId;
    }
    
    public void setPtmId(int ptmId) {
        this.ptmId = ptmId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getPtmDes() {
        return this.ptmDes;
    }
    
    public void setPtmDes(String ptmDes) {
        this.ptmDes = ptmDes;
    }
    public Float getPtmLimInf() {
        return this.ptmLimInf;
    }
    
    public void setPtmLimInf(Float ptmLimInf) {
        this.ptmLimInf = ptmLimInf;
    }
    public Float getPtmLimSup() {
        return this.ptmLimSup;
    }
    
    public void setPtmLimSup(Float ptmLimSup) {
        this.ptmLimSup = ptmLimSup;
    }
    public Integer getPtmOrdPre() {
        return this.ptmOrdPre;
    }
    
    public void setPtmOrdPre(Integer ptmOrdPre) {
        this.ptmOrdPre = ptmOrdPre;
    }
    public Float getPtmPto() {
        return this.ptmPto;
    }
    
    public void setPtmPto(Float ptmPto) {
        this.ptmPto = ptmPto;
    }
    public Float getPtmWoe() {
        return this.ptmWoe;
    }
    
    public void setPtmWoe(Float ptmWoe) {
        this.ptmWoe = ptmWoe;
    }
    public String getPtmDesLar() {
        return this.ptmDesLar;
    }
    
    public void setPtmDesLar(String ptmDesLar) {
        this.ptmDesLar = ptmDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


