package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rel generated by hbm2java
 */
public class Rel  implements java.io.Serializable {


     private int relId;
     private Integer calId;
     private String relDes;
     private Float relLimInf;
     private Float relLimSup;
     private Integer relOrdPre;
     private Float relPto;
     private Float relWoe;
     private String relDesLar;
     private Set cliMtas = new HashSet(0);

    public Rel() {
    }

	
    public Rel(int relId) {
        this.relId = relId;
    }
    public Rel(int relId, Integer calId, String relDes, Float relLimInf, Float relLimSup, Integer relOrdPre, Float relPto, Float relWoe, String relDesLar, Set cliMtas) {
       this.relId = relId;
       this.calId = calId;
       this.relDes = relDes;
       this.relLimInf = relLimInf;
       this.relLimSup = relLimSup;
       this.relOrdPre = relOrdPre;
       this.relPto = relPto;
       this.relWoe = relWoe;
       this.relDesLar = relDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getRelId() {
        return this.relId;
    }
    
    public void setRelId(int relId) {
        this.relId = relId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getRelDes() {
        return this.relDes;
    }
    
    public void setRelDes(String relDes) {
        this.relDes = relDes;
    }
    public Float getRelLimInf() {
        return this.relLimInf;
    }
    
    public void setRelLimInf(Float relLimInf) {
        this.relLimInf = relLimInf;
    }
    public Float getRelLimSup() {
        return this.relLimSup;
    }
    
    public void setRelLimSup(Float relLimSup) {
        this.relLimSup = relLimSup;
    }
    public Integer getRelOrdPre() {
        return this.relOrdPre;
    }
    
    public void setRelOrdPre(Integer relOrdPre) {
        this.relOrdPre = relOrdPre;
    }
    public Float getRelPto() {
        return this.relPto;
    }
    
    public void setRelPto(Float relPto) {
        this.relPto = relPto;
    }
    public Float getRelWoe() {
        return this.relWoe;
    }
    
    public void setRelWoe(Float relWoe) {
        this.relWoe = relWoe;
    }
    public String getRelDesLar() {
        return this.relDesLar;
    }
    
    public void setRelDesLar(String relDesLar) {
        this.relDesLar = relDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


