package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * RelFam generated by hbm2java
 */
public class RelFam  implements java.io.Serializable {


     private int relFamId;
     private Integer calId;
     private String relFamDes;
     private Float relFamLimInf;
     private Float relFamLimSup;
     private Integer relFamOrdPre;
     private Float relFamPto;
     private Float relFamWoe;
     private String relFamDesLar;

    public RelFam() {
    }

	
    public RelFam(int relFamId) {
        this.relFamId = relFamId;
    }
    public RelFam(int relFamId, Integer calId, String relFamDes, Float relFamLimInf, Float relFamLimSup, Integer relFamOrdPre, Float relFamPto, Float relFamWoe, String relFamDesLar) {
       this.relFamId = relFamId;
       this.calId = calId;
       this.relFamDes = relFamDes;
       this.relFamLimInf = relFamLimInf;
       this.relFamLimSup = relFamLimSup;
       this.relFamOrdPre = relFamOrdPre;
       this.relFamPto = relFamPto;
       this.relFamWoe = relFamWoe;
       this.relFamDesLar = relFamDesLar;
    }
   
    public int getRelFamId() {
        return this.relFamId;
    }
    
    public void setRelFamId(int relFamId) {
        this.relFamId = relFamId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getRelFamDes() {
        return this.relFamDes;
    }
    
    public void setRelFamDes(String relFamDes) {
        this.relFamDes = relFamDes;
    }
    public Float getRelFamLimInf() {
        return this.relFamLimInf;
    }
    
    public void setRelFamLimInf(Float relFamLimInf) {
        this.relFamLimInf = relFamLimInf;
    }
    public Float getRelFamLimSup() {
        return this.relFamLimSup;
    }
    
    public void setRelFamLimSup(Float relFamLimSup) {
        this.relFamLimSup = relFamLimSup;
    }
    public Integer getRelFamOrdPre() {
        return this.relFamOrdPre;
    }
    
    public void setRelFamOrdPre(Integer relFamOrdPre) {
        this.relFamOrdPre = relFamOrdPre;
    }
    public Float getRelFamPto() {
        return this.relFamPto;
    }
    
    public void setRelFamPto(Float relFamPto) {
        this.relFamPto = relFamPto;
    }
    public Float getRelFamWoe() {
        return this.relFamWoe;
    }
    
    public void setRelFamWoe(Float relFamWoe) {
        this.relFamWoe = relFamWoe;
    }
    public String getRelFamDesLar() {
        return this.relFamDesLar;
    }
    
    public void setRelFamDesLar(String relFamDesLar) {
        this.relFamDesLar = relFamDesLar;
    }




}


