package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * RelPsiSoc generated by hbm2java
 */
public class RelPsiSoc  implements java.io.Serializable {


     private int relPsiSocId;
     private CatPsi catPsi;
     private Integer calId;
     private String relPsiSocDes;
     private Integer relPsiSocNumRes;
     private Float relPsiSocPto;
     private Float relPsiSocWoe;

    public RelPsiSoc() {
    }

	
    public RelPsiSoc(int relPsiSocId) {
        this.relPsiSocId = relPsiSocId;
    }
    public RelPsiSoc(int relPsiSocId, CatPsi catPsi, Integer calId, String relPsiSocDes, Integer relPsiSocNumRes, Float relPsiSocPto, Float relPsiSocWoe) {
       this.relPsiSocId = relPsiSocId;
       this.catPsi = catPsi;
       this.calId = calId;
       this.relPsiSocDes = relPsiSocDes;
       this.relPsiSocNumRes = relPsiSocNumRes;
       this.relPsiSocPto = relPsiSocPto;
       this.relPsiSocWoe = relPsiSocWoe;
    }
   
    public int getRelPsiSocId() {
        return this.relPsiSocId;
    }
    
    public void setRelPsiSocId(int relPsiSocId) {
        this.relPsiSocId = relPsiSocId;
    }
    public CatPsi getCatPsi() {
        return this.catPsi;
    }
    
    public void setCatPsi(CatPsi catPsi) {
        this.catPsi = catPsi;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getRelPsiSocDes() {
        return this.relPsiSocDes;
    }
    
    public void setRelPsiSocDes(String relPsiSocDes) {
        this.relPsiSocDes = relPsiSocDes;
    }
    public Integer getRelPsiSocNumRes() {
        return this.relPsiSocNumRes;
    }
    
    public void setRelPsiSocNumRes(Integer relPsiSocNumRes) {
        this.relPsiSocNumRes = relPsiSocNumRes;
    }
    public Float getRelPsiSocPto() {
        return this.relPsiSocPto;
    }
    
    public void setRelPsiSocPto(Float relPsiSocPto) {
        this.relPsiSocPto = relPsiSocPto;
    }
    public Float getRelPsiSocWoe() {
        return this.relPsiSocWoe;
    }
    
    public void setRelPsiSocWoe(Float relPsiSocWoe) {
        this.relPsiSocWoe = relPsiSocWoe;
    }




}


