package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * RngResAct generated by hbm2java
 */
public class RngResAct  implements java.io.Serializable {


     private int rngResActId;
     private Integer calId;
     private String rngResActDes;
     private Float rngResActLimInf;
     private Float rngResActLimSup;
     private Integer rngResActOrdPre;
     private Float rngResActPto;
     private Float rngResActWoe;
     private String rngResActDesLar;

    public RngResAct() {
    }

	
    public RngResAct(int rngResActId) {
        this.rngResActId = rngResActId;
    }
    public RngResAct(int rngResActId, Integer calId, String rngResActDes, Float rngResActLimInf, Float rngResActLimSup, Integer rngResActOrdPre, Float rngResActPto, Float rngResActWoe, String rngResActDesLar) {
       this.rngResActId = rngResActId;
       this.calId = calId;
       this.rngResActDes = rngResActDes;
       this.rngResActLimInf = rngResActLimInf;
       this.rngResActLimSup = rngResActLimSup;
       this.rngResActOrdPre = rngResActOrdPre;
       this.rngResActPto = rngResActPto;
       this.rngResActWoe = rngResActWoe;
       this.rngResActDesLar = rngResActDesLar;
    }
   
    public int getRngResActId() {
        return this.rngResActId;
    }
    
    public void setRngResActId(int rngResActId) {
        this.rngResActId = rngResActId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getRngResActDes() {
        return this.rngResActDes;
    }
    
    public void setRngResActDes(String rngResActDes) {
        this.rngResActDes = rngResActDes;
    }
    public Float getRngResActLimInf() {
        return this.rngResActLimInf;
    }
    
    public void setRngResActLimInf(Float rngResActLimInf) {
        this.rngResActLimInf = rngResActLimInf;
    }
    public Float getRngResActLimSup() {
        return this.rngResActLimSup;
    }
    
    public void setRngResActLimSup(Float rngResActLimSup) {
        this.rngResActLimSup = rngResActLimSup;
    }
    public Integer getRngResActOrdPre() {
        return this.rngResActOrdPre;
    }
    
    public void setRngResActOrdPre(Integer rngResActOrdPre) {
        this.rngResActOrdPre = rngResActOrdPre;
    }
    public Float getRngResActPto() {
        return this.rngResActPto;
    }
    
    public void setRngResActPto(Float rngResActPto) {
        this.rngResActPto = rngResActPto;
    }
    public Float getRngResActWoe() {
        return this.rngResActWoe;
    }
    
    public void setRngResActWoe(Float rngResActWoe) {
        this.rngResActWoe = rngResActWoe;
    }
    public String getRngResActDesLar() {
        return this.rngResActDesLar;
    }
    
    public void setRngResActDesLar(String rngResActDesLar) {
        this.rngResActDesLar = rngResActDesLar;
    }




}


