package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sex generated by hbm2java
 */
public class Sex  implements java.io.Serializable {


     private int sexId;
     private Integer calId;
     private String sexDes;
     private Float sexLimInf;
     private Float sexLimSup;
     private Integer sexOrdPre;
     private Float sexPto;
     private Float sexWoe;
     private String sexDesLar;
     private Set cliMtas = new HashSet(0);

    public Sex() {
    }

	
    public Sex(int sexId) {
        this.sexId = sexId;
    }
    public Sex(int sexId, Integer calId, String sexDes, Float sexLimInf, Float sexLimSup, Integer sexOrdPre, Float sexPto, Float sexWoe, String sexDesLar, Set cliMtas) {
       this.sexId = sexId;
       this.calId = calId;
       this.sexDes = sexDes;
       this.sexLimInf = sexLimInf;
       this.sexLimSup = sexLimSup;
       this.sexOrdPre = sexOrdPre;
       this.sexPto = sexPto;
       this.sexWoe = sexWoe;
       this.sexDesLar = sexDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getSexId() {
        return this.sexId;
    }
    
    public void setSexId(int sexId) {
        this.sexId = sexId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getSexDes() {
        return this.sexDes;
    }
    
    public void setSexDes(String sexDes) {
        this.sexDes = sexDes;
    }
    public Float getSexLimInf() {
        return this.sexLimInf;
    }
    
    public void setSexLimInf(Float sexLimInf) {
        this.sexLimInf = sexLimInf;
    }
    public Float getSexLimSup() {
        return this.sexLimSup;
    }
    
    public void setSexLimSup(Float sexLimSup) {
        this.sexLimSup = sexLimSup;
    }
    public Integer getSexOrdPre() {
        return this.sexOrdPre;
    }
    
    public void setSexOrdPre(Integer sexOrdPre) {
        this.sexOrdPre = sexOrdPre;
    }
    public Float getSexPto() {
        return this.sexPto;
    }
    
    public void setSexPto(Float sexPto) {
        this.sexPto = sexPto;
    }
    public Float getSexWoe() {
        return this.sexWoe;
    }
    
    public void setSexWoe(Float sexWoe) {
        this.sexWoe = sexWoe;
    }
    public String getSexDesLar() {
        return this.sexDesLar;
    }
    
    public void setSexDesLar(String sexDesLar) {
        this.sexDesLar = sexDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


