package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Srv generated by hbm2java
 */
public class Srv  implements java.io.Serializable {


     private int srvId;
     private Integer calId;
     private String srvDes;
     private Float srvLimInf;
     private Float srvLimSup;
     private Integer srvOrdPre;
     private Float srvPto;
     private Float srvWoe;
     private String srvDesLar;
     private Integer tipEmpId;
     private Set ocps = new HashSet(0);

    public Srv() {
    }

	
    public Srv(int srvId) {
        this.srvId = srvId;
    }
    public Srv(int srvId, Integer calId, String srvDes, Float srvLimInf, Float srvLimSup, Integer srvOrdPre, Float srvPto, Float srvWoe, String srvDesLar, Integer tipEmpId, Set ocps) {
       this.srvId = srvId;
       this.calId = calId;
       this.srvDes = srvDes;
       this.srvLimInf = srvLimInf;
       this.srvLimSup = srvLimSup;
       this.srvOrdPre = srvOrdPre;
       this.srvPto = srvPto;
       this.srvWoe = srvWoe;
       this.srvDesLar = srvDesLar;
       this.tipEmpId = tipEmpId;
       this.ocps = ocps;
    }
   
    public int getSrvId() {
        return this.srvId;
    }
    
    public void setSrvId(int srvId) {
        this.srvId = srvId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getSrvDes() {
        return this.srvDes;
    }
    
    public void setSrvDes(String srvDes) {
        this.srvDes = srvDes;
    }
    public Float getSrvLimInf() {
        return this.srvLimInf;
    }
    
    public void setSrvLimInf(Float srvLimInf) {
        this.srvLimInf = srvLimInf;
    }
    public Float getSrvLimSup() {
        return this.srvLimSup;
    }
    
    public void setSrvLimSup(Float srvLimSup) {
        this.srvLimSup = srvLimSup;
    }
    public Integer getSrvOrdPre() {
        return this.srvOrdPre;
    }
    
    public void setSrvOrdPre(Integer srvOrdPre) {
        this.srvOrdPre = srvOrdPre;
    }
    public Float getSrvPto() {
        return this.srvPto;
    }
    
    public void setSrvPto(Float srvPto) {
        this.srvPto = srvPto;
    }
    public Float getSrvWoe() {
        return this.srvWoe;
    }
    
    public void setSrvWoe(Float srvWoe) {
        this.srvWoe = srvWoe;
    }
    public String getSrvDesLar() {
        return this.srvDesLar;
    }
    
    public void setSrvDesLar(String srvDesLar) {
        this.srvDesLar = srvDesLar;
    }
    public Integer getTipEmpId() {
        return this.tipEmpId;
    }
    
    public void setTipEmpId(Integer tipEmpId) {
        this.tipEmpId = tipEmpId;
    }
    public Set getOcps() {
        return this.ocps;
    }
    
    public void setOcps(Set ocps) {
        this.ocps = ocps;
    }




}


