package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA



/**
 * SrvInd generated by hbm2java
 */
public class SrvInd  implements java.io.Serializable {


     private int srvIndId;
     private Integer calId;
     private String srvIndDes;
     private Float srvIndLimInf;
     private Float srvIndLimSup;
     private Integer srvIndOrdPre;
     private Float srvIndPto;
     private Float srvIndWoe;
     private String srvIndDesLar;

    public SrvInd() {
    }

	
    public SrvInd(int srvIndId) {
        this.srvIndId = srvIndId;
    }
    public SrvInd(int srvIndId, Integer calId, String srvIndDes, Float srvIndLimInf, Float srvIndLimSup, Integer srvIndOrdPre, Float srvIndPto, Float srvIndWoe, String srvIndDesLar) {
       this.srvIndId = srvIndId;
       this.calId = calId;
       this.srvIndDes = srvIndDes;
       this.srvIndLimInf = srvIndLimInf;
       this.srvIndLimSup = srvIndLimSup;
       this.srvIndOrdPre = srvIndOrdPre;
       this.srvIndPto = srvIndPto;
       this.srvIndWoe = srvIndWoe;
       this.srvIndDesLar = srvIndDesLar;
    }
   
    public int getSrvIndId() {
        return this.srvIndId;
    }
    
    public void setSrvIndId(int srvIndId) {
        this.srvIndId = srvIndId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getSrvIndDes() {
        return this.srvIndDes;
    }
    
    public void setSrvIndDes(String srvIndDes) {
        this.srvIndDes = srvIndDes;
    }
    public Float getSrvIndLimInf() {
        return this.srvIndLimInf;
    }
    
    public void setSrvIndLimInf(Float srvIndLimInf) {
        this.srvIndLimInf = srvIndLimInf;
    }
    public Float getSrvIndLimSup() {
        return this.srvIndLimSup;
    }
    
    public void setSrvIndLimSup(Float srvIndLimSup) {
        this.srvIndLimSup = srvIndLimSup;
    }
    public Integer getSrvIndOrdPre() {
        return this.srvIndOrdPre;
    }
    
    public void setSrvIndOrdPre(Integer srvIndOrdPre) {
        this.srvIndOrdPre = srvIndOrdPre;
    }
    public Float getSrvIndPto() {
        return this.srvIndPto;
    }
    
    public void setSrvIndPto(Float srvIndPto) {
        this.srvIndPto = srvIndPto;
    }
    public Float getSrvIndWoe() {
        return this.srvIndWoe;
    }
    
    public void setSrvIndWoe(Float srvIndWoe) {
        this.srvIndWoe = srvIndWoe;
    }
    public String getSrvIndDesLar() {
        return this.srvIndDesLar;
    }
    
    public void setSrvIndDesLar(String srvIndDesLar) {
        this.srvIndDesLar = srvIndDesLar;
    }




}


