package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipEmp generated by hbm2java
 */
public class TipEmp  implements java.io.Serializable {


     private int tipEmpId;
     private Integer calId;
     private String tipEmpDes;
     private Float tipEmpLimInf;
     private Float tipEmpLimSup;
     private Integer tipEmpOrdPre;
     private Float tipEmpPto;
     private Float tipEmpWoe;
     private String tipEmpDesLar;
     private Set cliMtas = new HashSet(0);

    public TipEmp() {
    }

	
    public TipEmp(int tipEmpId) {
        this.tipEmpId = tipEmpId;
    }
    public TipEmp(int tipEmpId, Integer calId, String tipEmpDes, Float tipEmpLimInf, Float tipEmpLimSup, Integer tipEmpOrdPre, Float tipEmpPto, Float tipEmpWoe, String tipEmpDesLar, Set cliMtas) {
       this.tipEmpId = tipEmpId;
       this.calId = calId;
       this.tipEmpDes = tipEmpDes;
       this.tipEmpLimInf = tipEmpLimInf;
       this.tipEmpLimSup = tipEmpLimSup;
       this.tipEmpOrdPre = tipEmpOrdPre;
       this.tipEmpPto = tipEmpPto;
       this.tipEmpWoe = tipEmpWoe;
       this.tipEmpDesLar = tipEmpDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getTipEmpId() {
        return this.tipEmpId;
    }
    
    public void setTipEmpId(int tipEmpId) {
        this.tipEmpId = tipEmpId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getTipEmpDes() {
        return this.tipEmpDes;
    }
    
    public void setTipEmpDes(String tipEmpDes) {
        this.tipEmpDes = tipEmpDes;
    }
    public Float getTipEmpLimInf() {
        return this.tipEmpLimInf;
    }
    
    public void setTipEmpLimInf(Float tipEmpLimInf) {
        this.tipEmpLimInf = tipEmpLimInf;
    }
    public Float getTipEmpLimSup() {
        return this.tipEmpLimSup;
    }
    
    public void setTipEmpLimSup(Float tipEmpLimSup) {
        this.tipEmpLimSup = tipEmpLimSup;
    }
    public Integer getTipEmpOrdPre() {
        return this.tipEmpOrdPre;
    }
    
    public void setTipEmpOrdPre(Integer tipEmpOrdPre) {
        this.tipEmpOrdPre = tipEmpOrdPre;
    }
    public Float getTipEmpPto() {
        return this.tipEmpPto;
    }
    
    public void setTipEmpPto(Float tipEmpPto) {
        this.tipEmpPto = tipEmpPto;
    }
    public Float getTipEmpWoe() {
        return this.tipEmpWoe;
    }
    
    public void setTipEmpWoe(Float tipEmpWoe) {
        this.tipEmpWoe = tipEmpWoe;
    }
    public String getTipEmpDesLar() {
        return this.tipEmpDesLar;
    }
    
    public void setTipEmpDesLar(String tipEmpDesLar) {
        this.tipEmpDesLar = tipEmpDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


