package arbitreadores.objetos;
// Generated 13-may-2011 8:17:31 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipRes generated by hbm2java
 */
public class TipRes  implements java.io.Serializable {


     private int tipResId;
     private Integer calId;
     private String tipResDes;
     private Float tipResLimInf;
     private Float tipResLimSup;
     private Integer tipResOrdPre;
     private Float tipResPto;
     private Float tipResWoe;
     private String tipResDesLar;
     private Set cliMtas = new HashSet(0);

    public TipRes() {
    }

	
    public TipRes(int tipResId) {
        this.tipResId = tipResId;
    }
    public TipRes(int tipResId, Integer calId, String tipResDes, Float tipResLimInf, Float tipResLimSup, Integer tipResOrdPre, Float tipResPto, Float tipResWoe, String tipResDesLar, Set cliMtas) {
       this.tipResId = tipResId;
       this.calId = calId;
       this.tipResDes = tipResDes;
       this.tipResLimInf = tipResLimInf;
       this.tipResLimSup = tipResLimSup;
       this.tipResOrdPre = tipResOrdPre;
       this.tipResPto = tipResPto;
       this.tipResWoe = tipResWoe;
       this.tipResDesLar = tipResDesLar;
       this.cliMtas = cliMtas;
    }
   
    public int getTipResId() {
        return this.tipResId;
    }
    
    public void setTipResId(int tipResId) {
        this.tipResId = tipResId;
    }
    public Integer getCalId() {
        return this.calId;
    }
    
    public void setCalId(Integer calId) {
        this.calId = calId;
    }
    public String getTipResDes() {
        return this.tipResDes;
    }
    
    public void setTipResDes(String tipResDes) {
        this.tipResDes = tipResDes;
    }
    public Float getTipResLimInf() {
        return this.tipResLimInf;
    }
    
    public void setTipResLimInf(Float tipResLimInf) {
        this.tipResLimInf = tipResLimInf;
    }
    public Float getTipResLimSup() {
        return this.tipResLimSup;
    }
    
    public void setTipResLimSup(Float tipResLimSup) {
        this.tipResLimSup = tipResLimSup;
    }
    public Integer getTipResOrdPre() {
        return this.tipResOrdPre;
    }
    
    public void setTipResOrdPre(Integer tipResOrdPre) {
        this.tipResOrdPre = tipResOrdPre;
    }
    public Float getTipResPto() {
        return this.tipResPto;
    }
    
    public void setTipResPto(Float tipResPto) {
        this.tipResPto = tipResPto;
    }
    public Float getTipResWoe() {
        return this.tipResWoe;
    }
    
    public void setTipResWoe(Float tipResWoe) {
        this.tipResWoe = tipResWoe;
    }
    public String getTipResDesLar() {
        return this.tipResDesLar;
    }
    
    public void setTipResDesLar(String tipResDesLar) {
        this.tipResDesLar = tipResDesLar;
    }
    public Set getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set cliMtas) {
        this.cliMtas = cliMtas;
    }




}


