package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ActExt generated by hbm2java
 */
public class ActExt  implements java.io.Serializable {


     private BigDecimal actExtId;
     private Cal cal;
     private String actExtDes;
     private Double actExtLimInf;
     private Double actExtLimSup;
     private BigDecimal actExtOrdPre;
     private Double actExtPto;
     private Double actExtWoe;
     private String actExtDesLar;
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);

    public ActExt() {
    }

	
    public ActExt(BigDecimal actExtId) {
        this.actExtId = actExtId;
    }
    public ActExt(BigDecimal actExtId, Cal cal, String actExtDes, Double actExtLimInf, Double actExtLimSup, BigDecimal actExtOrdPre, Double actExtPto, Double actExtWoe, String actExtDesLar, Set<CliMta> cliMtas) {
       this.actExtId = actExtId;
       this.cal = cal;
       this.actExtDes = actExtDes;
       this.actExtLimInf = actExtLimInf;
       this.actExtLimSup = actExtLimSup;
       this.actExtOrdPre = actExtOrdPre;
       this.actExtPto = actExtPto;
       this.actExtWoe = actExtWoe;
       this.actExtDesLar = actExtDesLar;
       this.cliMtas = cliMtas;
    }
   
    public BigDecimal getActExtId() {
        return this.actExtId;
    }
    
    public void setActExtId(BigDecimal actExtId) {
        this.actExtId = actExtId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getActExtDes() {
        return this.actExtDes;
    }
    
    public void setActExtDes(String actExtDes) {
        this.actExtDes = actExtDes;
    }
    public Double getActExtLimInf() {
        return this.actExtLimInf;
    }
    
    public void setActExtLimInf(Double actExtLimInf) {
        this.actExtLimInf = actExtLimInf;
    }
    public Double getActExtLimSup() {
        return this.actExtLimSup;
    }
    
    public void setActExtLimSup(Double actExtLimSup) {
        this.actExtLimSup = actExtLimSup;
    }
    public BigDecimal getActExtOrdPre() {
        return this.actExtOrdPre;
    }
    
    public void setActExtOrdPre(BigDecimal actExtOrdPre) {
        this.actExtOrdPre = actExtOrdPre;
    }
    public Double getActExtPto() {
        return this.actExtPto;
    }
    
    public void setActExtPto(Double actExtPto) {
        this.actExtPto = actExtPto;
    }
    public Double getActExtWoe() {
        return this.actExtWoe;
    }
    
    public void setActExtWoe(Double actExtWoe) {
        this.actExtWoe = actExtWoe;
    }
    public String getActExtDesLar() {
        return this.actExtDesLar;
    }
    
    public void setActExtDesLar(String actExtDesLar) {
        this.actExtDesLar = actExtDesLar;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }




}


