package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ActUlt generated by hbm2java
 */
public class ActUlt  implements java.io.Serializable {


     private BigDecimal actUltId;
     private Cal cal;
     private String actUltDes;
     private Double actUltLimInf;
     private Double actUltLimSup;
     private BigDecimal actUltOrdPre;
     private Double actUltPto;
     private Double actUltWoe;
     private String actUltDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public ActUlt() {
    }

	
    public ActUlt(BigDecimal actUltId) {
        this.actUltId = actUltId;
    }
    public ActUlt(BigDecimal actUltId, Cal cal, String actUltDes, Double actUltLimInf, Double actUltLimSup, BigDecimal actUltOrdPre, Double actUltPto, Double actUltWoe, String actUltDesLar, Set<CliGol> cliGols) {
       this.actUltId = actUltId;
       this.cal = cal;
       this.actUltDes = actUltDes;
       this.actUltLimInf = actUltLimInf;
       this.actUltLimSup = actUltLimSup;
       this.actUltOrdPre = actUltOrdPre;
       this.actUltPto = actUltPto;
       this.actUltWoe = actUltWoe;
       this.actUltDesLar = actUltDesLar;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getActUltId() {
        return this.actUltId;
    }
    
    public void setActUltId(BigDecimal actUltId) {
        this.actUltId = actUltId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getActUltDes() {
        return this.actUltDes;
    }
    
    public void setActUltDes(String actUltDes) {
        this.actUltDes = actUltDes;
    }
    public Double getActUltLimInf() {
        return this.actUltLimInf;
    }
    
    public void setActUltLimInf(Double actUltLimInf) {
        this.actUltLimInf = actUltLimInf;
    }
    public Double getActUltLimSup() {
        return this.actUltLimSup;
    }
    
    public void setActUltLimSup(Double actUltLimSup) {
        this.actUltLimSup = actUltLimSup;
    }
    public BigDecimal getActUltOrdPre() {
        return this.actUltOrdPre;
    }
    
    public void setActUltOrdPre(BigDecimal actUltOrdPre) {
        this.actUltOrdPre = actUltOrdPre;
    }
    public Double getActUltPto() {
        return this.actUltPto;
    }
    
    public void setActUltPto(Double actUltPto) {
        this.actUltPto = actUltPto;
    }
    public Double getActUltWoe() {
        return this.actUltWoe;
    }
    
    public void setActUltWoe(Double actUltWoe) {
        this.actUltWoe = actUltWoe;
    }
    public String getActUltDesLar() {
        return this.actUltDesLar;
    }
    
    public void setActUltDesLar(String actUltDesLar) {
        this.actUltDesLar = actUltDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


