package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * BanCmp generated by hbm2java
 */
public class BanCmp  implements java.io.Serializable {


     private BigDecimal banCmpId;
     private Cal cal;
     private String banCmpDes;
     private Double banCmpLimInf;
     private Double banCmpLimSup;
     private BigDecimal banCmpOrdPre;
     private Double banCmpPto;
     private Double banCmpWoe;
     private String banCmpDesLar;

    public BanCmp() {
    }

	
    public BanCmp(BigDecimal banCmpId) {
        this.banCmpId = banCmpId;
    }
    public BanCmp(BigDecimal banCmpId, Cal cal, String banCmpDes, Double banCmpLimInf, Double banCmpLimSup, BigDecimal banCmpOrdPre, Double banCmpPto, Double banCmpWoe, String banCmpDesLar) {
       this.banCmpId = banCmpId;
       this.cal = cal;
       this.banCmpDes = banCmpDes;
       this.banCmpLimInf = banCmpLimInf;
       this.banCmpLimSup = banCmpLimSup;
       this.banCmpOrdPre = banCmpOrdPre;
       this.banCmpPto = banCmpPto;
       this.banCmpWoe = banCmpWoe;
       this.banCmpDesLar = banCmpDesLar;
    }
   
    public BigDecimal getBanCmpId() {
        return this.banCmpId;
    }
    
    public void setBanCmpId(BigDecimal banCmpId) {
        this.banCmpId = banCmpId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getBanCmpDes() {
        return this.banCmpDes;
    }
    
    public void setBanCmpDes(String banCmpDes) {
        this.banCmpDes = banCmpDes;
    }
    public Double getBanCmpLimInf() {
        return this.banCmpLimInf;
    }
    
    public void setBanCmpLimInf(Double banCmpLimInf) {
        this.banCmpLimInf = banCmpLimInf;
    }
    public Double getBanCmpLimSup() {
        return this.banCmpLimSup;
    }
    
    public void setBanCmpLimSup(Double banCmpLimSup) {
        this.banCmpLimSup = banCmpLimSup;
    }
    public BigDecimal getBanCmpOrdPre() {
        return this.banCmpOrdPre;
    }
    
    public void setBanCmpOrdPre(BigDecimal banCmpOrdPre) {
        this.banCmpOrdPre = banCmpOrdPre;
    }
    public Double getBanCmpPto() {
        return this.banCmpPto;
    }
    
    public void setBanCmpPto(Double banCmpPto) {
        this.banCmpPto = banCmpPto;
    }
    public Double getBanCmpWoe() {
        return this.banCmpWoe;
    }
    
    public void setBanCmpWoe(Double banCmpWoe) {
        this.banCmpWoe = banCmpWoe;
    }
    public String getBanCmpDesLar() {
        return this.banCmpDesLar;
    }
    
    public void setBanCmpDesLar(String banCmpDesLar) {
        this.banCmpDesLar = banCmpDesLar;
    }




}


