package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * BhrPagPtlCnt generated by hbm2java
 */
public class BhrPagPtlCnt  implements java.io.Serializable {


     private BigDecimal bhrPagPtlCntId;
     private BigDecimal calId;
     private String bhrPagPtlCntDes;
     private Double bhrPagPtlCntLimInf;
     private Double bhrPagPtlCntLimSup;
     private BigDecimal bhrPagPtlCntOrdPre;
     private Double bhrPagPtlCntPto;
     private Double bhrPagPtlCntWoe;
     private String bhrPagPtlCntDesLar;
     private Set<CliBhr> cliBhrs = new HashSet<CliBhr>(0);

    public BhrPagPtlCnt() {
    }

	
    public BhrPagPtlCnt(BigDecimal bhrPagPtlCntId) {
        this.bhrPagPtlCntId = bhrPagPtlCntId;
    }
    public BhrPagPtlCnt(BigDecimal bhrPagPtlCntId, BigDecimal calId, String bhrPagPtlCntDes, Double bhrPagPtlCntLimInf, Double bhrPagPtlCntLimSup, BigDecimal bhrPagPtlCntOrdPre, Double bhrPagPtlCntPto, Double bhrPagPtlCntWoe, String bhrPagPtlCntDesLar, Set<CliBhr> cliBhrs) {
       this.bhrPagPtlCntId = bhrPagPtlCntId;
       this.calId = calId;
       this.bhrPagPtlCntDes = bhrPagPtlCntDes;
       this.bhrPagPtlCntLimInf = bhrPagPtlCntLimInf;
       this.bhrPagPtlCntLimSup = bhrPagPtlCntLimSup;
       this.bhrPagPtlCntOrdPre = bhrPagPtlCntOrdPre;
       this.bhrPagPtlCntPto = bhrPagPtlCntPto;
       this.bhrPagPtlCntWoe = bhrPagPtlCntWoe;
       this.bhrPagPtlCntDesLar = bhrPagPtlCntDesLar;
       this.cliBhrs = cliBhrs;
    }
   
    public BigDecimal getBhrPagPtlCntId() {
        return this.bhrPagPtlCntId;
    }
    
    public void setBhrPagPtlCntId(BigDecimal bhrPagPtlCntId) {
        this.bhrPagPtlCntId = bhrPagPtlCntId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getBhrPagPtlCntDes() {
        return this.bhrPagPtlCntDes;
    }
    
    public void setBhrPagPtlCntDes(String bhrPagPtlCntDes) {
        this.bhrPagPtlCntDes = bhrPagPtlCntDes;
    }
    public Double getBhrPagPtlCntLimInf() {
        return this.bhrPagPtlCntLimInf;
    }
    
    public void setBhrPagPtlCntLimInf(Double bhrPagPtlCntLimInf) {
        this.bhrPagPtlCntLimInf = bhrPagPtlCntLimInf;
    }
    public Double getBhrPagPtlCntLimSup() {
        return this.bhrPagPtlCntLimSup;
    }
    
    public void setBhrPagPtlCntLimSup(Double bhrPagPtlCntLimSup) {
        this.bhrPagPtlCntLimSup = bhrPagPtlCntLimSup;
    }
    public BigDecimal getBhrPagPtlCntOrdPre() {
        return this.bhrPagPtlCntOrdPre;
    }
    
    public void setBhrPagPtlCntOrdPre(BigDecimal bhrPagPtlCntOrdPre) {
        this.bhrPagPtlCntOrdPre = bhrPagPtlCntOrdPre;
    }
    public Double getBhrPagPtlCntPto() {
        return this.bhrPagPtlCntPto;
    }
    
    public void setBhrPagPtlCntPto(Double bhrPagPtlCntPto) {
        this.bhrPagPtlCntPto = bhrPagPtlCntPto;
    }
    public Double getBhrPagPtlCntWoe() {
        return this.bhrPagPtlCntWoe;
    }
    
    public void setBhrPagPtlCntWoe(Double bhrPagPtlCntWoe) {
        this.bhrPagPtlCntWoe = bhrPagPtlCntWoe;
    }
    public String getBhrPagPtlCntDesLar() {
        return this.bhrPagPtlCntDesLar;
    }
    
    public void setBhrPagPtlCntDesLar(String bhrPagPtlCntDesLar) {
        this.bhrPagPtlCntDesLar = bhrPagPtlCntDesLar;
    }
    public Set<CliBhr> getCliBhrs() {
        return this.cliBhrs;
    }
    
    public void setCliBhrs(Set<CliBhr> cliBhrs) {
        this.cliBhrs = cliBhrs;
    }




}


