package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * BurAnt generated by hbm2java
 */
public class BurAnt  implements java.io.Serializable {


     private BigDecimal burAntId;
     private Cal cal;
     private String burAntDes;
     private Double burAntLimInf;
     private Double burAntLimSup;
     private BigDecimal burAntOrdPre;
     private Double burAntPto;
     private Double burAntWoe;
     private String burAntDesLar;
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);

    public BurAnt() {
    }

	
    public BurAnt(BigDecimal burAntId) {
        this.burAntId = burAntId;
    }
    public BurAnt(BigDecimal burAntId, Cal cal, String burAntDes, Double burAntLimInf, Double burAntLimSup, BigDecimal burAntOrdPre, Double burAntPto, Double burAntWoe, String burAntDesLar, Set<CliMta> cliMtas) {
       this.burAntId = burAntId;
       this.cal = cal;
       this.burAntDes = burAntDes;
       this.burAntLimInf = burAntLimInf;
       this.burAntLimSup = burAntLimSup;
       this.burAntOrdPre = burAntOrdPre;
       this.burAntPto = burAntPto;
       this.burAntWoe = burAntWoe;
       this.burAntDesLar = burAntDesLar;
       this.cliMtas = cliMtas;
    }
   
    public BigDecimal getBurAntId() {
        return this.burAntId;
    }
    
    public void setBurAntId(BigDecimal burAntId) {
        this.burAntId = burAntId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getBurAntDes() {
        return this.burAntDes;
    }
    
    public void setBurAntDes(String burAntDes) {
        this.burAntDes = burAntDes;
    }
    public Double getBurAntLimInf() {
        return this.burAntLimInf;
    }
    
    public void setBurAntLimInf(Double burAntLimInf) {
        this.burAntLimInf = burAntLimInf;
    }
    public Double getBurAntLimSup() {
        return this.burAntLimSup;
    }
    
    public void setBurAntLimSup(Double burAntLimSup) {
        this.burAntLimSup = burAntLimSup;
    }
    public BigDecimal getBurAntOrdPre() {
        return this.burAntOrdPre;
    }
    
    public void setBurAntOrdPre(BigDecimal burAntOrdPre) {
        this.burAntOrdPre = burAntOrdPre;
    }
    public Double getBurAntPto() {
        return this.burAntPto;
    }
    
    public void setBurAntPto(Double burAntPto) {
        this.burAntPto = burAntPto;
    }
    public Double getBurAntWoe() {
        return this.burAntWoe;
    }
    
    public void setBurAntWoe(Double burAntWoe) {
        this.burAntWoe = burAntWoe;
    }
    public String getBurAntDesLar() {
        return this.burAntDesLar;
    }
    
    public void setBurAntDesLar(String burAntDesLar) {
        this.burAntDesLar = burAntDesLar;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }




}


