package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * BurPag generated by hbm2java
 */
public class BurPag  implements java.io.Serializable {


     private BigDecimal burPagId;
     private Cal cal;
     private String burPagDes;
     private Double burPagLimInf;
     private Double burPagLimSup;
     private BigDecimal burPagOrdPre;
     private Double burPagPto;
     private Double burPagWoe;
     private String burPagDesLar;
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);
     private Set<CliBur> cliBurs = new HashSet<CliBur>(0);

    public BurPag() {
    }

	
    public BurPag(BigDecimal burPagId) {
        this.burPagId = burPagId;
    }
    public BurPag(BigDecimal burPagId, Cal cal, String burPagDes, Double burPagLimInf, Double burPagLimSup, BigDecimal burPagOrdPre, Double burPagPto, Double burPagWoe, String burPagDesLar, Set<CliMta> cliMtas, Set<CliBur> cliBurs) {
       this.burPagId = burPagId;
       this.cal = cal;
       this.burPagDes = burPagDes;
       this.burPagLimInf = burPagLimInf;
       this.burPagLimSup = burPagLimSup;
       this.burPagOrdPre = burPagOrdPre;
       this.burPagPto = burPagPto;
       this.burPagWoe = burPagWoe;
       this.burPagDesLar = burPagDesLar;
       this.cliMtas = cliMtas;
       this.cliBurs = cliBurs;
    }
   
    public BigDecimal getBurPagId() {
        return this.burPagId;
    }
    
    public void setBurPagId(BigDecimal burPagId) {
        this.burPagId = burPagId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getBurPagDes() {
        return this.burPagDes;
    }
    
    public void setBurPagDes(String burPagDes) {
        this.burPagDes = burPagDes;
    }
    public Double getBurPagLimInf() {
        return this.burPagLimInf;
    }
    
    public void setBurPagLimInf(Double burPagLimInf) {
        this.burPagLimInf = burPagLimInf;
    }
    public Double getBurPagLimSup() {
        return this.burPagLimSup;
    }
    
    public void setBurPagLimSup(Double burPagLimSup) {
        this.burPagLimSup = burPagLimSup;
    }
    public BigDecimal getBurPagOrdPre() {
        return this.burPagOrdPre;
    }
    
    public void setBurPagOrdPre(BigDecimal burPagOrdPre) {
        this.burPagOrdPre = burPagOrdPre;
    }
    public Double getBurPagPto() {
        return this.burPagPto;
    }
    
    public void setBurPagPto(Double burPagPto) {
        this.burPagPto = burPagPto;
    }
    public Double getBurPagWoe() {
        return this.burPagWoe;
    }
    
    public void setBurPagWoe(Double burPagWoe) {
        this.burPagWoe = burPagWoe;
    }
    public String getBurPagDesLar() {
        return this.burPagDesLar;
    }
    
    public void setBurPagDesLar(String burPagDesLar) {
        this.burPagDesLar = burPagDesLar;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }
    public Set<CliBur> getCliBurs() {
        return this.cliBurs;
    }
    
    public void setCliBurs(Set<CliBur> cliBurs) {
        this.cliBurs = cliBurs;
    }




}


