package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cal generated by hbm2java
 */
public class Cal  implements java.io.Serializable {


     private int calId;
     private String calDes;
     private Set<CatPsi> catPsis = new HashSet<CatPsi>(0);
     private Set<ApoOtr> apoOtrs = new HashSet<ApoOtr>(0);
     private Set<GtoSld> gtoSlds = new HashSet<GtoSld>(0);
     private Set<DinExt> dinExts = new HashSet<DinExt>(0);
     private Set<GtoRen> gtoRens = new HashSet<GtoRen>(0);
     private Set<GtoVes> gtoVeses = new HashSet<GtoVes>(0);
     private Set<ApyEco> apyEcos = new HashSet<ApyEco>(0);
     private Set<OpnBar> opnBars = new HashSet<OpnBar>(0);
     private Set<ConFpf> conFpfs = new HashSet<ConFpf>(0);
     private Set<BurAbt> burAbts = new HashSet<BurAbt>(0);
     private Set<ConAbf> conAbfs = new HashSet<ConAbf>(0);
     private Set<GtoImp> gtoImps = new HashSet<GtoImp>(0);
     private Set<GtoLim> gtoLims = new HashSet<GtoLim>(0);
     private Set<OpnBzn> opnBzns = new HashSet<OpnBzn>(0);
     private Set<BurAct> burActs = new HashSet<BurAct>(0);
     private Set<OpnFpFv> opnFpFvs = new HashSet<OpnFpFv>(0);
     private Set<CreOtr> creOtrs = new HashSet<CreOtr>(0);
     private Set<ConRed> conReds = new HashSet<ConRed>(0);
     private Set<Mig> migs = new HashSet<Mig>(0);
     private Set<ConUce> conUces = new HashSet<ConUce>(0);
     private Set<IntPi> intPis = new HashSet<IntPi>(0);
     private Set<Ing> ings = new HashSet<Ing>(0);
     private Set<BanPorPag> banPorPags = new HashSet<BanPorPag>(0);
     private Set<DepEco> depEcos = new HashSet<DepEco>(0);
     private Set<GtoEdu> gtoEdus = new HashSet<GtoEdu>(0);
     private Set<Edo> edos = new HashSet<Edo>(0);
     private Set<EdoCvl> edoCvls = new HashSet<EdoCvl>(0);
     private Set<ConAma> conAmas = new HashSet<ConAma>(0);
     private Set<CueAbr> cueAbrs = new HashSet<CueAbr>(0);
     private Set<GtoDeu> gtoDeus = new HashSet<GtoDeu>(0);
     private Set<NivEst> nivEsts = new HashSet<NivEst>(0);
     private Set<ApoHij> apoHijs = new HashSet<ApoHij>(0);
     private Set<GtoSab> gtoSabs = new HashSet<GtoSab>(0);
     private Set<IRnt> IRnts = new HashSet<IRnt>(0);
     private Set<GtoSerViv> gtoSerVivs = new HashSet<GtoSerViv>(0);
     private Set<NivEstPap> nivEstPaps = new HashSet<NivEstPap>(0);
     private Set<Mov> movs = new HashSet<Mov>(0);
     private Set<BurAnt> burAnts = new HashSet<BurAnt>(0);
     private Set<ConBar> conBars = new HashSet<ConBar>(0);
     private Set<GtoCre> gtoCres = new HashSet<GtoCre>(0);
     private Set<OpnPrt> opnPrts = new HashSet<OpnPrt>(0);
     private Set<NivEstMam> nivEstMams = new HashSet<NivEstMam>(0);
     private Set<FreRel> freRels = new HashSet<FreRel>(0);
     private Set<BanPorUso> banPorUsos = new HashSet<BanPorUso>(0);
     private Set<BurUso> burUsos = new HashSet<BurUso>(0);
     private Set<Ocp> ocps = new HashSet<Ocp>(0);
     private Set<BanCmp> banCmps = new HashSet<BanCmp>(0);
     private Set<Des> deses = new HashSet<Des>(0);
     private Set<BurPag> burPags = new HashSet<BurPag>(0);
     private Set<Est> ests = new HashSet<Est>(0);
     private Set<GtoTrn> gtoTrns = new HashSet<GtoTrn>(0);
     private Set<ActExt> actExts = new HashSet<ActExt>(0);
     private Set<AsoPar> asoPars = new HashSet<AsoPar>(0);
     private Set<Eda> edas = new HashSet<Eda>(0);
     private Set<CreHip> creHips = new HashSet<CreHip>(0);
     private Set<GtoAlm> gtoAlms = new HashSet<GtoAlm>(0);
     private Set<Cli> clis = new HashSet<Cli>(0);
     private Set<GtoDiv> gtoDivs = new HashSet<GtoDiv>(0);
     private Set<OpnAbf> opnAbfs = new HashSet<OpnAbf>(0);
     private Set<MejPar> mejPars = new HashSet<MejPar>(0);
     private Set<GtoSot> gtoSots = new HashSet<GtoSot>(0);
     private Set<IPsi> IPsis = new HashSet<IPsi>(0);
     private Set<ActUlt> actUlts = new HashSet<ActUlt>(0);
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);
     private Set<NumCre> numCres = new HashSet<NumCre>(0);
     private Set<GtoPer> gtoPers = new HashSet<GtoPer>(0);
     private Set<FreDin> freDins = new HashSet<FreDin>(0);
     private Set<GtoOtr> gtoOtrs = new HashSet<GtoOtr>(0);
     private Set<ApoCon> apoCons = new HashSet<ApoCon>(0);
     private Set<ApoPad> apoPads = new HashSet<ApoPad>(0);
     private Set<BurHis> burHises = new HashSet<BurHis>(0);
     private Set<OpnMap> opnMaps = new HashSet<OpnMap>(0);

    public Cal() {
    }

	
    public Cal(int calId) {
        this.calId = calId;
    }
    public Cal(int calId, String calDes, Set<CatPsi> catPsis, Set<ApoOtr> apoOtrs, Set<GtoSld> gtoSlds, Set<DinExt> dinExts, Set<GtoRen> gtoRens, Set<GtoVes> gtoVeses, Set<ApyEco> apyEcos, Set<OpnBar> opnBars, Set<ConFpf> conFpfs, Set<BurAbt> burAbts, Set<ConAbf> conAbfs, Set<GtoImp> gtoImps, Set<GtoLim> gtoLims, Set<OpnBzn> opnBzns, Set<BurAct> burActs, Set<OpnFpFv> opnFpFvs, Set<CreOtr> creOtrs, Set<ConRed> conReds, Set<Mig> migs, Set<ConUce> conUces, Set<IntPi> intPis, Set<Ing> ings, Set<BanPorPag> banPorPags, Set<DepEco> depEcos, Set<GtoEdu> gtoEdus, Set<Edo> edos, Set<EdoCvl> edoCvls, Set<ConAma> conAmas, Set<CueAbr> cueAbrs, Set<GtoDeu> gtoDeus, Set<NivEst> nivEsts, Set<ApoHij> apoHijs, Set<GtoSab> gtoSabs, Set<IRnt> IRnts, Set<GtoSerViv> gtoSerVivs, Set<NivEstPap> nivEstPaps, Set<Mov> movs, Set<BurAnt> burAnts, Set<ConBar> conBars, Set<GtoCre> gtoCres, Set<OpnPrt> opnPrts, Set<NivEstMam> nivEstMams, Set<FreRel> freRels, Set<BanPorUso> banPorUsos, Set<BurUso> burUsos, Set<Ocp> ocps, Set<BanCmp> banCmps, Set<Des> deses, Set<BurPag> burPags, Set<Est> ests, Set<GtoTrn> gtoTrns, Set<ActExt> actExts, Set<AsoPar> asoPars, Set<Eda> edas, Set<CreHip> creHips, Set<GtoAlm> gtoAlms, Set<Cli> clis, Set<GtoDiv> gtoDivs, Set<OpnAbf> opnAbfs, Set<MejPar> mejPars, Set<GtoSot> gtoSots, Set<IPsi> IPsis, Set<ActUlt> actUlts, Set<CliMta> cliMtas, Set<NumCre> numCres, Set<GtoPer> gtoPers, Set<FreDin> freDins, Set<GtoOtr> gtoOtrs, Set<ApoCon> apoCons, Set<ApoPad> apoPads, Set<BurHis> burHises, Set<OpnMap> opnMaps) {
       this.calId = calId;
       this.calDes = calDes;
       this.catPsis = catPsis;
       this.apoOtrs = apoOtrs;
       this.gtoSlds = gtoSlds;
       this.dinExts = dinExts;
       this.gtoRens = gtoRens;
       this.gtoVeses = gtoVeses;
       this.apyEcos = apyEcos;
       this.opnBars = opnBars;
       this.conFpfs = conFpfs;
       this.burAbts = burAbts;
       this.conAbfs = conAbfs;
       this.gtoImps = gtoImps;
       this.gtoLims = gtoLims;
       this.opnBzns = opnBzns;
       this.burActs = burActs;
       this.opnFpFvs = opnFpFvs;
       this.creOtrs = creOtrs;
       this.conReds = conReds;
       this.migs = migs;
       this.conUces = conUces;
       this.intPis = intPis;
       this.ings = ings;
       this.banPorPags = banPorPags;
       this.depEcos = depEcos;
       this.gtoEdus = gtoEdus;
       this.edos = edos;
       this.edoCvls = edoCvls;
       this.conAmas = conAmas;
       this.cueAbrs = cueAbrs;
       this.gtoDeus = gtoDeus;
       this.nivEsts = nivEsts;
       this.apoHijs = apoHijs;
       this.gtoSabs = gtoSabs;
       this.IRnts = IRnts;
       this.gtoSerVivs = gtoSerVivs;
       this.nivEstPaps = nivEstPaps;
       this.movs = movs;
       this.burAnts = burAnts;
       this.conBars = conBars;
       this.gtoCres = gtoCres;
       this.opnPrts = opnPrts;
       this.nivEstMams = nivEstMams;
       this.freRels = freRels;
       this.banPorUsos = banPorUsos;
       this.burUsos = burUsos;
       this.ocps = ocps;
       this.banCmps = banCmps;
       this.deses = deses;
       this.burPags = burPags;
       this.ests = ests;
       this.gtoTrns = gtoTrns;
       this.actExts = actExts;
       this.asoPars = asoPars;
       this.edas = edas;
       this.creHips = creHips;
       this.gtoAlms = gtoAlms;
       this.clis = clis;
       this.gtoDivs = gtoDivs;
       this.opnAbfs = opnAbfs;
       this.mejPars = mejPars;
       this.gtoSots = gtoSots;
       this.IPsis = IPsis;
       this.actUlts = actUlts;
       this.cliMtas = cliMtas;
       this.numCres = numCres;
       this.gtoPers = gtoPers;
       this.freDins = freDins;
       this.gtoOtrs = gtoOtrs;
       this.apoCons = apoCons;
       this.apoPads = apoPads;
       this.burHises = burHises;
       this.opnMaps = opnMaps;
    }
   
    public int getCalId() {
        return this.calId;
    }
    
    public void setCalId(int calId) {
        this.calId = calId;
    }
    public String getCalDes() {
        return this.calDes;
    }
    
    public void setCalDes(String calDes) {
        this.calDes = calDes;
    }
    public Set<CatPsi> getCatPsis() {
        return this.catPsis;
    }
    
    public void setCatPsis(Set<CatPsi> catPsis) {
        this.catPsis = catPsis;
    }
    public Set<ApoOtr> getApoOtrs() {
        return this.apoOtrs;
    }
    
    public void setApoOtrs(Set<ApoOtr> apoOtrs) {
        this.apoOtrs = apoOtrs;
    }
    public Set<GtoSld> getGtoSlds() {
        return this.gtoSlds;
    }
    
    public void setGtoSlds(Set<GtoSld> gtoSlds) {
        this.gtoSlds = gtoSlds;
    }
    public Set<DinExt> getDinExts() {
        return this.dinExts;
    }
    
    public void setDinExts(Set<DinExt> dinExts) {
        this.dinExts = dinExts;
    }
    public Set<GtoRen> getGtoRens() {
        return this.gtoRens;
    }
    
    public void setGtoRens(Set<GtoRen> gtoRens) {
        this.gtoRens = gtoRens;
    }
    public Set<GtoVes> getGtoVeses() {
        return this.gtoVeses;
    }
    
    public void setGtoVeses(Set<GtoVes> gtoVeses) {
        this.gtoVeses = gtoVeses;
    }
    public Set<ApyEco> getApyEcos() {
        return this.apyEcos;
    }
    
    public void setApyEcos(Set<ApyEco> apyEcos) {
        this.apyEcos = apyEcos;
    }
    public Set<OpnBar> getOpnBars() {
        return this.opnBars;
    }
    
    public void setOpnBars(Set<OpnBar> opnBars) {
        this.opnBars = opnBars;
    }
    public Set<ConFpf> getConFpfs() {
        return this.conFpfs;
    }
    
    public void setConFpfs(Set<ConFpf> conFpfs) {
        this.conFpfs = conFpfs;
    }
    public Set<BurAbt> getBurAbts() {
        return this.burAbts;
    }
    
    public void setBurAbts(Set<BurAbt> burAbts) {
        this.burAbts = burAbts;
    }
    public Set<ConAbf> getConAbfs() {
        return this.conAbfs;
    }
    
    public void setConAbfs(Set<ConAbf> conAbfs) {
        this.conAbfs = conAbfs;
    }
    public Set<GtoImp> getGtoImps() {
        return this.gtoImps;
    }
    
    public void setGtoImps(Set<GtoImp> gtoImps) {
        this.gtoImps = gtoImps;
    }
    public Set<GtoLim> getGtoLims() {
        return this.gtoLims;
    }
    
    public void setGtoLims(Set<GtoLim> gtoLims) {
        this.gtoLims = gtoLims;
    }
    public Set<OpnBzn> getOpnBzns() {
        return this.opnBzns;
    }
    
    public void setOpnBzns(Set<OpnBzn> opnBzns) {
        this.opnBzns = opnBzns;
    }
    public Set<BurAct> getBurActs() {
        return this.burActs;
    }
    
    public void setBurActs(Set<BurAct> burActs) {
        this.burActs = burActs;
    }
    public Set<OpnFpFv> getOpnFpFvs() {
        return this.opnFpFvs;
    }
    
    public void setOpnFpFvs(Set<OpnFpFv> opnFpFvs) {
        this.opnFpFvs = opnFpFvs;
    }
    public Set<CreOtr> getCreOtrs() {
        return this.creOtrs;
    }
    
    public void setCreOtrs(Set<CreOtr> creOtrs) {
        this.creOtrs = creOtrs;
    }
    public Set<ConRed> getConReds() {
        return this.conReds;
    }
    
    public void setConReds(Set<ConRed> conReds) {
        this.conReds = conReds;
    }
    public Set<Mig> getMigs() {
        return this.migs;
    }
    
    public void setMigs(Set<Mig> migs) {
        this.migs = migs;
    }
    public Set<ConUce> getConUces() {
        return this.conUces;
    }
    
    public void setConUces(Set<ConUce> conUces) {
        this.conUces = conUces;
    }
    public Set<IntPi> getIntPis() {
        return this.intPis;
    }
    
    public void setIntPis(Set<IntPi> intPis) {
        this.intPis = intPis;
    }
    public Set<Ing> getIngs() {
        return this.ings;
    }
    
    public void setIngs(Set<Ing> ings) {
        this.ings = ings;
    }
    public Set<BanPorPag> getBanPorPags() {
        return this.banPorPags;
    }
    
    public void setBanPorPags(Set<BanPorPag> banPorPags) {
        this.banPorPags = banPorPags;
    }
    public Set<DepEco> getDepEcos() {
        return this.depEcos;
    }
    
    public void setDepEcos(Set<DepEco> depEcos) {
        this.depEcos = depEcos;
    }
    public Set<GtoEdu> getGtoEdus() {
        return this.gtoEdus;
    }
    
    public void setGtoEdus(Set<GtoEdu> gtoEdus) {
        this.gtoEdus = gtoEdus;
    }
    public Set<Edo> getEdos() {
        return this.edos;
    }
    
    public void setEdos(Set<Edo> edos) {
        this.edos = edos;
    }
    public Set<EdoCvl> getEdoCvls() {
        return this.edoCvls;
    }
    
    public void setEdoCvls(Set<EdoCvl> edoCvls) {
        this.edoCvls = edoCvls;
    }
    public Set<ConAma> getConAmas() {
        return this.conAmas;
    }
    
    public void setConAmas(Set<ConAma> conAmas) {
        this.conAmas = conAmas;
    }
    public Set<CueAbr> getCueAbrs() {
        return this.cueAbrs;
    }
    
    public void setCueAbrs(Set<CueAbr> cueAbrs) {
        this.cueAbrs = cueAbrs;
    }
    public Set<GtoDeu> getGtoDeus() {
        return this.gtoDeus;
    }
    
    public void setGtoDeus(Set<GtoDeu> gtoDeus) {
        this.gtoDeus = gtoDeus;
    }
    public Set<NivEst> getNivEsts() {
        return this.nivEsts;
    }
    
    public void setNivEsts(Set<NivEst> nivEsts) {
        this.nivEsts = nivEsts;
    }
    public Set<ApoHij> getApoHijs() {
        return this.apoHijs;
    }
    
    public void setApoHijs(Set<ApoHij> apoHijs) {
        this.apoHijs = apoHijs;
    }
    public Set<GtoSab> getGtoSabs() {
        return this.gtoSabs;
    }
    
    public void setGtoSabs(Set<GtoSab> gtoSabs) {
        this.gtoSabs = gtoSabs;
    }
    public Set<IRnt> getIRnts() {
        return this.IRnts;
    }
    
    public void setIRnts(Set<IRnt> IRnts) {
        this.IRnts = IRnts;
    }
    public Set<GtoSerViv> getGtoSerVivs() {
        return this.gtoSerVivs;
    }
    
    public void setGtoSerVivs(Set<GtoSerViv> gtoSerVivs) {
        this.gtoSerVivs = gtoSerVivs;
    }
    public Set<NivEstPap> getNivEstPaps() {
        return this.nivEstPaps;
    }
    
    public void setNivEstPaps(Set<NivEstPap> nivEstPaps) {
        this.nivEstPaps = nivEstPaps;
    }
    public Set<Mov> getMovs() {
        return this.movs;
    }
    
    public void setMovs(Set<Mov> movs) {
        this.movs = movs;
    }
    public Set<BurAnt> getBurAnts() {
        return this.burAnts;
    }
    
    public void setBurAnts(Set<BurAnt> burAnts) {
        this.burAnts = burAnts;
    }
    public Set<ConBar> getConBars() {
        return this.conBars;
    }
    
    public void setConBars(Set<ConBar> conBars) {
        this.conBars = conBars;
    }
    public Set<GtoCre> getGtoCres() {
        return this.gtoCres;
    }
    
    public void setGtoCres(Set<GtoCre> gtoCres) {
        this.gtoCres = gtoCres;
    }
    public Set<OpnPrt> getOpnPrts() {
        return this.opnPrts;
    }
    
    public void setOpnPrts(Set<OpnPrt> opnPrts) {
        this.opnPrts = opnPrts;
    }
    public Set<NivEstMam> getNivEstMams() {
        return this.nivEstMams;
    }
    
    public void setNivEstMams(Set<NivEstMam> nivEstMams) {
        this.nivEstMams = nivEstMams;
    }
    public Set<FreRel> getFreRels() {
        return this.freRels;
    }
    
    public void setFreRels(Set<FreRel> freRels) {
        this.freRels = freRels;
    }
    public Set<BanPorUso> getBanPorUsos() {
        return this.banPorUsos;
    }
    
    public void setBanPorUsos(Set<BanPorUso> banPorUsos) {
        this.banPorUsos = banPorUsos;
    }
    public Set<BurUso> getBurUsos() {
        return this.burUsos;
    }
    
    public void setBurUsos(Set<BurUso> burUsos) {
        this.burUsos = burUsos;
    }
    public Set<Ocp> getOcps() {
        return this.ocps;
    }
    
    public void setOcps(Set<Ocp> ocps) {
        this.ocps = ocps;
    }
    public Set<BanCmp> getBanCmps() {
        return this.banCmps;
    }
    
    public void setBanCmps(Set<BanCmp> banCmps) {
        this.banCmps = banCmps;
    }
    public Set<Des> getDeses() {
        return this.deses;
    }
    
    public void setDeses(Set<Des> deses) {
        this.deses = deses;
    }
    public Set<BurPag> getBurPags() {
        return this.burPags;
    }
    
    public void setBurPags(Set<BurPag> burPags) {
        this.burPags = burPags;
    }
    public Set<Est> getEsts() {
        return this.ests;
    }
    
    public void setEsts(Set<Est> ests) {
        this.ests = ests;
    }
    public Set<GtoTrn> getGtoTrns() {
        return this.gtoTrns;
    }
    
    public void setGtoTrns(Set<GtoTrn> gtoTrns) {
        this.gtoTrns = gtoTrns;
    }
    public Set<ActExt> getActExts() {
        return this.actExts;
    }
    
    public void setActExts(Set<ActExt> actExts) {
        this.actExts = actExts;
    }
    public Set<AsoPar> getAsoPars() {
        return this.asoPars;
    }
    
    public void setAsoPars(Set<AsoPar> asoPars) {
        this.asoPars = asoPars;
    }
    public Set<Eda> getEdas() {
        return this.edas;
    }
    
    public void setEdas(Set<Eda> edas) {
        this.edas = edas;
    }
    public Set<CreHip> getCreHips() {
        return this.creHips;
    }
    
    public void setCreHips(Set<CreHip> creHips) {
        this.creHips = creHips;
    }
    public Set<GtoAlm> getGtoAlms() {
        return this.gtoAlms;
    }
    
    public void setGtoAlms(Set<GtoAlm> gtoAlms) {
        this.gtoAlms = gtoAlms;
    }
    public Set<Cli> getClis() {
        return this.clis;
    }
    
    public void setClis(Set<Cli> clis) {
        this.clis = clis;
    }
    public Set<GtoDiv> getGtoDivs() {
        return this.gtoDivs;
    }
    
    public void setGtoDivs(Set<GtoDiv> gtoDivs) {
        this.gtoDivs = gtoDivs;
    }
    public Set<OpnAbf> getOpnAbfs() {
        return this.opnAbfs;
    }
    
    public void setOpnAbfs(Set<OpnAbf> opnAbfs) {
        this.opnAbfs = opnAbfs;
    }
    public Set<MejPar> getMejPars() {
        return this.mejPars;
    }
    
    public void setMejPars(Set<MejPar> mejPars) {
        this.mejPars = mejPars;
    }
    public Set<GtoSot> getGtoSots() {
        return this.gtoSots;
    }
    
    public void setGtoSots(Set<GtoSot> gtoSots) {
        this.gtoSots = gtoSots;
    }
    public Set<IPsi> getIPsis() {
        return this.IPsis;
    }
    
    public void setIPsis(Set<IPsi> IPsis) {
        this.IPsis = IPsis;
    }
    public Set<ActUlt> getActUlts() {
        return this.actUlts;
    }
    
    public void setActUlts(Set<ActUlt> actUlts) {
        this.actUlts = actUlts;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }
    public Set<NumCre> getNumCres() {
        return this.numCres;
    }
    
    public void setNumCres(Set<NumCre> numCres) {
        this.numCres = numCres;
    }
    public Set<GtoPer> getGtoPers() {
        return this.gtoPers;
    }
    
    public void setGtoPers(Set<GtoPer> gtoPers) {
        this.gtoPers = gtoPers;
    }
    public Set<FreDin> getFreDins() {
        return this.freDins;
    }
    
    public void setFreDins(Set<FreDin> freDins) {
        this.freDins = freDins;
    }
    public Set<GtoOtr> getGtoOtrs() {
        return this.gtoOtrs;
    }
    
    public void setGtoOtrs(Set<GtoOtr> gtoOtrs) {
        this.gtoOtrs = gtoOtrs;
    }
    public Set<ApoCon> getApoCons() {
        return this.apoCons;
    }
    
    public void setApoCons(Set<ApoCon> apoCons) {
        this.apoCons = apoCons;
    }
    public Set<ApoPad> getApoPads() {
        return this.apoPads;
    }
    
    public void setApoPads(Set<ApoPad> apoPads) {
        this.apoPads = apoPads;
    }
    public Set<BurHis> getBurHises() {
        return this.burHises;
    }
    
    public void setBurHises(Set<BurHis> burHises) {
        this.burHises = burHises;
    }
    public Set<OpnMap> getOpnMaps() {
        return this.opnMaps;
    }
    
    public void setOpnMaps(Set<OpnMap> opnMaps) {
        this.opnMaps = opnMaps;
    }




}


