package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CatPsi generated by hbm2java
 */
public class CatPsi  implements java.io.Serializable {


     private BigDecimal catPsiId;
     private Cal cal;
     private String catPsiDes;
     private Set<RelPsiSoc> relPsiSocs = new HashSet<RelPsiSoc>(0);

    public CatPsi() {
    }

	
    public CatPsi(BigDecimal catPsiId) {
        this.catPsiId = catPsiId;
    }
    public CatPsi(BigDecimal catPsiId, Cal cal, String catPsiDes, Set<RelPsiSoc> relPsiSocs) {
       this.catPsiId = catPsiId;
       this.cal = cal;
       this.catPsiDes = catPsiDes;
       this.relPsiSocs = relPsiSocs;
    }
   
    public BigDecimal getCatPsiId() {
        return this.catPsiId;
    }
    
    public void setCatPsiId(BigDecimal catPsiId) {
        this.catPsiId = catPsiId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getCatPsiDes() {
        return this.catPsiDes;
    }
    
    public void setCatPsiDes(String catPsiDes) {
        this.catPsiDes = catPsiDes;
    }
    public Set<RelPsiSoc> getRelPsiSocs() {
        return this.relPsiSocs;
    }
    
    public void setRelPsiSocs(Set<RelPsiSoc> relPsiSocs) {
        this.relPsiSocs = relPsiSocs;
    }




}


