package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CliMta generated by hbm2java
 */
public class CliMta  implements java.io.Serializable {


     private int cliMtaId;
     private Cli cli;
     private NivEst nivEst;
     private DinExt dinExt;
     private Cal cal;
     private ProAnoGto proAnoGto;
     private BanPorUso banPorUso;
     private BurUso burUso;
     private DepEco depEco;
     private Mig mig;
     private Edo edo;
     private TipRes tipRes;
     private OpnBar opnBar;
     private Rol rol;
     private Rel rel;
     private Eda eda;
     private BurAct burAct;
     private Ocp ocp;
     private TipEmp tipEmp;
     private BurHis burHis;
     private Ptm ptm;
     private BurAnt burAnt;
     private ParPlt parPlt;
     private BurPag burPag;
     private Gpo gpo;
     private Rld rld;
     private AsoPar asoPar;
     private ActExt actExt;
     private EdoCvl edoCvl;
     private Ing ing;
     private BanPorPag banPorPag;
     private Sex sex;
     private Date cliFecNac;
     private String codPosId;
     private Double cliAntRes;
     private Double cliAntEmp;
     private int banCmpId;
     private Character cliIndTarCre;
     private Character cliIndBurCre;
     private String cliDesOcu;
     private int cliIngMen;
     private int desId;
     private int cliValViv;
     private int cliValMen;
     private Set<CliBur> cliBurs = new HashSet<CliBur>(0);
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public CliMta() {
    }

	
    public CliMta(int cliMtaId) {
        this.cliMtaId = cliMtaId;
    }
    public CliMta(int cliMtaId, Cli cli, NivEst nivEst, DinExt dinExt, Cal cal, ProAnoGto proAnoGto, BanPorUso banPorUso, BurUso burUso, DepEco depEco, Mig mig, Edo edo, TipRes tipRes, OpnBar opnBar, Rol rol, Rel rel, Eda eda, BurAct burAct, Ocp ocp, TipEmp tipEmp, BurHis burHis, Ptm ptm, BurAnt burAnt, ParPlt parPlt, BurPag burPag, Gpo gpo, Rld rld, AsoPar asoPar, ActExt actExt, EdoCvl edoCvl, Ing ing, BanPorPag banPorPag, Sex sex, Date cliFecNac, String codPosId, Double cliAntRes, Double cliAntEmp, int banCmpId, Character cliIndTarCre, Character cliIndBurCre, String cliDesOcu, int cliIngMen, int desId, int cliValViv, int cliValMen, Set<CliBur> cliBurs, Set<CliGol> cliGols) {
       this.cliMtaId = cliMtaId;
       this.cli = cli;
       this.nivEst = nivEst;
       this.dinExt = dinExt;
       this.cal = cal;
       this.proAnoGto = proAnoGto;
       this.banPorUso = banPorUso;
       this.burUso = burUso;
       this.depEco = depEco;
       this.mig = mig;
       this.edo = edo;
       this.tipRes = tipRes;
       this.opnBar = opnBar;
       this.rol = rol;
       this.rel = rel;
       this.eda = eda;
       this.burAct = burAct;
       this.ocp = ocp;
       this.tipEmp = tipEmp;
       this.burHis = burHis;
       this.ptm = ptm;
       this.burAnt = burAnt;
       this.parPlt = parPlt;
       this.burPag = burPag;
       this.gpo = gpo;
       this.rld = rld;
       this.asoPar = asoPar;
       this.actExt = actExt;
       this.edoCvl = edoCvl;
       this.ing = ing;
       this.banPorPag = banPorPag;
       this.sex = sex;
       this.cliFecNac = cliFecNac;
       this.codPosId = codPosId;
       this.cliAntRes = cliAntRes;
       this.cliAntEmp = cliAntEmp;
       this.banCmpId = banCmpId;
       this.cliIndTarCre = cliIndTarCre;
       this.cliIndBurCre = cliIndBurCre;
       this.cliDesOcu = cliDesOcu;
       this.cliIngMen = cliIngMen;
       this.desId = desId;
       this.cliValViv = cliValViv;
       this.cliValMen = cliValMen;
       this.cliBurs = cliBurs;
       this.cliGols = cliGols;
    }
   
    public int getCliMtaId() {
        return this.cliMtaId;
    }
    
    public void setCliMtaId(int cliMtaId) {
        this.cliMtaId = cliMtaId;
    }
    public Cli getCli() {
        return this.cli;
    }
    
    public void setCli(Cli cli) {
        this.cli = cli;
    }
    public NivEst getNivEst() {
        return this.nivEst;
    }
    
    public void setNivEst(NivEst nivEst) {
        this.nivEst = nivEst;
    }
    public DinExt getDinExt() {
        return this.dinExt;
    }
    
    public void setDinExt(DinExt dinExt) {
        this.dinExt = dinExt;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public ProAnoGto getProAnoGto() {
        return this.proAnoGto;
    }
    
    public void setProAnoGto(ProAnoGto proAnoGto) {
        this.proAnoGto = proAnoGto;
    }
    public BanPorUso getBanPorUso() {
        return this.banPorUso;
    }
    
    public void setBanPorUso(BanPorUso banPorUso) {
        this.banPorUso = banPorUso;
    }
    public BurUso getBurUso() {
        return this.burUso;
    }
    
    public void setBurUso(BurUso burUso) {
        this.burUso = burUso;
    }
    public DepEco getDepEco() {
        return this.depEco;
    }
    
    public void setDepEco(DepEco depEco) {
        this.depEco = depEco;
    }
    public Mig getMig() {
        return this.mig;
    }
    
    public void setMig(Mig mig) {
        this.mig = mig;
    }
    public Edo getEdo() {
        return this.edo;
    }
    
    public void setEdo(Edo edo) {
        this.edo = edo;
    }
    public TipRes getTipRes() {
        return this.tipRes;
    }
    
    public void setTipRes(TipRes tipRes) {
        this.tipRes = tipRes;
    }
    public OpnBar getOpnBar() {
        return this.opnBar;
    }
    
    public void setOpnBar(OpnBar opnBar) {
        this.opnBar = opnBar;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Rel getRel() {
        return this.rel;
    }
    
    public void setRel(Rel rel) {
        this.rel = rel;
    }
    public Eda getEda() {
        return this.eda;
    }
    
    public void setEda(Eda eda) {
        this.eda = eda;
    }
    public BurAct getBurAct() {
        return this.burAct;
    }
    
    public void setBurAct(BurAct burAct) {
        this.burAct = burAct;
    }
    public Ocp getOcp() {
        return this.ocp;
    }
    
    public void setOcp(Ocp ocp) {
        this.ocp = ocp;
    }
    public TipEmp getTipEmp() {
        return this.tipEmp;
    }
    
    public void setTipEmp(TipEmp tipEmp) {
        this.tipEmp = tipEmp;
    }
    public BurHis getBurHis() {
        return this.burHis;
    }
    
    public void setBurHis(BurHis burHis) {
        this.burHis = burHis;
    }
    public Ptm getPtm() {
        return this.ptm;
    }
    
    public void setPtm(Ptm ptm) {
        this.ptm = ptm;
    }
    public BurAnt getBurAnt() {
        return this.burAnt;
    }
    
    public void setBurAnt(BurAnt burAnt) {
        this.burAnt = burAnt;
    }
    public ParPlt getParPlt() {
        return this.parPlt;
    }
    
    public void setParPlt(ParPlt parPlt) {
        this.parPlt = parPlt;
    }
    public BurPag getBurPag() {
        return this.burPag;
    }
    
    public void setBurPag(BurPag burPag) {
        this.burPag = burPag;
    }
    public Gpo getGpo() {
        return this.gpo;
    }
    
    public void setGpo(Gpo gpo) {
        this.gpo = gpo;
    }
    public Rld getRld() {
        return this.rld;
    }
    
    public void setRld(Rld rld) {
        this.rld = rld;
    }
    public AsoPar getAsoPar() {
        return this.asoPar;
    }
    
    public void setAsoPar(AsoPar asoPar) {
        this.asoPar = asoPar;
    }
    public ActExt getActExt() {
        return this.actExt;
    }
    
    public void setActExt(ActExt actExt) {
        this.actExt = actExt;
    }
    public EdoCvl getEdoCvl() {
        return this.edoCvl;
    }
    
    public void setEdoCvl(EdoCvl edoCvl) {
        this.edoCvl = edoCvl;
    }
    public Ing getIng() {
        return this.ing;
    }
    
    public void setIng(Ing ing) {
        this.ing = ing;
    }
    public BanPorPag getBanPorPag() {
        return this.banPorPag;
    }
    
    public void setBanPorPag(BanPorPag banPorPag) {
        this.banPorPag = banPorPag;
    }
    public Sex getSex() {
        return this.sex;
    }
    
    public void setSex(Sex sex) {
        this.sex = sex;
    }
    public Date getCliFecNac() {
        return this.cliFecNac;
    }
    
    public void setCliFecNac(Date cliFecNac) {
        this.cliFecNac = cliFecNac;
    }
    public String getCodPosId() {
        return this.codPosId;
    }
    
    public void setCodPosId(String codPosId) {
        this.codPosId = codPosId;
    }
    public Double getCliAntRes() {
        return this.cliAntRes;
    }
    
    public void setCliAntRes(Double cliAntRes) {
        this.cliAntRes = cliAntRes;
    }
    public Double getCliAntEmp() {
        return this.cliAntEmp;
    }
    
    public void setCliAntEmp(Double cliAntEmp) {
        this.cliAntEmp = cliAntEmp;
    }
    public int getBanCmpId() {
        return this.banCmpId;
    }
    
    public void setBanCmpId(int banCmpId) {
        this.banCmpId = banCmpId;
    }
    public Character getCliIndTarCre() {
        return this.cliIndTarCre;
    }
    
    public void setCliIndTarCre(Character cliIndTarCre) {
        this.cliIndTarCre = cliIndTarCre;
    }
    public Character getCliIndBurCre() {
        return this.cliIndBurCre;
    }
    
    public void setCliIndBurCre(Character cliIndBurCre) {
        this.cliIndBurCre = cliIndBurCre;
    }
    public String getCliDesOcu() {
        return this.cliDesOcu;
    }
    
    public void setCliDesOcu(String cliDesOcu) {
        this.cliDesOcu = cliDesOcu;
    }
    public int getCliIngMen() {
        return this.cliIngMen;
    }
    
    public void setCliIngMen(int cliIngMen) {
        this.cliIngMen = cliIngMen;
    }
    public int getDesId() {
        return this.desId;
    }
    
    public void setDesId(int desId) {
        this.desId = desId;
    }
    public int getCliValViv() {
        return this.cliValViv;
    }
    
    public void setCliValViv(int cliValViv) {
        this.cliValViv = cliValViv;
    }
    public int getCliValMen() {
        return this.cliValMen;
    }
    
    public void setCliValMen(int cliValMen) {
        this.cliValMen = cliValMen;
    }
    public Set<CliBur> getCliBurs() {
        return this.cliBurs;
    }
    
    public void setCliBurs(Set<CliBur> cliBurs) {
        this.cliBurs = cliBurs;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


