package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA



/**
 * CodPos generated by hbm2java
 */
public class CodPos  implements java.io.Serializable {


     private String codPosId;
     private Edo edo;
     private String codPosNomMun;

    public CodPos() {
    }

	
    public CodPos(String codPosId) {
        this.codPosId = codPosId;
    }
    public CodPos(String codPosId, Edo edo, String codPosNomMun) {
       this.codPosId = codPosId;
       this.edo = edo;
       this.codPosNomMun = codPosNomMun;
    }
   
    public String getCodPosId() {
        return this.codPosId;
    }
    
    public void setCodPosId(String codPosId) {
        this.codPosId = codPosId;
    }
    public Edo getEdo() {
        return this.edo;
    }
    
    public void setEdo(Edo edo) {
        this.edo = edo;
    }
    public String getCodPosNomMun() {
        return this.codPosNomMun;
    }
    
    public void setCodPosNomMun(String codPosNomMun) {
        this.codPosNomMun = codPosNomMun;
    }




}


