package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * ConAma generated by hbm2java
 */
public class ConAma  implements java.io.Serializable {


     private BigDecimal conAmaId;
     private Cal cal;
     private String conAmaDes;
     private Double conAmaLimInf;
     private Double conAmaLimSup;
     private BigDecimal conAmaOrdPre;
     private Double conAmaPto;
     private Double conAmaWoe;
     private String conAmaDesLar;

    public ConAma() {
    }

	
    public ConAma(BigDecimal conAmaId) {
        this.conAmaId = conAmaId;
    }
    public ConAma(BigDecimal conAmaId, Cal cal, String conAmaDes, Double conAmaLimInf, Double conAmaLimSup, BigDecimal conAmaOrdPre, Double conAmaPto, Double conAmaWoe, String conAmaDesLar) {
       this.conAmaId = conAmaId;
       this.cal = cal;
       this.conAmaDes = conAmaDes;
       this.conAmaLimInf = conAmaLimInf;
       this.conAmaLimSup = conAmaLimSup;
       this.conAmaOrdPre = conAmaOrdPre;
       this.conAmaPto = conAmaPto;
       this.conAmaWoe = conAmaWoe;
       this.conAmaDesLar = conAmaDesLar;
    }
   
    public BigDecimal getConAmaId() {
        return this.conAmaId;
    }
    
    public void setConAmaId(BigDecimal conAmaId) {
        this.conAmaId = conAmaId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getConAmaDes() {
        return this.conAmaDes;
    }
    
    public void setConAmaDes(String conAmaDes) {
        this.conAmaDes = conAmaDes;
    }
    public Double getConAmaLimInf() {
        return this.conAmaLimInf;
    }
    
    public void setConAmaLimInf(Double conAmaLimInf) {
        this.conAmaLimInf = conAmaLimInf;
    }
    public Double getConAmaLimSup() {
        return this.conAmaLimSup;
    }
    
    public void setConAmaLimSup(Double conAmaLimSup) {
        this.conAmaLimSup = conAmaLimSup;
    }
    public BigDecimal getConAmaOrdPre() {
        return this.conAmaOrdPre;
    }
    
    public void setConAmaOrdPre(BigDecimal conAmaOrdPre) {
        this.conAmaOrdPre = conAmaOrdPre;
    }
    public Double getConAmaPto() {
        return this.conAmaPto;
    }
    
    public void setConAmaPto(Double conAmaPto) {
        this.conAmaPto = conAmaPto;
    }
    public Double getConAmaWoe() {
        return this.conAmaWoe;
    }
    
    public void setConAmaWoe(Double conAmaWoe) {
        this.conAmaWoe = conAmaWoe;
    }
    public String getConAmaDesLar() {
        return this.conAmaDesLar;
    }
    
    public void setConAmaDesLar(String conAmaDesLar) {
        this.conAmaDesLar = conAmaDesLar;
    }




}


