package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DepEco generated by hbm2java
 */
public class DepEco  implements java.io.Serializable {


     private BigDecimal depEcoId;
     private Cal cal;
     private String depEcoDes;
     private Double depEcoLimInf;
     private Double depEcoLimSup;
     private BigDecimal depEcoOrdPre;
     private Double depEcoPto;
     private Double depEcoWoe;
     private String depEcoDesLar;
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);

    public DepEco() {
    }

	
    public DepEco(BigDecimal depEcoId) {
        this.depEcoId = depEcoId;
    }
    public DepEco(BigDecimal depEcoId, Cal cal, String depEcoDes, Double depEcoLimInf, Double depEcoLimSup, BigDecimal depEcoOrdPre, Double depEcoPto, Double depEcoWoe, String depEcoDesLar, Set<CliMta> cliMtas) {
       this.depEcoId = depEcoId;
       this.cal = cal;
       this.depEcoDes = depEcoDes;
       this.depEcoLimInf = depEcoLimInf;
       this.depEcoLimSup = depEcoLimSup;
       this.depEcoOrdPre = depEcoOrdPre;
       this.depEcoPto = depEcoPto;
       this.depEcoWoe = depEcoWoe;
       this.depEcoDesLar = depEcoDesLar;
       this.cliMtas = cliMtas;
    }
   
    public BigDecimal getDepEcoId() {
        return this.depEcoId;
    }
    
    public void setDepEcoId(BigDecimal depEcoId) {
        this.depEcoId = depEcoId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getDepEcoDes() {
        return this.depEcoDes;
    }
    
    public void setDepEcoDes(String depEcoDes) {
        this.depEcoDes = depEcoDes;
    }
    public Double getDepEcoLimInf() {
        return this.depEcoLimInf;
    }
    
    public void setDepEcoLimInf(Double depEcoLimInf) {
        this.depEcoLimInf = depEcoLimInf;
    }
    public Double getDepEcoLimSup() {
        return this.depEcoLimSup;
    }
    
    public void setDepEcoLimSup(Double depEcoLimSup) {
        this.depEcoLimSup = depEcoLimSup;
    }
    public BigDecimal getDepEcoOrdPre() {
        return this.depEcoOrdPre;
    }
    
    public void setDepEcoOrdPre(BigDecimal depEcoOrdPre) {
        this.depEcoOrdPre = depEcoOrdPre;
    }
    public Double getDepEcoPto() {
        return this.depEcoPto;
    }
    
    public void setDepEcoPto(Double depEcoPto) {
        this.depEcoPto = depEcoPto;
    }
    public Double getDepEcoWoe() {
        return this.depEcoWoe;
    }
    
    public void setDepEcoWoe(Double depEcoWoe) {
        this.depEcoWoe = depEcoWoe;
    }
    public String getDepEcoDesLar() {
        return this.depEcoDesLar;
    }
    
    public void setDepEcoDesLar(String depEcoDesLar) {
        this.depEcoDesLar = depEcoDesLar;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }




}


