package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Des generated by hbm2java
 */
public class Des  implements java.io.Serializable {


     private BigDecimal desId;
     private Edo edo;
     private Cal cal;
     private String desDes;

    public Des() {
    }

	
    public Des(BigDecimal desId) {
        this.desId = desId;
    }
    public Des(BigDecimal desId, Edo edo, Cal cal, String desDes) {
       this.desId = desId;
       this.edo = edo;
       this.cal = cal;
       this.desDes = desDes;
    }
   
    public BigDecimal getDesId() {
        return this.desId;
    }
    
    public void setDesId(BigDecimal desId) {
        this.desId = desId;
    }
    public Edo getEdo() {
        return this.edo;
    }
    
    public void setEdo(Edo edo) {
        this.edo = edo;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getDesDes() {
        return this.desDes;
    }
    
    public void setDesDes(String desDes) {
        this.desDes = desDes;
    }




}


