package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DinExt generated by hbm2java
 */
public class DinExt  implements java.io.Serializable {


     private BigDecimal dinExtId;
     private Cal cal;
     private String dinExtDes;
     private Double dinExtLimInf;
     private Double dinExtLimSup;
     private BigDecimal dinExtOrdPre;
     private Double dinExtPto;
     private Double dinExtWoe;
     private String dinExtDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);

    public DinExt() {
    }

	
    public DinExt(BigDecimal dinExtId) {
        this.dinExtId = dinExtId;
    }
    public DinExt(BigDecimal dinExtId, Cal cal, String dinExtDes, Double dinExtLimInf, Double dinExtLimSup, BigDecimal dinExtOrdPre, Double dinExtPto, Double dinExtWoe, String dinExtDesLar, Set<CliGol> cliGols, Set<CliMta> cliMtas) {
       this.dinExtId = dinExtId;
       this.cal = cal;
       this.dinExtDes = dinExtDes;
       this.dinExtLimInf = dinExtLimInf;
       this.dinExtLimSup = dinExtLimSup;
       this.dinExtOrdPre = dinExtOrdPre;
       this.dinExtPto = dinExtPto;
       this.dinExtWoe = dinExtWoe;
       this.dinExtDesLar = dinExtDesLar;
       this.cliGols = cliGols;
       this.cliMtas = cliMtas;
    }
   
    public BigDecimal getDinExtId() {
        return this.dinExtId;
    }
    
    public void setDinExtId(BigDecimal dinExtId) {
        this.dinExtId = dinExtId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getDinExtDes() {
        return this.dinExtDes;
    }
    
    public void setDinExtDes(String dinExtDes) {
        this.dinExtDes = dinExtDes;
    }
    public Double getDinExtLimInf() {
        return this.dinExtLimInf;
    }
    
    public void setDinExtLimInf(Double dinExtLimInf) {
        this.dinExtLimInf = dinExtLimInf;
    }
    public Double getDinExtLimSup() {
        return this.dinExtLimSup;
    }
    
    public void setDinExtLimSup(Double dinExtLimSup) {
        this.dinExtLimSup = dinExtLimSup;
    }
    public BigDecimal getDinExtOrdPre() {
        return this.dinExtOrdPre;
    }
    
    public void setDinExtOrdPre(BigDecimal dinExtOrdPre) {
        this.dinExtOrdPre = dinExtOrdPre;
    }
    public Double getDinExtPto() {
        return this.dinExtPto;
    }
    
    public void setDinExtPto(Double dinExtPto) {
        this.dinExtPto = dinExtPto;
    }
    public Double getDinExtWoe() {
        return this.dinExtWoe;
    }
    
    public void setDinExtWoe(Double dinExtWoe) {
        this.dinExtWoe = dinExtWoe;
    }
    public String getDinExtDesLar() {
        return this.dinExtDesLar;
    }
    
    public void setDinExtDesLar(String dinExtDesLar) {
        this.dinExtDesLar = dinExtDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }




}


