package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Edo generated by hbm2java
 */
public class Edo  implements java.io.Serializable {


     private BigDecimal edoId;
     private Cal cal;
     private String edoDes;
     private BigDecimal edoOrdPre;
     private Double edoWoe;
     private String edoDesLar;
     private Double edoRcg;
     private Set<CodPos> codPoses = new HashSet<CodPos>(0);
     private Set<CliBhr> cliBhrs = new HashSet<CliBhr>(0);
     private Set<Des> deses = new HashSet<Des>(0);
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);

    public Edo() {
    }

	
    public Edo(BigDecimal edoId) {
        this.edoId = edoId;
    }
    public Edo(BigDecimal edoId, Cal cal, String edoDes, BigDecimal edoOrdPre, Double edoWoe, String edoDesLar, Double edoRcg, Set<CodPos> codPoses, Set<CliBhr> cliBhrs, Set<Des> deses, Set<CliMta> cliMtas) {
       this.edoId = edoId;
       this.cal = cal;
       this.edoDes = edoDes;
       this.edoOrdPre = edoOrdPre;
       this.edoWoe = edoWoe;
       this.edoDesLar = edoDesLar;
       this.edoRcg = edoRcg;
       this.codPoses = codPoses;
       this.cliBhrs = cliBhrs;
       this.deses = deses;
       this.cliMtas = cliMtas;
    }
   
    public BigDecimal getEdoId() {
        return this.edoId;
    }
    
    public void setEdoId(BigDecimal edoId) {
        this.edoId = edoId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getEdoDes() {
        return this.edoDes;
    }
    
    public void setEdoDes(String edoDes) {
        this.edoDes = edoDes;
    }
    public BigDecimal getEdoOrdPre() {
        return this.edoOrdPre;
    }
    
    public void setEdoOrdPre(BigDecimal edoOrdPre) {
        this.edoOrdPre = edoOrdPre;
    }
    public Double getEdoWoe() {
        return this.edoWoe;
    }
    
    public void setEdoWoe(Double edoWoe) {
        this.edoWoe = edoWoe;
    }
    public String getEdoDesLar() {
        return this.edoDesLar;
    }
    
    public void setEdoDesLar(String edoDesLar) {
        this.edoDesLar = edoDesLar;
    }
    public Double getEdoRcg() {
        return this.edoRcg;
    }
    
    public void setEdoRcg(Double edoRcg) {
        this.edoRcg = edoRcg;
    }
    public Set<CodPos> getCodPoses() {
        return this.codPoses;
    }
    
    public void setCodPoses(Set<CodPos> codPoses) {
        this.codPoses = codPoses;
    }
    public Set<CliBhr> getCliBhrs() {
        return this.cliBhrs;
    }
    
    public void setCliBhrs(Set<CliBhr> cliBhrs) {
        this.cliBhrs = cliBhrs;
    }
    public Set<Des> getDeses() {
        return this.deses;
    }
    
    public void setDeses(Set<Des> deses) {
        this.deses = deses;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }




}


