package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * FtrPpr generated by hbm2java
 */
public class FtrPpr  implements java.io.Serializable {


     private BigDecimal ftrPprId;
     private String ftrPprCls;
     private Double ftrPprMes;
     private Double ftrPprFtr;
     private Set<CliPpr> cliPprs = new HashSet<CliPpr>(0);

    public FtrPpr() {
    }

	
    public FtrPpr(BigDecimal ftrPprId) {
        this.ftrPprId = ftrPprId;
    }
    public FtrPpr(BigDecimal ftrPprId, String ftrPprCls, Double ftrPprMes, Double ftrPprFtr, Set<CliPpr> cliPprs) {
       this.ftrPprId = ftrPprId;
       this.ftrPprCls = ftrPprCls;
       this.ftrPprMes = ftrPprMes;
       this.ftrPprFtr = ftrPprFtr;
       this.cliPprs = cliPprs;
    }
   
    public BigDecimal getFtrPprId() {
        return this.ftrPprId;
    }
    
    public void setFtrPprId(BigDecimal ftrPprId) {
        this.ftrPprId = ftrPprId;
    }
    public String getFtrPprCls() {
        return this.ftrPprCls;
    }
    
    public void setFtrPprCls(String ftrPprCls) {
        this.ftrPprCls = ftrPprCls;
    }
    public Double getFtrPprMes() {
        return this.ftrPprMes;
    }
    
    public void setFtrPprMes(Double ftrPprMes) {
        this.ftrPprMes = ftrPprMes;
    }
    public Double getFtrPprFtr() {
        return this.ftrPprFtr;
    }
    
    public void setFtrPprFtr(Double ftrPprFtr) {
        this.ftrPprFtr = ftrPprFtr;
    }
    public Set<CliPpr> getCliPprs() {
        return this.cliPprs;
    }
    
    public void setCliPprs(Set<CliPpr> cliPprs) {
        this.cliPprs = cliPprs;
    }




}


