package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * GtoCre generated by hbm2java
 */
public class GtoCre  implements java.io.Serializable {


     private BigDecimal gtoCreId;
     private Cal cal;
     private String gtoCreDes;
     private Double gtoCreLimInf;
     private Double gtoCreLimSup;
     private BigDecimal gtoCreOrdPre;
     private Double gtoCrePto;
     private Double gtoCreWoe;
     private String gtoCreDesLar;

    public GtoCre() {
    }

	
    public GtoCre(BigDecimal gtoCreId) {
        this.gtoCreId = gtoCreId;
    }
    public GtoCre(BigDecimal gtoCreId, Cal cal, String gtoCreDes, Double gtoCreLimInf, Double gtoCreLimSup, BigDecimal gtoCreOrdPre, Double gtoCrePto, Double gtoCreWoe, String gtoCreDesLar) {
       this.gtoCreId = gtoCreId;
       this.cal = cal;
       this.gtoCreDes = gtoCreDes;
       this.gtoCreLimInf = gtoCreLimInf;
       this.gtoCreLimSup = gtoCreLimSup;
       this.gtoCreOrdPre = gtoCreOrdPre;
       this.gtoCrePto = gtoCrePto;
       this.gtoCreWoe = gtoCreWoe;
       this.gtoCreDesLar = gtoCreDesLar;
    }
   
    public BigDecimal getGtoCreId() {
        return this.gtoCreId;
    }
    
    public void setGtoCreId(BigDecimal gtoCreId) {
        this.gtoCreId = gtoCreId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoCreDes() {
        return this.gtoCreDes;
    }
    
    public void setGtoCreDes(String gtoCreDes) {
        this.gtoCreDes = gtoCreDes;
    }
    public Double getGtoCreLimInf() {
        return this.gtoCreLimInf;
    }
    
    public void setGtoCreLimInf(Double gtoCreLimInf) {
        this.gtoCreLimInf = gtoCreLimInf;
    }
    public Double getGtoCreLimSup() {
        return this.gtoCreLimSup;
    }
    
    public void setGtoCreLimSup(Double gtoCreLimSup) {
        this.gtoCreLimSup = gtoCreLimSup;
    }
    public BigDecimal getGtoCreOrdPre() {
        return this.gtoCreOrdPre;
    }
    
    public void setGtoCreOrdPre(BigDecimal gtoCreOrdPre) {
        this.gtoCreOrdPre = gtoCreOrdPre;
    }
    public Double getGtoCrePto() {
        return this.gtoCrePto;
    }
    
    public void setGtoCrePto(Double gtoCrePto) {
        this.gtoCrePto = gtoCrePto;
    }
    public Double getGtoCreWoe() {
        return this.gtoCreWoe;
    }
    
    public void setGtoCreWoe(Double gtoCreWoe) {
        this.gtoCreWoe = gtoCreWoe;
    }
    public String getGtoCreDesLar() {
        return this.gtoCreDesLar;
    }
    
    public void setGtoCreDesLar(String gtoCreDesLar) {
        this.gtoCreDesLar = gtoCreDesLar;
    }




}


