package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * GtoDeu generated by hbm2java
 */
public class GtoDeu  implements java.io.Serializable {


     private BigDecimal gtoDeuId;
     private Cal cal;
     private String gtoDeuDes;
     private Double gtoDeuLimInf;
     private Double gtoDeuLimSup;
     private BigDecimal gtoDeuOrdPre;
     private Double gtoDeuPto;
     private Double gtoDeuWoe;
     private String gtoDeuDesLar;
     private Set<CliGol> cliGolsForGtoDeuHId = new HashSet<CliGol>(0);
     private Set<CliGol> cliGolsForGtoDeuId = new HashSet<CliGol>(0);

    public GtoDeu() {
    }

	
    public GtoDeu(BigDecimal gtoDeuId) {
        this.gtoDeuId = gtoDeuId;
    }
    public GtoDeu(BigDecimal gtoDeuId, Cal cal, String gtoDeuDes, Double gtoDeuLimInf, Double gtoDeuLimSup, BigDecimal gtoDeuOrdPre, Double gtoDeuPto, Double gtoDeuWoe, String gtoDeuDesLar, Set<CliGol> cliGolsForGtoDeuHId, Set<CliGol> cliGolsForGtoDeuId) {
       this.gtoDeuId = gtoDeuId;
       this.cal = cal;
       this.gtoDeuDes = gtoDeuDes;
       this.gtoDeuLimInf = gtoDeuLimInf;
       this.gtoDeuLimSup = gtoDeuLimSup;
       this.gtoDeuOrdPre = gtoDeuOrdPre;
       this.gtoDeuPto = gtoDeuPto;
       this.gtoDeuWoe = gtoDeuWoe;
       this.gtoDeuDesLar = gtoDeuDesLar;
       this.cliGolsForGtoDeuHId = cliGolsForGtoDeuHId;
       this.cliGolsForGtoDeuId = cliGolsForGtoDeuId;
    }
   
    public BigDecimal getGtoDeuId() {
        return this.gtoDeuId;
    }
    
    public void setGtoDeuId(BigDecimal gtoDeuId) {
        this.gtoDeuId = gtoDeuId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoDeuDes() {
        return this.gtoDeuDes;
    }
    
    public void setGtoDeuDes(String gtoDeuDes) {
        this.gtoDeuDes = gtoDeuDes;
    }
    public Double getGtoDeuLimInf() {
        return this.gtoDeuLimInf;
    }
    
    public void setGtoDeuLimInf(Double gtoDeuLimInf) {
        this.gtoDeuLimInf = gtoDeuLimInf;
    }
    public Double getGtoDeuLimSup() {
        return this.gtoDeuLimSup;
    }
    
    public void setGtoDeuLimSup(Double gtoDeuLimSup) {
        this.gtoDeuLimSup = gtoDeuLimSup;
    }
    public BigDecimal getGtoDeuOrdPre() {
        return this.gtoDeuOrdPre;
    }
    
    public void setGtoDeuOrdPre(BigDecimal gtoDeuOrdPre) {
        this.gtoDeuOrdPre = gtoDeuOrdPre;
    }
    public Double getGtoDeuPto() {
        return this.gtoDeuPto;
    }
    
    public void setGtoDeuPto(Double gtoDeuPto) {
        this.gtoDeuPto = gtoDeuPto;
    }
    public Double getGtoDeuWoe() {
        return this.gtoDeuWoe;
    }
    
    public void setGtoDeuWoe(Double gtoDeuWoe) {
        this.gtoDeuWoe = gtoDeuWoe;
    }
    public String getGtoDeuDesLar() {
        return this.gtoDeuDesLar;
    }
    
    public void setGtoDeuDesLar(String gtoDeuDesLar) {
        this.gtoDeuDesLar = gtoDeuDesLar;
    }
    public Set<CliGol> getCliGolsForGtoDeuHId() {
        return this.cliGolsForGtoDeuHId;
    }
    
    public void setCliGolsForGtoDeuHId(Set<CliGol> cliGolsForGtoDeuHId) {
        this.cliGolsForGtoDeuHId = cliGolsForGtoDeuHId;
    }
    public Set<CliGol> getCliGolsForGtoDeuId() {
        return this.cliGolsForGtoDeuId;
    }
    
    public void setCliGolsForGtoDeuId(Set<CliGol> cliGolsForGtoDeuId) {
        this.cliGolsForGtoDeuId = cliGolsForGtoDeuId;
    }




}


