package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * GtoLim generated by hbm2java
 */
public class GtoLim  implements java.io.Serializable {


     private BigDecimal gtoLimId;
     private Cal cal;
     private String gtoLimDes;
     private Double gtoLimLimInf;
     private Double gtoLimLimSup;
     private BigDecimal gtoLimOrdPre;
     private Double gtoLimPto;
     private Double gtoLimWoe;
     private String gtoLimDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public GtoLim() {
    }

	
    public GtoLim(BigDecimal gtoLimId) {
        this.gtoLimId = gtoLimId;
    }
    public GtoLim(BigDecimal gtoLimId, Cal cal, String gtoLimDes, Double gtoLimLimInf, Double gtoLimLimSup, BigDecimal gtoLimOrdPre, Double gtoLimPto, Double gtoLimWoe, String gtoLimDesLar, Set<CliGol> cliGols) {
       this.gtoLimId = gtoLimId;
       this.cal = cal;
       this.gtoLimDes = gtoLimDes;
       this.gtoLimLimInf = gtoLimLimInf;
       this.gtoLimLimSup = gtoLimLimSup;
       this.gtoLimOrdPre = gtoLimOrdPre;
       this.gtoLimPto = gtoLimPto;
       this.gtoLimWoe = gtoLimWoe;
       this.gtoLimDesLar = gtoLimDesLar;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getGtoLimId() {
        return this.gtoLimId;
    }
    
    public void setGtoLimId(BigDecimal gtoLimId) {
        this.gtoLimId = gtoLimId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoLimDes() {
        return this.gtoLimDes;
    }
    
    public void setGtoLimDes(String gtoLimDes) {
        this.gtoLimDes = gtoLimDes;
    }
    public Double getGtoLimLimInf() {
        return this.gtoLimLimInf;
    }
    
    public void setGtoLimLimInf(Double gtoLimLimInf) {
        this.gtoLimLimInf = gtoLimLimInf;
    }
    public Double getGtoLimLimSup() {
        return this.gtoLimLimSup;
    }
    
    public void setGtoLimLimSup(Double gtoLimLimSup) {
        this.gtoLimLimSup = gtoLimLimSup;
    }
    public BigDecimal getGtoLimOrdPre() {
        return this.gtoLimOrdPre;
    }
    
    public void setGtoLimOrdPre(BigDecimal gtoLimOrdPre) {
        this.gtoLimOrdPre = gtoLimOrdPre;
    }
    public Double getGtoLimPto() {
        return this.gtoLimPto;
    }
    
    public void setGtoLimPto(Double gtoLimPto) {
        this.gtoLimPto = gtoLimPto;
    }
    public Double getGtoLimWoe() {
        return this.gtoLimWoe;
    }
    
    public void setGtoLimWoe(Double gtoLimWoe) {
        this.gtoLimWoe = gtoLimWoe;
    }
    public String getGtoLimDesLar() {
        return this.gtoLimDesLar;
    }
    
    public void setGtoLimDesLar(String gtoLimDesLar) {
        this.gtoLimDesLar = gtoLimDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


