package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * GtoSot generated by hbm2java
 */
public class GtoSot  implements java.io.Serializable {


     private BigDecimal gtoSotId;
     private Cal cal;
     private String gtoSotDes;
     private Double gtoSotLimInf;
     private Double gtoSotLimSup;
     private BigDecimal gtoSotOrdPre;
     private Double gtoSotPto;
     private Double gtoSotWoe;
     private String gtoSotDesLar;

    public GtoSot() {
    }

	
    public GtoSot(BigDecimal gtoSotId) {
        this.gtoSotId = gtoSotId;
    }
    public GtoSot(BigDecimal gtoSotId, Cal cal, String gtoSotDes, Double gtoSotLimInf, Double gtoSotLimSup, BigDecimal gtoSotOrdPre, Double gtoSotPto, Double gtoSotWoe, String gtoSotDesLar) {
       this.gtoSotId = gtoSotId;
       this.cal = cal;
       this.gtoSotDes = gtoSotDes;
       this.gtoSotLimInf = gtoSotLimInf;
       this.gtoSotLimSup = gtoSotLimSup;
       this.gtoSotOrdPre = gtoSotOrdPre;
       this.gtoSotPto = gtoSotPto;
       this.gtoSotWoe = gtoSotWoe;
       this.gtoSotDesLar = gtoSotDesLar;
    }
   
    public BigDecimal getGtoSotId() {
        return this.gtoSotId;
    }
    
    public void setGtoSotId(BigDecimal gtoSotId) {
        this.gtoSotId = gtoSotId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoSotDes() {
        return this.gtoSotDes;
    }
    
    public void setGtoSotDes(String gtoSotDes) {
        this.gtoSotDes = gtoSotDes;
    }
    public Double getGtoSotLimInf() {
        return this.gtoSotLimInf;
    }
    
    public void setGtoSotLimInf(Double gtoSotLimInf) {
        this.gtoSotLimInf = gtoSotLimInf;
    }
    public Double getGtoSotLimSup() {
        return this.gtoSotLimSup;
    }
    
    public void setGtoSotLimSup(Double gtoSotLimSup) {
        this.gtoSotLimSup = gtoSotLimSup;
    }
    public BigDecimal getGtoSotOrdPre() {
        return this.gtoSotOrdPre;
    }
    
    public void setGtoSotOrdPre(BigDecimal gtoSotOrdPre) {
        this.gtoSotOrdPre = gtoSotOrdPre;
    }
    public Double getGtoSotPto() {
        return this.gtoSotPto;
    }
    
    public void setGtoSotPto(Double gtoSotPto) {
        this.gtoSotPto = gtoSotPto;
    }
    public Double getGtoSotWoe() {
        return this.gtoSotWoe;
    }
    
    public void setGtoSotWoe(Double gtoSotWoe) {
        this.gtoSotWoe = gtoSotWoe;
    }
    public String getGtoSotDesLar() {
        return this.gtoSotDesLar;
    }
    
    public void setGtoSotDesLar(String gtoSotDesLar) {
        this.gtoSotDesLar = gtoSotDesLar;
    }




}


