package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * GtoSab generated by hbm2java
 */
public class GtoSab  implements java.io.Serializable {


     private BigDecimal gtoSabId;
     private Cal cal;
     private String gtoSabDes;
     private Double gtoSabLimInf;
     private Double gtoSabLimSup;
     private BigDecimal gtoSabOrdPre;
     private Double gtoSabPto;
     private Double gtoSabWoe;
     private String gtoSabDesLar;

    public GtoSab() {
    }

	
    public GtoSab(BigDecimal gtoSabId) {
        this.gtoSabId = gtoSabId;
    }
    public GtoSab(BigDecimal gtoSabId, Cal cal, String gtoSabDes, Double gtoSabLimInf, Double gtoSabLimSup, BigDecimal gtoSabOrdPre, Double gtoSabPto, Double gtoSabWoe, String gtoSabDesLar) {
       this.gtoSabId = gtoSabId;
       this.cal = cal;
       this.gtoSabDes = gtoSabDes;
       this.gtoSabLimInf = gtoSabLimInf;
       this.gtoSabLimSup = gtoSabLimSup;
       this.gtoSabOrdPre = gtoSabOrdPre;
       this.gtoSabPto = gtoSabPto;
       this.gtoSabWoe = gtoSabWoe;
       this.gtoSabDesLar = gtoSabDesLar;
    }
   
    public BigDecimal getGtoSabId() {
        return this.gtoSabId;
    }
    
    public void setGtoSabId(BigDecimal gtoSabId) {
        this.gtoSabId = gtoSabId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoSabDes() {
        return this.gtoSabDes;
    }
    
    public void setGtoSabDes(String gtoSabDes) {
        this.gtoSabDes = gtoSabDes;
    }
    public Double getGtoSabLimInf() {
        return this.gtoSabLimInf;
    }
    
    public void setGtoSabLimInf(Double gtoSabLimInf) {
        this.gtoSabLimInf = gtoSabLimInf;
    }
    public Double getGtoSabLimSup() {
        return this.gtoSabLimSup;
    }
    
    public void setGtoSabLimSup(Double gtoSabLimSup) {
        this.gtoSabLimSup = gtoSabLimSup;
    }
    public BigDecimal getGtoSabOrdPre() {
        return this.gtoSabOrdPre;
    }
    
    public void setGtoSabOrdPre(BigDecimal gtoSabOrdPre) {
        this.gtoSabOrdPre = gtoSabOrdPre;
    }
    public Double getGtoSabPto() {
        return this.gtoSabPto;
    }
    
    public void setGtoSabPto(Double gtoSabPto) {
        this.gtoSabPto = gtoSabPto;
    }
    public Double getGtoSabWoe() {
        return this.gtoSabWoe;
    }
    
    public void setGtoSabWoe(Double gtoSabWoe) {
        this.gtoSabWoe = gtoSabWoe;
    }
    public String getGtoSabDesLar() {
        return this.gtoSabDesLar;
    }
    
    public void setGtoSabDesLar(String gtoSabDesLar) {
        this.gtoSabDesLar = gtoSabDesLar;
    }




}


