package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * GtoTrn generated by hbm2java
 */
public class GtoTrn  implements java.io.Serializable {


     private BigDecimal gtoTrnId;
     private Cal cal;
     private String gtoTrnDes;
     private Double gtoTrnLimInf;
     private Double gtoTrnLimSup;
     private BigDecimal gtoTrnOrdPre;
     private Double gtoTrnPto;
     private Double gtoTrnWoe;
     private String gtoTrnDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public GtoTrn() {
    }

	
    public GtoTrn(BigDecimal gtoTrnId) {
        this.gtoTrnId = gtoTrnId;
    }
    public GtoTrn(BigDecimal gtoTrnId, Cal cal, String gtoTrnDes, Double gtoTrnLimInf, Double gtoTrnLimSup, BigDecimal gtoTrnOrdPre, Double gtoTrnPto, Double gtoTrnWoe, String gtoTrnDesLar, Set<CliGol> cliGols) {
       this.gtoTrnId = gtoTrnId;
       this.cal = cal;
       this.gtoTrnDes = gtoTrnDes;
       this.gtoTrnLimInf = gtoTrnLimInf;
       this.gtoTrnLimSup = gtoTrnLimSup;
       this.gtoTrnOrdPre = gtoTrnOrdPre;
       this.gtoTrnPto = gtoTrnPto;
       this.gtoTrnWoe = gtoTrnWoe;
       this.gtoTrnDesLar = gtoTrnDesLar;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getGtoTrnId() {
        return this.gtoTrnId;
    }
    
    public void setGtoTrnId(BigDecimal gtoTrnId) {
        this.gtoTrnId = gtoTrnId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoTrnDes() {
        return this.gtoTrnDes;
    }
    
    public void setGtoTrnDes(String gtoTrnDes) {
        this.gtoTrnDes = gtoTrnDes;
    }
    public Double getGtoTrnLimInf() {
        return this.gtoTrnLimInf;
    }
    
    public void setGtoTrnLimInf(Double gtoTrnLimInf) {
        this.gtoTrnLimInf = gtoTrnLimInf;
    }
    public Double getGtoTrnLimSup() {
        return this.gtoTrnLimSup;
    }
    
    public void setGtoTrnLimSup(Double gtoTrnLimSup) {
        this.gtoTrnLimSup = gtoTrnLimSup;
    }
    public BigDecimal getGtoTrnOrdPre() {
        return this.gtoTrnOrdPre;
    }
    
    public void setGtoTrnOrdPre(BigDecimal gtoTrnOrdPre) {
        this.gtoTrnOrdPre = gtoTrnOrdPre;
    }
    public Double getGtoTrnPto() {
        return this.gtoTrnPto;
    }
    
    public void setGtoTrnPto(Double gtoTrnPto) {
        this.gtoTrnPto = gtoTrnPto;
    }
    public Double getGtoTrnWoe() {
        return this.gtoTrnWoe;
    }
    
    public void setGtoTrnWoe(Double gtoTrnWoe) {
        this.gtoTrnWoe = gtoTrnWoe;
    }
    public String getGtoTrnDesLar() {
        return this.gtoTrnDesLar;
    }
    
    public void setGtoTrnDesLar(String gtoTrnDesLar) {
        this.gtoTrnDesLar = gtoTrnDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


