package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * GtoVes generated by hbm2java
 */
public class GtoVes  implements java.io.Serializable {


     private BigDecimal gtoVesId;
     private Cal cal;
     private String gtoVesDes;
     private Double gtoVesLimInf;
     private Double gtoVesLimSup;
     private BigDecimal gtoVesOrdPre;
     private Double gtoVesPto;
     private Double gtoVesWoe;
     private String gtoVesDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public GtoVes() {
    }

	
    public GtoVes(BigDecimal gtoVesId) {
        this.gtoVesId = gtoVesId;
    }
    public GtoVes(BigDecimal gtoVesId, Cal cal, String gtoVesDes, Double gtoVesLimInf, Double gtoVesLimSup, BigDecimal gtoVesOrdPre, Double gtoVesPto, Double gtoVesWoe, String gtoVesDesLar, Set<CliGol> cliGols) {
       this.gtoVesId = gtoVesId;
       this.cal = cal;
       this.gtoVesDes = gtoVesDes;
       this.gtoVesLimInf = gtoVesLimInf;
       this.gtoVesLimSup = gtoVesLimSup;
       this.gtoVesOrdPre = gtoVesOrdPre;
       this.gtoVesPto = gtoVesPto;
       this.gtoVesWoe = gtoVesWoe;
       this.gtoVesDesLar = gtoVesDesLar;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getGtoVesId() {
        return this.gtoVesId;
    }
    
    public void setGtoVesId(BigDecimal gtoVesId) {
        this.gtoVesId = gtoVesId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getGtoVesDes() {
        return this.gtoVesDes;
    }
    
    public void setGtoVesDes(String gtoVesDes) {
        this.gtoVesDes = gtoVesDes;
    }
    public Double getGtoVesLimInf() {
        return this.gtoVesLimInf;
    }
    
    public void setGtoVesLimInf(Double gtoVesLimInf) {
        this.gtoVesLimInf = gtoVesLimInf;
    }
    public Double getGtoVesLimSup() {
        return this.gtoVesLimSup;
    }
    
    public void setGtoVesLimSup(Double gtoVesLimSup) {
        this.gtoVesLimSup = gtoVesLimSup;
    }
    public BigDecimal getGtoVesOrdPre() {
        return this.gtoVesOrdPre;
    }
    
    public void setGtoVesOrdPre(BigDecimal gtoVesOrdPre) {
        this.gtoVesOrdPre = gtoVesOrdPre;
    }
    public Double getGtoVesPto() {
        return this.gtoVesPto;
    }
    
    public void setGtoVesPto(Double gtoVesPto) {
        this.gtoVesPto = gtoVesPto;
    }
    public Double getGtoVesWoe() {
        return this.gtoVesWoe;
    }
    
    public void setGtoVesWoe(Double gtoVesWoe) {
        this.gtoVesWoe = gtoVesWoe;
    }
    public String getGtoVesDesLar() {
        return this.gtoVesDesLar;
    }
    
    public void setGtoVesDesLar(String gtoVesDesLar) {
        this.gtoVesDesLar = gtoVesDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


