package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * IRnt generated by hbm2java
 */
public class IRnt  implements java.io.Serializable {


     private BigDecimal IRntId;
     private Cal cal;
     private BigDecimal calId;
     private String IRntDes;
     private Double IRntLimInf;
     private Double IRntLimSup;
     private BigDecimal IRntOrdPre;
     private Double IRntPto;
     private Double IRntWoe;
     private String IRntDesLar;

    public IRnt() {
    }

	
    public IRnt(BigDecimal IRntId, Cal cal) {
        this.IRntId = IRntId;
        this.cal = cal;
    }
    public IRnt(BigDecimal IRntId, Cal cal, BigDecimal calId, String IRntDes, Double IRntLimInf, Double IRntLimSup, BigDecimal IRntOrdPre, Double IRntPto, Double IRntWoe, String IRntDesLar) {
       this.IRntId = IRntId;
       this.cal = cal;
       this.calId = calId;
       this.IRntDes = IRntDes;
       this.IRntLimInf = IRntLimInf;
       this.IRntLimSup = IRntLimSup;
       this.IRntOrdPre = IRntOrdPre;
       this.IRntPto = IRntPto;
       this.IRntWoe = IRntWoe;
       this.IRntDesLar = IRntDesLar;
    }
   
    public BigDecimal getIRntId() {
        return this.IRntId;
    }
    
    public void setIRntId(BigDecimal IRntId) {
        this.IRntId = IRntId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getIRntDes() {
        return this.IRntDes;
    }
    
    public void setIRntDes(String IRntDes) {
        this.IRntDes = IRntDes;
    }
    public Double getIRntLimInf() {
        return this.IRntLimInf;
    }
    
    public void setIRntLimInf(Double IRntLimInf) {
        this.IRntLimInf = IRntLimInf;
    }
    public Double getIRntLimSup() {
        return this.IRntLimSup;
    }
    
    public void setIRntLimSup(Double IRntLimSup) {
        this.IRntLimSup = IRntLimSup;
    }
    public BigDecimal getIRntOrdPre() {
        return this.IRntOrdPre;
    }
    
    public void setIRntOrdPre(BigDecimal IRntOrdPre) {
        this.IRntOrdPre = IRntOrdPre;
    }
    public Double getIRntPto() {
        return this.IRntPto;
    }
    
    public void setIRntPto(Double IRntPto) {
        this.IRntPto = IRntPto;
    }
    public Double getIRntWoe() {
        return this.IRntWoe;
    }
    
    public void setIRntWoe(Double IRntWoe) {
        this.IRntWoe = IRntWoe;
    }
    public String getIRntDesLar() {
        return this.IRntDesLar;
    }
    
    public void setIRntDesLar(String IRntDesLar) {
        this.IRntDesLar = IRntDesLar;
    }




}


