package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Mov generated by hbm2java
 */
public class Mov  implements java.io.Serializable {


     private BigDecimal movId;
     private Cal cal;
     private String movDes;
     private Double movLimInf;
     private Double movLimSup;
     private BigDecimal movOrdPre;
     private Double movPto;
     private Double movWoe;
     private String movDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public Mov() {
    }

	
    public Mov(BigDecimal movId) {
        this.movId = movId;
    }
    public Mov(BigDecimal movId, Cal cal, String movDes, Double movLimInf, Double movLimSup, BigDecimal movOrdPre, Double movPto, Double movWoe, String movDesLar, Set<CliGol> cliGols) {
       this.movId = movId;
       this.cal = cal;
       this.movDes = movDes;
       this.movLimInf = movLimInf;
       this.movLimSup = movLimSup;
       this.movOrdPre = movOrdPre;
       this.movPto = movPto;
       this.movWoe = movWoe;
       this.movDesLar = movDesLar;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getMovId() {
        return this.movId;
    }
    
    public void setMovId(BigDecimal movId) {
        this.movId = movId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getMovDes() {
        return this.movDes;
    }
    
    public void setMovDes(String movDes) {
        this.movDes = movDes;
    }
    public Double getMovLimInf() {
        return this.movLimInf;
    }
    
    public void setMovLimInf(Double movLimInf) {
        this.movLimInf = movLimInf;
    }
    public Double getMovLimSup() {
        return this.movLimSup;
    }
    
    public void setMovLimSup(Double movLimSup) {
        this.movLimSup = movLimSup;
    }
    public BigDecimal getMovOrdPre() {
        return this.movOrdPre;
    }
    
    public void setMovOrdPre(BigDecimal movOrdPre) {
        this.movOrdPre = movOrdPre;
    }
    public Double getMovPto() {
        return this.movPto;
    }
    
    public void setMovPto(Double movPto) {
        this.movPto = movPto;
    }
    public Double getMovWoe() {
        return this.movWoe;
    }
    
    public void setMovWoe(Double movWoe) {
        this.movWoe = movWoe;
    }
    public String getMovDesLar() {
        return this.movDesLar;
    }
    
    public void setMovDesLar(String movDesLar) {
        this.movDesLar = movDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


