package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * NivEstPap generated by hbm2java
 */
public class NivEstPap  implements java.io.Serializable {


     private BigDecimal nivEstPapId;
     private Cal cal;
     private String nivEstPapDes;
     private Double nivEstPapLimInf;
     private Double nivEstPapLimSup;
     private BigDecimal nivEstPapOrdPre;
     private Double nivEstPapPto;
     private Double nivEstPapWoe;
     private String nivEstPapDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public NivEstPap() {
    }

	
    public NivEstPap(BigDecimal nivEstPapId) {
        this.nivEstPapId = nivEstPapId;
    }
    public NivEstPap(BigDecimal nivEstPapId, Cal cal, String nivEstPapDes, Double nivEstPapLimInf, Double nivEstPapLimSup, BigDecimal nivEstPapOrdPre, Double nivEstPapPto, Double nivEstPapWoe, String nivEstPapDesLar, Set<CliGol> cliGols) {
       this.nivEstPapId = nivEstPapId;
       this.cal = cal;
       this.nivEstPapDes = nivEstPapDes;
       this.nivEstPapLimInf = nivEstPapLimInf;
       this.nivEstPapLimSup = nivEstPapLimSup;
       this.nivEstPapOrdPre = nivEstPapOrdPre;
       this.nivEstPapPto = nivEstPapPto;
       this.nivEstPapWoe = nivEstPapWoe;
       this.nivEstPapDesLar = nivEstPapDesLar;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getNivEstPapId() {
        return this.nivEstPapId;
    }
    
    public void setNivEstPapId(BigDecimal nivEstPapId) {
        this.nivEstPapId = nivEstPapId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getNivEstPapDes() {
        return this.nivEstPapDes;
    }
    
    public void setNivEstPapDes(String nivEstPapDes) {
        this.nivEstPapDes = nivEstPapDes;
    }
    public Double getNivEstPapLimInf() {
        return this.nivEstPapLimInf;
    }
    
    public void setNivEstPapLimInf(Double nivEstPapLimInf) {
        this.nivEstPapLimInf = nivEstPapLimInf;
    }
    public Double getNivEstPapLimSup() {
        return this.nivEstPapLimSup;
    }
    
    public void setNivEstPapLimSup(Double nivEstPapLimSup) {
        this.nivEstPapLimSup = nivEstPapLimSup;
    }
    public BigDecimal getNivEstPapOrdPre() {
        return this.nivEstPapOrdPre;
    }
    
    public void setNivEstPapOrdPre(BigDecimal nivEstPapOrdPre) {
        this.nivEstPapOrdPre = nivEstPapOrdPre;
    }
    public Double getNivEstPapPto() {
        return this.nivEstPapPto;
    }
    
    public void setNivEstPapPto(Double nivEstPapPto) {
        this.nivEstPapPto = nivEstPapPto;
    }
    public Double getNivEstPapWoe() {
        return this.nivEstPapWoe;
    }
    
    public void setNivEstPapWoe(Double nivEstPapWoe) {
        this.nivEstPapWoe = nivEstPapWoe;
    }
    public String getNivEstPapDesLar() {
        return this.nivEstPapDesLar;
    }
    
    public void setNivEstPapDesLar(String nivEstPapDesLar) {
        this.nivEstPapDesLar = nivEstPapDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


