package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * NivEst generated by hbm2java
 */
public class NivEst  implements java.io.Serializable {


     private BigDecimal nivEstId;
     private Cal cal;
     private String nivEstDes;
     private Double nivEstLimInf;
     private Double nivEstLimSup;
     private BigDecimal nivEstOrdPre;
     private Double nivEstPto;
     private Double nivEstWoe;
     private String nivEstDesLar;
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public NivEst() {
    }

	
    public NivEst(BigDecimal nivEstId) {
        this.nivEstId = nivEstId;
    }
    public NivEst(BigDecimal nivEstId, Cal cal, String nivEstDes, Double nivEstLimInf, Double nivEstLimSup, BigDecimal nivEstOrdPre, Double nivEstPto, Double nivEstWoe, String nivEstDesLar, Set<CliMta> cliMtas, Set<CliGol> cliGols) {
       this.nivEstId = nivEstId;
       this.cal = cal;
       this.nivEstDes = nivEstDes;
       this.nivEstLimInf = nivEstLimInf;
       this.nivEstLimSup = nivEstLimSup;
       this.nivEstOrdPre = nivEstOrdPre;
       this.nivEstPto = nivEstPto;
       this.nivEstWoe = nivEstWoe;
       this.nivEstDesLar = nivEstDesLar;
       this.cliMtas = cliMtas;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getNivEstId() {
        return this.nivEstId;
    }
    
    public void setNivEstId(BigDecimal nivEstId) {
        this.nivEstId = nivEstId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getNivEstDes() {
        return this.nivEstDes;
    }
    
    public void setNivEstDes(String nivEstDes) {
        this.nivEstDes = nivEstDes;
    }
    public Double getNivEstLimInf() {
        return this.nivEstLimInf;
    }
    
    public void setNivEstLimInf(Double nivEstLimInf) {
        this.nivEstLimInf = nivEstLimInf;
    }
    public Double getNivEstLimSup() {
        return this.nivEstLimSup;
    }
    
    public void setNivEstLimSup(Double nivEstLimSup) {
        this.nivEstLimSup = nivEstLimSup;
    }
    public BigDecimal getNivEstOrdPre() {
        return this.nivEstOrdPre;
    }
    
    public void setNivEstOrdPre(BigDecimal nivEstOrdPre) {
        this.nivEstOrdPre = nivEstOrdPre;
    }
    public Double getNivEstPto() {
        return this.nivEstPto;
    }
    
    public void setNivEstPto(Double nivEstPto) {
        this.nivEstPto = nivEstPto;
    }
    public Double getNivEstWoe() {
        return this.nivEstWoe;
    }
    
    public void setNivEstWoe(Double nivEstWoe) {
        this.nivEstWoe = nivEstWoe;
    }
    public String getNivEstDesLar() {
        return this.nivEstDesLar;
    }
    
    public void setNivEstDesLar(String nivEstDesLar) {
        this.nivEstDesLar = nivEstDesLar;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


