package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * NumCre generated by hbm2java
 */
public class NumCre  implements java.io.Serializable {


     private BigDecimal numCreId;
     private Cal cal;
     private String numCreDes;
     private Double numCreLimInf;
     private Double numCreLimSup;
     private BigDecimal numCreOrdPre;
     private Double numCrePto;
     private Double numCreWoe;
     private String numCreDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public NumCre() {
    }

	
    public NumCre(BigDecimal numCreId) {
        this.numCreId = numCreId;
    }
    public NumCre(BigDecimal numCreId, Cal cal, String numCreDes, Double numCreLimInf, Double numCreLimSup, BigDecimal numCreOrdPre, Double numCrePto, Double numCreWoe, String numCreDesLar, Set<CliGol> cliGols) {
       this.numCreId = numCreId;
       this.cal = cal;
       this.numCreDes = numCreDes;
       this.numCreLimInf = numCreLimInf;
       this.numCreLimSup = numCreLimSup;
       this.numCreOrdPre = numCreOrdPre;
       this.numCrePto = numCrePto;
       this.numCreWoe = numCreWoe;
       this.numCreDesLar = numCreDesLar;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getNumCreId() {
        return this.numCreId;
    }
    
    public void setNumCreId(BigDecimal numCreId) {
        this.numCreId = numCreId;
    }
    public Cal getCal() {
        return this.cal;
    }
    
    public void setCal(Cal cal) {
        this.cal = cal;
    }
    public String getNumCreDes() {
        return this.numCreDes;
    }
    
    public void setNumCreDes(String numCreDes) {
        this.numCreDes = numCreDes;
    }
    public Double getNumCreLimInf() {
        return this.numCreLimInf;
    }
    
    public void setNumCreLimInf(Double numCreLimInf) {
        this.numCreLimInf = numCreLimInf;
    }
    public Double getNumCreLimSup() {
        return this.numCreLimSup;
    }
    
    public void setNumCreLimSup(Double numCreLimSup) {
        this.numCreLimSup = numCreLimSup;
    }
    public BigDecimal getNumCreOrdPre() {
        return this.numCreOrdPre;
    }
    
    public void setNumCreOrdPre(BigDecimal numCreOrdPre) {
        this.numCreOrdPre = numCreOrdPre;
    }
    public Double getNumCrePto() {
        return this.numCrePto;
    }
    
    public void setNumCrePto(Double numCrePto) {
        this.numCrePto = numCrePto;
    }
    public Double getNumCreWoe() {
        return this.numCreWoe;
    }
    
    public void setNumCreWoe(Double numCreWoe) {
        this.numCreWoe = numCreWoe;
    }
    public String getNumCreDesLar() {
        return this.numCreDesLar;
    }
    
    public void setNumCreDesLar(String numCreDesLar) {
        this.numCreDesLar = numCreDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


