package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PagRnt generated by hbm2java
 */
public class PagRnt  implements java.io.Serializable {


     private BigDecimal pagRntId;
     private BigDecimal calId;
     private String pagRntDes;
     private Double pagRntLimInf;
     private Double pagRntLimSup;
     private BigDecimal pagRntOrdPre;
     private Double pagRntPto;
     private Double pagRntWoe;
     private String pagRntDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public PagRnt() {
    }

	
    public PagRnt(BigDecimal pagRntId) {
        this.pagRntId = pagRntId;
    }
    public PagRnt(BigDecimal pagRntId, BigDecimal calId, String pagRntDes, Double pagRntLimInf, Double pagRntLimSup, BigDecimal pagRntOrdPre, Double pagRntPto, Double pagRntWoe, String pagRntDesLar, Set<CliGol> cliGols) {
       this.pagRntId = pagRntId;
       this.calId = calId;
       this.pagRntDes = pagRntDes;
       this.pagRntLimInf = pagRntLimInf;
       this.pagRntLimSup = pagRntLimSup;
       this.pagRntOrdPre = pagRntOrdPre;
       this.pagRntPto = pagRntPto;
       this.pagRntWoe = pagRntWoe;
       this.pagRntDesLar = pagRntDesLar;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getPagRntId() {
        return this.pagRntId;
    }
    
    public void setPagRntId(BigDecimal pagRntId) {
        this.pagRntId = pagRntId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getPagRntDes() {
        return this.pagRntDes;
    }
    
    public void setPagRntDes(String pagRntDes) {
        this.pagRntDes = pagRntDes;
    }
    public Double getPagRntLimInf() {
        return this.pagRntLimInf;
    }
    
    public void setPagRntLimInf(Double pagRntLimInf) {
        this.pagRntLimInf = pagRntLimInf;
    }
    public Double getPagRntLimSup() {
        return this.pagRntLimSup;
    }
    
    public void setPagRntLimSup(Double pagRntLimSup) {
        this.pagRntLimSup = pagRntLimSup;
    }
    public BigDecimal getPagRntOrdPre() {
        return this.pagRntOrdPre;
    }
    
    public void setPagRntOrdPre(BigDecimal pagRntOrdPre) {
        this.pagRntOrdPre = pagRntOrdPre;
    }
    public Double getPagRntPto() {
        return this.pagRntPto;
    }
    
    public void setPagRntPto(Double pagRntPto) {
        this.pagRntPto = pagRntPto;
    }
    public Double getPagRntWoe() {
        return this.pagRntWoe;
    }
    
    public void setPagRntWoe(Double pagRntWoe) {
        this.pagRntWoe = pagRntWoe;
    }
    public String getPagRntDesLar() {
        return this.pagRntDesLar;
    }
    
    public void setPagRntDesLar(String pagRntDesLar) {
        this.pagRntDesLar = pagRntDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


