package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ParPlt generated by hbm2java
 */
public class ParPlt  implements java.io.Serializable {


     private BigDecimal parPltId;
     private BigDecimal calId;
     private String parPltDes;
     private Double parPltLimInf;
     private Double parPltLimSup;
     private BigDecimal parPltOrdPre;
     private Double parPltPto;
     private Double parPltWoe;
     private String parPltDesLar;
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);

    public ParPlt() {
    }

	
    public ParPlt(BigDecimal parPltId) {
        this.parPltId = parPltId;
    }
    public ParPlt(BigDecimal parPltId, BigDecimal calId, String parPltDes, Double parPltLimInf, Double parPltLimSup, BigDecimal parPltOrdPre, Double parPltPto, Double parPltWoe, String parPltDesLar, Set<CliMta> cliMtas) {
       this.parPltId = parPltId;
       this.calId = calId;
       this.parPltDes = parPltDes;
       this.parPltLimInf = parPltLimInf;
       this.parPltLimSup = parPltLimSup;
       this.parPltOrdPre = parPltOrdPre;
       this.parPltPto = parPltPto;
       this.parPltWoe = parPltWoe;
       this.parPltDesLar = parPltDesLar;
       this.cliMtas = cliMtas;
    }
   
    public BigDecimal getParPltId() {
        return this.parPltId;
    }
    
    public void setParPltId(BigDecimal parPltId) {
        this.parPltId = parPltId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getParPltDes() {
        return this.parPltDes;
    }
    
    public void setParPltDes(String parPltDes) {
        this.parPltDes = parPltDes;
    }
    public Double getParPltLimInf() {
        return this.parPltLimInf;
    }
    
    public void setParPltLimInf(Double parPltLimInf) {
        this.parPltLimInf = parPltLimInf;
    }
    public Double getParPltLimSup() {
        return this.parPltLimSup;
    }
    
    public void setParPltLimSup(Double parPltLimSup) {
        this.parPltLimSup = parPltLimSup;
    }
    public BigDecimal getParPltOrdPre() {
        return this.parPltOrdPre;
    }
    
    public void setParPltOrdPre(BigDecimal parPltOrdPre) {
        this.parPltOrdPre = parPltOrdPre;
    }
    public Double getParPltPto() {
        return this.parPltPto;
    }
    
    public void setParPltPto(Double parPltPto) {
        this.parPltPto = parPltPto;
    }
    public Double getParPltWoe() {
        return this.parPltWoe;
    }
    
    public void setParPltWoe(Double parPltWoe) {
        this.parPltWoe = parPltWoe;
    }
    public String getParPltDesLar() {
        return this.parPltDesLar;
    }
    
    public void setParPltDesLar(String parPltDesLar) {
        this.parPltDesLar = parPltDesLar;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }




}


