package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ProAnoGto generated by hbm2java
 */
public class ProAnoGto  implements java.io.Serializable {


     private BigDecimal proAnoGtoId;
     private BigDecimal calId;
     private String proAnoGtoDes;
     private Double proAnoGtoLimInf;
     private Double proAnoGtoLimSup;
     private BigDecimal proAnoGtoOrdPre;
     private Double proAnoGtoPto;
     private Double proAnoGtoWoe;
     private String proAnoGtoDesLar;
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public ProAnoGto() {
    }

	
    public ProAnoGto(BigDecimal proAnoGtoId) {
        this.proAnoGtoId = proAnoGtoId;
    }
    public ProAnoGto(BigDecimal proAnoGtoId, BigDecimal calId, String proAnoGtoDes, Double proAnoGtoLimInf, Double proAnoGtoLimSup, BigDecimal proAnoGtoOrdPre, Double proAnoGtoPto, Double proAnoGtoWoe, String proAnoGtoDesLar, Set<CliMta> cliMtas, Set<CliGol> cliGols) {
       this.proAnoGtoId = proAnoGtoId;
       this.calId = calId;
       this.proAnoGtoDes = proAnoGtoDes;
       this.proAnoGtoLimInf = proAnoGtoLimInf;
       this.proAnoGtoLimSup = proAnoGtoLimSup;
       this.proAnoGtoOrdPre = proAnoGtoOrdPre;
       this.proAnoGtoPto = proAnoGtoPto;
       this.proAnoGtoWoe = proAnoGtoWoe;
       this.proAnoGtoDesLar = proAnoGtoDesLar;
       this.cliMtas = cliMtas;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getProAnoGtoId() {
        return this.proAnoGtoId;
    }
    
    public void setProAnoGtoId(BigDecimal proAnoGtoId) {
        this.proAnoGtoId = proAnoGtoId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getProAnoGtoDes() {
        return this.proAnoGtoDes;
    }
    
    public void setProAnoGtoDes(String proAnoGtoDes) {
        this.proAnoGtoDes = proAnoGtoDes;
    }
    public Double getProAnoGtoLimInf() {
        return this.proAnoGtoLimInf;
    }
    
    public void setProAnoGtoLimInf(Double proAnoGtoLimInf) {
        this.proAnoGtoLimInf = proAnoGtoLimInf;
    }
    public Double getProAnoGtoLimSup() {
        return this.proAnoGtoLimSup;
    }
    
    public void setProAnoGtoLimSup(Double proAnoGtoLimSup) {
        this.proAnoGtoLimSup = proAnoGtoLimSup;
    }
    public BigDecimal getProAnoGtoOrdPre() {
        return this.proAnoGtoOrdPre;
    }
    
    public void setProAnoGtoOrdPre(BigDecimal proAnoGtoOrdPre) {
        this.proAnoGtoOrdPre = proAnoGtoOrdPre;
    }
    public Double getProAnoGtoPto() {
        return this.proAnoGtoPto;
    }
    
    public void setProAnoGtoPto(Double proAnoGtoPto) {
        this.proAnoGtoPto = proAnoGtoPto;
    }
    public Double getProAnoGtoWoe() {
        return this.proAnoGtoWoe;
    }
    
    public void setProAnoGtoWoe(Double proAnoGtoWoe) {
        this.proAnoGtoWoe = proAnoGtoWoe;
    }
    public String getProAnoGtoDesLar() {
        return this.proAnoGtoDesLar;
    }
    
    public void setProAnoGtoDesLar(String proAnoGtoDesLar) {
        this.proAnoGtoDesLar = proAnoGtoDesLar;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


