package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Ptm generated by hbm2java
 */
public class Ptm  implements java.io.Serializable {


     private BigDecimal ptmId;
     private BigDecimal calId;
     private String ptmDes;
     private Double ptmLimInf;
     private Double ptmLimSup;
     private BigDecimal ptmOrdPre;
     private Double ptmPto;
     private Double ptmWoe;
     private String ptmDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);

    public Ptm() {
    }

	
    public Ptm(BigDecimal ptmId) {
        this.ptmId = ptmId;
    }
    public Ptm(BigDecimal ptmId, BigDecimal calId, String ptmDes, Double ptmLimInf, Double ptmLimSup, BigDecimal ptmOrdPre, Double ptmPto, Double ptmWoe, String ptmDesLar, Set<CliGol> cliGols, Set<CliMta> cliMtas) {
       this.ptmId = ptmId;
       this.calId = calId;
       this.ptmDes = ptmDes;
       this.ptmLimInf = ptmLimInf;
       this.ptmLimSup = ptmLimSup;
       this.ptmOrdPre = ptmOrdPre;
       this.ptmPto = ptmPto;
       this.ptmWoe = ptmWoe;
       this.ptmDesLar = ptmDesLar;
       this.cliGols = cliGols;
       this.cliMtas = cliMtas;
    }
   
    public BigDecimal getPtmId() {
        return this.ptmId;
    }
    
    public void setPtmId(BigDecimal ptmId) {
        this.ptmId = ptmId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getPtmDes() {
        return this.ptmDes;
    }
    
    public void setPtmDes(String ptmDes) {
        this.ptmDes = ptmDes;
    }
    public Double getPtmLimInf() {
        return this.ptmLimInf;
    }
    
    public void setPtmLimInf(Double ptmLimInf) {
        this.ptmLimInf = ptmLimInf;
    }
    public Double getPtmLimSup() {
        return this.ptmLimSup;
    }
    
    public void setPtmLimSup(Double ptmLimSup) {
        this.ptmLimSup = ptmLimSup;
    }
    public BigDecimal getPtmOrdPre() {
        return this.ptmOrdPre;
    }
    
    public void setPtmOrdPre(BigDecimal ptmOrdPre) {
        this.ptmOrdPre = ptmOrdPre;
    }
    public Double getPtmPto() {
        return this.ptmPto;
    }
    
    public void setPtmPto(Double ptmPto) {
        this.ptmPto = ptmPto;
    }
    public Double getPtmWoe() {
        return this.ptmWoe;
    }
    
    public void setPtmWoe(Double ptmWoe) {
        this.ptmWoe = ptmWoe;
    }
    public String getPtmDesLar() {
        return this.ptmDesLar;
    }
    
    public void setPtmDesLar(String ptmDesLar) {
        this.ptmDesLar = ptmDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }




}


