package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * RelAfe generated by hbm2java
 */
public class RelAfe  implements java.io.Serializable {


     private BigDecimal relAfeId;
     private BigDecimal calId;
     private String relAfeDes;
     private Double relAfeLimInf;
     private Double relAfeLimSup;
     private BigDecimal relAfeOrdPre;
     private Double relAfePto;
     private Double relAfeWoe;
     private String relAfeDesLar;

    public RelAfe() {
    }

	
    public RelAfe(BigDecimal relAfeId) {
        this.relAfeId = relAfeId;
    }
    public RelAfe(BigDecimal relAfeId, BigDecimal calId, String relAfeDes, Double relAfeLimInf, Double relAfeLimSup, BigDecimal relAfeOrdPre, Double relAfePto, Double relAfeWoe, String relAfeDesLar) {
       this.relAfeId = relAfeId;
       this.calId = calId;
       this.relAfeDes = relAfeDes;
       this.relAfeLimInf = relAfeLimInf;
       this.relAfeLimSup = relAfeLimSup;
       this.relAfeOrdPre = relAfeOrdPre;
       this.relAfePto = relAfePto;
       this.relAfeWoe = relAfeWoe;
       this.relAfeDesLar = relAfeDesLar;
    }
   
    public BigDecimal getRelAfeId() {
        return this.relAfeId;
    }
    
    public void setRelAfeId(BigDecimal relAfeId) {
        this.relAfeId = relAfeId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getRelAfeDes() {
        return this.relAfeDes;
    }
    
    public void setRelAfeDes(String relAfeDes) {
        this.relAfeDes = relAfeDes;
    }
    public Double getRelAfeLimInf() {
        return this.relAfeLimInf;
    }
    
    public void setRelAfeLimInf(Double relAfeLimInf) {
        this.relAfeLimInf = relAfeLimInf;
    }
    public Double getRelAfeLimSup() {
        return this.relAfeLimSup;
    }
    
    public void setRelAfeLimSup(Double relAfeLimSup) {
        this.relAfeLimSup = relAfeLimSup;
    }
    public BigDecimal getRelAfeOrdPre() {
        return this.relAfeOrdPre;
    }
    
    public void setRelAfeOrdPre(BigDecimal relAfeOrdPre) {
        this.relAfeOrdPre = relAfeOrdPre;
    }
    public Double getRelAfePto() {
        return this.relAfePto;
    }
    
    public void setRelAfePto(Double relAfePto) {
        this.relAfePto = relAfePto;
    }
    public Double getRelAfeWoe() {
        return this.relAfeWoe;
    }
    
    public void setRelAfeWoe(Double relAfeWoe) {
        this.relAfeWoe = relAfeWoe;
    }
    public String getRelAfeDesLar() {
        return this.relAfeDesLar;
    }
    
    public void setRelAfeDesLar(String relAfeDesLar) {
        this.relAfeDesLar = relAfeDesLar;
    }




}


