package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Rld generated by hbm2java
 */
public class Rld  implements java.io.Serializable {


     private BigDecimal rldId;
     private BigDecimal calId;
     private String rldDes;
     private Double rldLimInf;
     private Double rldLimSup;
     private BigDecimal rldOrdPre;
     private Double rldPto;
     private Double rldWoe;
     private String rldDesLar;
     private Set<CliMta> cliMtas = new HashSet<CliMta>(0);

    public Rld() {
    }

	
    public Rld(BigDecimal rldId) {
        this.rldId = rldId;
    }
    public Rld(BigDecimal rldId, BigDecimal calId, String rldDes, Double rldLimInf, Double rldLimSup, BigDecimal rldOrdPre, Double rldPto, Double rldWoe, String rldDesLar, Set<CliMta> cliMtas) {
       this.rldId = rldId;
       this.calId = calId;
       this.rldDes = rldDes;
       this.rldLimInf = rldLimInf;
       this.rldLimSup = rldLimSup;
       this.rldOrdPre = rldOrdPre;
       this.rldPto = rldPto;
       this.rldWoe = rldWoe;
       this.rldDesLar = rldDesLar;
       this.cliMtas = cliMtas;
    }
   
    public BigDecimal getRldId() {
        return this.rldId;
    }
    
    public void setRldId(BigDecimal rldId) {
        this.rldId = rldId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getRldDes() {
        return this.rldDes;
    }
    
    public void setRldDes(String rldDes) {
        this.rldDes = rldDes;
    }
    public Double getRldLimInf() {
        return this.rldLimInf;
    }
    
    public void setRldLimInf(Double rldLimInf) {
        this.rldLimInf = rldLimInf;
    }
    public Double getRldLimSup() {
        return this.rldLimSup;
    }
    
    public void setRldLimSup(Double rldLimSup) {
        this.rldLimSup = rldLimSup;
    }
    public BigDecimal getRldOrdPre() {
        return this.rldOrdPre;
    }
    
    public void setRldOrdPre(BigDecimal rldOrdPre) {
        this.rldOrdPre = rldOrdPre;
    }
    public Double getRldPto() {
        return this.rldPto;
    }
    
    public void setRldPto(Double rldPto) {
        this.rldPto = rldPto;
    }
    public Double getRldWoe() {
        return this.rldWoe;
    }
    
    public void setRldWoe(Double rldWoe) {
        this.rldWoe = rldWoe;
    }
    public String getRldDesLar() {
        return this.rldDesLar;
    }
    
    public void setRldDesLar(String rldDesLar) {
        this.rldDesLar = rldDesLar;
    }
    public Set<CliMta> getCliMtas() {
        return this.cliMtas;
    }
    
    public void setCliMtas(Set<CliMta> cliMtas) {
        this.cliMtas = cliMtas;
    }




}


