package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * RngAntOcp generated by hbm2java
 */
public class RngAntOcp  implements java.io.Serializable {


     private BigDecimal rngAntOcpId;
     private BigDecimal calId;
     private String rngAntOcpDes;
     private Double rngAntOcpLimInf;
     private Double rngAntOcpLimSup;
     private BigDecimal rngAntOcpOrdPre;
     private Double rngAntOcpPto;
     private Double rngAntOcpWoe;
     private String rngAntOcpDesLar;

    public RngAntOcp() {
    }

	
    public RngAntOcp(BigDecimal rngAntOcpId) {
        this.rngAntOcpId = rngAntOcpId;
    }
    public RngAntOcp(BigDecimal rngAntOcpId, BigDecimal calId, String rngAntOcpDes, Double rngAntOcpLimInf, Double rngAntOcpLimSup, BigDecimal rngAntOcpOrdPre, Double rngAntOcpPto, Double rngAntOcpWoe, String rngAntOcpDesLar) {
       this.rngAntOcpId = rngAntOcpId;
       this.calId = calId;
       this.rngAntOcpDes = rngAntOcpDes;
       this.rngAntOcpLimInf = rngAntOcpLimInf;
       this.rngAntOcpLimSup = rngAntOcpLimSup;
       this.rngAntOcpOrdPre = rngAntOcpOrdPre;
       this.rngAntOcpPto = rngAntOcpPto;
       this.rngAntOcpWoe = rngAntOcpWoe;
       this.rngAntOcpDesLar = rngAntOcpDesLar;
    }
   
    public BigDecimal getRngAntOcpId() {
        return this.rngAntOcpId;
    }
    
    public void setRngAntOcpId(BigDecimal rngAntOcpId) {
        this.rngAntOcpId = rngAntOcpId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getRngAntOcpDes() {
        return this.rngAntOcpDes;
    }
    
    public void setRngAntOcpDes(String rngAntOcpDes) {
        this.rngAntOcpDes = rngAntOcpDes;
    }
    public Double getRngAntOcpLimInf() {
        return this.rngAntOcpLimInf;
    }
    
    public void setRngAntOcpLimInf(Double rngAntOcpLimInf) {
        this.rngAntOcpLimInf = rngAntOcpLimInf;
    }
    public Double getRngAntOcpLimSup() {
        return this.rngAntOcpLimSup;
    }
    
    public void setRngAntOcpLimSup(Double rngAntOcpLimSup) {
        this.rngAntOcpLimSup = rngAntOcpLimSup;
    }
    public BigDecimal getRngAntOcpOrdPre() {
        return this.rngAntOcpOrdPre;
    }
    
    public void setRngAntOcpOrdPre(BigDecimal rngAntOcpOrdPre) {
        this.rngAntOcpOrdPre = rngAntOcpOrdPre;
    }
    public Double getRngAntOcpPto() {
        return this.rngAntOcpPto;
    }
    
    public void setRngAntOcpPto(Double rngAntOcpPto) {
        this.rngAntOcpPto = rngAntOcpPto;
    }
    public Double getRngAntOcpWoe() {
        return this.rngAntOcpWoe;
    }
    
    public void setRngAntOcpWoe(Double rngAntOcpWoe) {
        this.rngAntOcpWoe = rngAntOcpWoe;
    }
    public String getRngAntOcpDesLar() {
        return this.rngAntOcpDesLar;
    }
    
    public void setRngAntOcpDesLar(String rngAntOcpDesLar) {
        this.rngAntOcpDesLar = rngAntOcpDesLar;
    }




}


