package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * RngResAct generated by hbm2java
 */
public class RngResAct  implements java.io.Serializable {


     private BigDecimal rngResActId;
     private BigDecimal calId;
     private String rngResActDes;
     private Double rngResActLimInf;
     private Double rngResActLimSup;
     private BigDecimal rngResActOrdPre;
     private Double rngResActPto;
     private Double rngResActWoe;
     private String rngResActDesLar;

    public RngResAct() {
    }

	
    public RngResAct(BigDecimal rngResActId) {
        this.rngResActId = rngResActId;
    }
    public RngResAct(BigDecimal rngResActId, BigDecimal calId, String rngResActDes, Double rngResActLimInf, Double rngResActLimSup, BigDecimal rngResActOrdPre, Double rngResActPto, Double rngResActWoe, String rngResActDesLar) {
       this.rngResActId = rngResActId;
       this.calId = calId;
       this.rngResActDes = rngResActDes;
       this.rngResActLimInf = rngResActLimInf;
       this.rngResActLimSup = rngResActLimSup;
       this.rngResActOrdPre = rngResActOrdPre;
       this.rngResActPto = rngResActPto;
       this.rngResActWoe = rngResActWoe;
       this.rngResActDesLar = rngResActDesLar;
    }
   
    public BigDecimal getRngResActId() {
        return this.rngResActId;
    }
    
    public void setRngResActId(BigDecimal rngResActId) {
        this.rngResActId = rngResActId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getRngResActDes() {
        return this.rngResActDes;
    }
    
    public void setRngResActDes(String rngResActDes) {
        this.rngResActDes = rngResActDes;
    }
    public Double getRngResActLimInf() {
        return this.rngResActLimInf;
    }
    
    public void setRngResActLimInf(Double rngResActLimInf) {
        this.rngResActLimInf = rngResActLimInf;
    }
    public Double getRngResActLimSup() {
        return this.rngResActLimSup;
    }
    
    public void setRngResActLimSup(Double rngResActLimSup) {
        this.rngResActLimSup = rngResActLimSup;
    }
    public BigDecimal getRngResActOrdPre() {
        return this.rngResActOrdPre;
    }
    
    public void setRngResActOrdPre(BigDecimal rngResActOrdPre) {
        this.rngResActOrdPre = rngResActOrdPre;
    }
    public Double getRngResActPto() {
        return this.rngResActPto;
    }
    
    public void setRngResActPto(Double rngResActPto) {
        this.rngResActPto = rngResActPto;
    }
    public Double getRngResActWoe() {
        return this.rngResActWoe;
    }
    
    public void setRngResActWoe(Double rngResActWoe) {
        this.rngResActWoe = rngResActWoe;
    }
    public String getRngResActDesLar() {
        return this.rngResActDesLar;
    }
    
    public void setRngResActDesLar(String rngResActDesLar) {
        this.rngResActDesLar = rngResActDesLar;
    }




}


