package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * SegVda generated by hbm2java
 */
public class SegVda  implements java.io.Serializable {


     private BigDecimal segVdaId;
     private BigDecimal calId;
     private String segVdaDes;
     private Double segVdaLimInf;
     private Double segVdaLimSup;
     private BigDecimal segVdaOrdPre;
     private Double segVdaPto;
     private Double segVdaWoe;
     private String segVdaDesLar;

    public SegVda() {
    }

	
    public SegVda(BigDecimal segVdaId) {
        this.segVdaId = segVdaId;
    }
    public SegVda(BigDecimal segVdaId, BigDecimal calId, String segVdaDes, Double segVdaLimInf, Double segVdaLimSup, BigDecimal segVdaOrdPre, Double segVdaPto, Double segVdaWoe, String segVdaDesLar) {
       this.segVdaId = segVdaId;
       this.calId = calId;
       this.segVdaDes = segVdaDes;
       this.segVdaLimInf = segVdaLimInf;
       this.segVdaLimSup = segVdaLimSup;
       this.segVdaOrdPre = segVdaOrdPre;
       this.segVdaPto = segVdaPto;
       this.segVdaWoe = segVdaWoe;
       this.segVdaDesLar = segVdaDesLar;
    }
   
    public BigDecimal getSegVdaId() {
        return this.segVdaId;
    }
    
    public void setSegVdaId(BigDecimal segVdaId) {
        this.segVdaId = segVdaId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getSegVdaDes() {
        return this.segVdaDes;
    }
    
    public void setSegVdaDes(String segVdaDes) {
        this.segVdaDes = segVdaDes;
    }
    public Double getSegVdaLimInf() {
        return this.segVdaLimInf;
    }
    
    public void setSegVdaLimInf(Double segVdaLimInf) {
        this.segVdaLimInf = segVdaLimInf;
    }
    public Double getSegVdaLimSup() {
        return this.segVdaLimSup;
    }
    
    public void setSegVdaLimSup(Double segVdaLimSup) {
        this.segVdaLimSup = segVdaLimSup;
    }
    public BigDecimal getSegVdaOrdPre() {
        return this.segVdaOrdPre;
    }
    
    public void setSegVdaOrdPre(BigDecimal segVdaOrdPre) {
        this.segVdaOrdPre = segVdaOrdPre;
    }
    public Double getSegVdaPto() {
        return this.segVdaPto;
    }
    
    public void setSegVdaPto(Double segVdaPto) {
        this.segVdaPto = segVdaPto;
    }
    public Double getSegVdaWoe() {
        return this.segVdaWoe;
    }
    
    public void setSegVdaWoe(Double segVdaWoe) {
        this.segVdaWoe = segVdaWoe;
    }
    public String getSegVdaDesLar() {
        return this.segVdaDesLar;
    }
    
    public void setSegVdaDesLar(String segVdaDesLar) {
        this.segVdaDesLar = segVdaDesLar;
    }




}


