package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SitAct generated by hbm2java
 */
public class SitAct  implements java.io.Serializable {


     private BigDecimal sitActId;
     private BigDecimal calId;
     private String sitActDes;
     private Double sitActLimInf;
     private Double sitActLimSup;
     private BigDecimal sitActOrdPre;
     private Double sitActPto;
     private Double sitActWoe;
     private String sitActDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public SitAct() {
    }

	
    public SitAct(BigDecimal sitActId) {
        this.sitActId = sitActId;
    }
    public SitAct(BigDecimal sitActId, BigDecimal calId, String sitActDes, Double sitActLimInf, Double sitActLimSup, BigDecimal sitActOrdPre, Double sitActPto, Double sitActWoe, String sitActDesLar, Set<CliGol> cliGols) {
       this.sitActId = sitActId;
       this.calId = calId;
       this.sitActDes = sitActDes;
       this.sitActLimInf = sitActLimInf;
       this.sitActLimSup = sitActLimSup;
       this.sitActOrdPre = sitActOrdPre;
       this.sitActPto = sitActPto;
       this.sitActWoe = sitActWoe;
       this.sitActDesLar = sitActDesLar;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getSitActId() {
        return this.sitActId;
    }
    
    public void setSitActId(BigDecimal sitActId) {
        this.sitActId = sitActId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getSitActDes() {
        return this.sitActDes;
    }
    
    public void setSitActDes(String sitActDes) {
        this.sitActDes = sitActDes;
    }
    public Double getSitActLimInf() {
        return this.sitActLimInf;
    }
    
    public void setSitActLimInf(Double sitActLimInf) {
        this.sitActLimInf = sitActLimInf;
    }
    public Double getSitActLimSup() {
        return this.sitActLimSup;
    }
    
    public void setSitActLimSup(Double sitActLimSup) {
        this.sitActLimSup = sitActLimSup;
    }
    public BigDecimal getSitActOrdPre() {
        return this.sitActOrdPre;
    }
    
    public void setSitActOrdPre(BigDecimal sitActOrdPre) {
        this.sitActOrdPre = sitActOrdPre;
    }
    public Double getSitActPto() {
        return this.sitActPto;
    }
    
    public void setSitActPto(Double sitActPto) {
        this.sitActPto = sitActPto;
    }
    public Double getSitActWoe() {
        return this.sitActWoe;
    }
    
    public void setSitActWoe(Double sitActWoe) {
        this.sitActWoe = sitActWoe;
    }
    public String getSitActDesLar() {
        return this.sitActDesLar;
    }
    
    public void setSitActDesLar(String sitActDesLar) {
        this.sitActDesLar = sitActDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


