package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Srv generated by hbm2java
 */
public class Srv  implements java.io.Serializable {


     private BigDecimal srvId;
     private BigDecimal calId;
     private String srvDes;
     private Double srvLimInf;
     private Double srvLimSup;
     private BigDecimal srvOrdPre;
     private Double srvPto;
     private Double srvWoe;
     private String srvDesLar;
     private int tipEmpId;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public Srv() {
    }

	
    public Srv(BigDecimal srvId) {
        this.srvId = srvId;
    }
    public Srv(BigDecimal srvId, BigDecimal calId, String srvDes, Double srvLimInf, Double srvLimSup, BigDecimal srvOrdPre, Double srvPto, Double srvWoe, String srvDesLar, int tipEmpId,  Set<CliGol> cliGols) {
       this.srvId = srvId;
       this.calId = calId;
       this.srvDes = srvDes;
       this.srvLimInf = srvLimInf;
       this.srvLimSup = srvLimSup;
       this.srvOrdPre = srvOrdPre;
       this.srvPto = srvPto;
       this.srvWoe = srvWoe;
       this.srvDesLar = srvDesLar;
       this.tipEmpId = tipEmpId;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getSrvId() {
        return this.srvId;
    }
    
    public void setSrvId(BigDecimal srvId) {
        this.srvId = srvId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getSrvDes() {
        return this.srvDes;
    }
    
    public void setSrvDes(String srvDes) {
        this.srvDes = srvDes;
    }
    public Double getSrvLimInf() {
        return this.srvLimInf;
    }
    
    public void setSrvLimInf(Double srvLimInf) {
        this.srvLimInf = srvLimInf;
    }
    public Double getSrvLimSup() {
        return this.srvLimSup;
    }
    
    public void setSrvLimSup(Double srvLimSup) {
        this.srvLimSup = srvLimSup;
    }
    public BigDecimal getSrvOrdPre() {
        return this.srvOrdPre;
    }
    
    public void setSrvOrdPre(BigDecimal srvOrdPre) {
        this.srvOrdPre = srvOrdPre;
    }
    public Double getSrvPto() {
        return this.srvPto;
    }
    
    public void setSrvPto(Double srvPto) {
        this.srvPto = srvPto;
    }
    public Double getSrvWoe() {
        return this.srvWoe;
    }
    
    public void setSrvWoe(Double srvWoe) {
        this.srvWoe = srvWoe;
    }
    public String getSrvDesLar() {
        return this.srvDesLar;
    }
    
    public void setSrvDesLar(String srvDesLar) {
        this.srvDesLar = srvDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }

    public int getTipEmpId() {
        return tipEmpId;
    }

    public void setTipEmpId(int tipEmpId) {
        this.tipEmpId = tipEmpId;
    }




}


