package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * StaMta generated by hbm2java
 */
public class StaMta  implements java.io.Serializable {


     private BigDecimal staMtaId;
     private String staMtaDes;

    public StaMta() {
    }

	
    public StaMta(BigDecimal staMtaId) {
        this.staMtaId = staMtaId;
    }
    public StaMta(BigDecimal staMtaId, String staMtaDes) {
       this.staMtaId = staMtaId;
       this.staMtaDes = staMtaDes;
    }
   
    public BigDecimal getStaMtaId() {
        return this.staMtaId;
    }
    
    public void setStaMtaId(BigDecimal staMtaId) {
        this.staMtaId = staMtaId;
    }
    public String getStaMtaDes() {
        return this.staMtaDes;
    }
    
    public void setStaMtaDes(String staMtaDes) {
        this.staMtaDes = staMtaDes;
    }




}


