package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * TarCre generated by hbm2java
 */
public class TarCre  implements java.io.Serializable {


     private BigDecimal tarCreId;
     private BigDecimal calId;
     private String tarCreDes;
     private Double tarCreLimInf;
     private Double tarCreLimSup;
     private BigDecimal tarCreOrdPre;
     private Double tarCrePto;
     private Double tarCreWoe;
     private String tarCreDesLar;

    public TarCre() {
    }

	
    public TarCre(BigDecimal tarCreId) {
        this.tarCreId = tarCreId;
    }
    public TarCre(BigDecimal tarCreId, BigDecimal calId, String tarCreDes, Double tarCreLimInf, Double tarCreLimSup, BigDecimal tarCreOrdPre, Double tarCrePto, Double tarCreWoe, String tarCreDesLar) {
       this.tarCreId = tarCreId;
       this.calId = calId;
       this.tarCreDes = tarCreDes;
       this.tarCreLimInf = tarCreLimInf;
       this.tarCreLimSup = tarCreLimSup;
       this.tarCreOrdPre = tarCreOrdPre;
       this.tarCrePto = tarCrePto;
       this.tarCreWoe = tarCreWoe;
       this.tarCreDesLar = tarCreDesLar;
    }
   
    public BigDecimal getTarCreId() {
        return this.tarCreId;
    }
    
    public void setTarCreId(BigDecimal tarCreId) {
        this.tarCreId = tarCreId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getTarCreDes() {
        return this.tarCreDes;
    }
    
    public void setTarCreDes(String tarCreDes) {
        this.tarCreDes = tarCreDes;
    }
    public Double getTarCreLimInf() {
        return this.tarCreLimInf;
    }
    
    public void setTarCreLimInf(Double tarCreLimInf) {
        this.tarCreLimInf = tarCreLimInf;
    }
    public Double getTarCreLimSup() {
        return this.tarCreLimSup;
    }
    
    public void setTarCreLimSup(Double tarCreLimSup) {
        this.tarCreLimSup = tarCreLimSup;
    }
    public BigDecimal getTarCreOrdPre() {
        return this.tarCreOrdPre;
    }
    
    public void setTarCreOrdPre(BigDecimal tarCreOrdPre) {
        this.tarCreOrdPre = tarCreOrdPre;
    }
    public Double getTarCrePto() {
        return this.tarCrePto;
    }
    
    public void setTarCrePto(Double tarCrePto) {
        this.tarCrePto = tarCrePto;
    }
    public Double getTarCreWoe() {
        return this.tarCreWoe;
    }
    
    public void setTarCreWoe(Double tarCreWoe) {
        this.tarCreWoe = tarCreWoe;
    }
    public String getTarCreDesLar() {
        return this.tarCreDesLar;
    }
    
    public void setTarCreDesLar(String tarCreDesLar) {
        this.tarCreDesLar = tarCreDesLar;
    }




}


