package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipCre generated by hbm2java
 */
public class TipCre  implements java.io.Serializable {


     private BigDecimal tipCreId;
     private BigDecimal calId;
     private String tipCreDes;
     private Double tipCreLimInf;
     private Double tipCreLimSup;
     private BigDecimal tipCreOrdPre;
     private Double tipCrePto;
     private Double tipCreWoe;
     private String tipCreDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public TipCre() {
    }

	
    public TipCre(BigDecimal tipCreId) {
        this.tipCreId = tipCreId;
    }
    public TipCre(BigDecimal tipCreId, BigDecimal calId, String tipCreDes, Double tipCreLimInf, Double tipCreLimSup, BigDecimal tipCreOrdPre, Double tipCrePto, Double tipCreWoe, String tipCreDesLar, Set<CliGol> cliGols) {
       this.tipCreId = tipCreId;
       this.calId = calId;
       this.tipCreDes = tipCreDes;
       this.tipCreLimInf = tipCreLimInf;
       this.tipCreLimSup = tipCreLimSup;
       this.tipCreOrdPre = tipCreOrdPre;
       this.tipCrePto = tipCrePto;
       this.tipCreWoe = tipCreWoe;
       this.tipCreDesLar = tipCreDesLar;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getTipCreId() {
        return this.tipCreId;
    }
    
    public void setTipCreId(BigDecimal tipCreId) {
        this.tipCreId = tipCreId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getTipCreDes() {
        return this.tipCreDes;
    }
    
    public void setTipCreDes(String tipCreDes) {
        this.tipCreDes = tipCreDes;
    }
    public Double getTipCreLimInf() {
        return this.tipCreLimInf;
    }
    
    public void setTipCreLimInf(Double tipCreLimInf) {
        this.tipCreLimInf = tipCreLimInf;
    }
    public Double getTipCreLimSup() {
        return this.tipCreLimSup;
    }
    
    public void setTipCreLimSup(Double tipCreLimSup) {
        this.tipCreLimSup = tipCreLimSup;
    }
    public BigDecimal getTipCreOrdPre() {
        return this.tipCreOrdPre;
    }
    
    public void setTipCreOrdPre(BigDecimal tipCreOrdPre) {
        this.tipCreOrdPre = tipCreOrdPre;
    }
    public Double getTipCrePto() {
        return this.tipCrePto;
    }
    
    public void setTipCrePto(Double tipCrePto) {
        this.tipCrePto = tipCrePto;
    }
    public Double getTipCreWoe() {
        return this.tipCreWoe;
    }
    
    public void setTipCreWoe(Double tipCreWoe) {
        this.tipCreWoe = tipCreWoe;
    }
    public String getTipCreDesLar() {
        return this.tipCreDesLar;
    }
    
    public void setTipCreDesLar(String tipCreDesLar) {
        this.tipCreDesLar = tipCreDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


