package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Usu generated by hbm2java
 */
public class Usu  implements java.io.Serializable {


     private BigDecimal usuId;
     private BigDecimal calId;
     private String usuDes;
     private Double usuLimInf;
     private Double usuLimSup;
     private BigDecimal usuOrdPre;
     private Double usuPto;
     private Double usuWoe;
     private String usuDesLar;
     private String usuClave;
     private String usuPassword;
     private String usuPerfil;

    public Usu() {
    }

	
    public Usu(BigDecimal usuId) {
        this.usuId = usuId;
    }

    public Usu(BigDecimal usuId, BigDecimal calId, String usuDes, Double usuLimInf, Double usuLimSup, BigDecimal usuOrdPre, Double usuPto, Double usuWoe, String usuDesLar, String usuClave, String usuPassword, String usuPerfil) {
        this.usuId = usuId;
        this.calId = calId;
        this.usuDes = usuDes;
        this.usuLimInf = usuLimInf;
        this.usuLimSup = usuLimSup;
        this.usuOrdPre = usuOrdPre;
        this.usuPto = usuPto;
        this.usuWoe = usuWoe;
        this.usuDesLar = usuDesLar;
        this.usuClave = usuClave;
        this.usuPassword = usuPassword;
        this.usuPerfil = usuPerfil;
    }

   
    
    
   
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getUsuDes() {
        return this.usuDes;
    }
    
    public void setUsuDes(String usuDes) {
        this.usuDes = usuDes;
    }
    public Double getUsuLimInf() {
        return this.usuLimInf;
    }
    
    public void setUsuLimInf(Double usuLimInf) {
        this.usuLimInf = usuLimInf;
    }
    public Double getUsuLimSup() {
        return this.usuLimSup;
    }
    
    public void setUsuLimSup(Double usuLimSup) {
        this.usuLimSup = usuLimSup;
    }
    public BigDecimal getUsuOrdPre() {
        return this.usuOrdPre;
    }
    
    public void setUsuOrdPre(BigDecimal usuOrdPre) {
        this.usuOrdPre = usuOrdPre;
    }
    public Double getUsuPto() {
        return this.usuPto;
    }
    
    public void setUsuPto(Double usuPto) {
        this.usuPto = usuPto;
    }
    public Double getUsuWoe() {
        return this.usuWoe;
    }
    
    public void setUsuWoe(Double usuWoe) {
        this.usuWoe = usuWoe;
    }
    public String getUsuDesLar() {
        return this.usuDesLar;
    }
    
    public void setUsuDesLar(String usuDesLar) {
        this.usuDesLar = usuDesLar;
    }

    /**
     * @return the usuClave
     */
    public String getUsuClave() {
        return usuClave;
    }

    /**
     * @param usuClave the usuClave to set
     */
    public void setUsuClave(String usuClave) {
        this.usuClave = usuClave;
    }

    /**
     * @return the usuPassword
     */
    public String getUsuPassword() {
        return usuPassword;
    }
    
    public void setUsuPassword(String password){
        this.usuPassword=password;
    }

    /**
     * @return the usuPerfil
     */
    public String getUsuPerfil() {
        return usuPerfil;
    }

    /**
     * @param usuPerfil the usuPerfil to set
     */
    public void setUsuPerfil(String usuPerfil) {
        this.usuPerfil = usuPerfil;
    }



}


