package objetos;
// Generated 1/04/2010 01:02:42 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * VlrViv generated by hbm2java
 */
public class VlrViv  implements java.io.Serializable {


     private BigDecimal vlrVivId;
     private BigDecimal calId;
     private String vlrVivDes;
     private Double vlrVivLimInf;
     private Double vlrVivLimSup;
     private BigDecimal vlrVivOrdPre;
     private Double vlrVivPto;
     private Double vlrVivWoe;
     private String vlrVivDesLar;
     private Set<CliGol> cliGols = new HashSet<CliGol>(0);

    public VlrViv() {
    }

	
    public VlrViv(BigDecimal vlrVivId) {
        this.vlrVivId = vlrVivId;
    }
    public VlrViv(BigDecimal vlrVivId, BigDecimal calId, String vlrVivDes, Double vlrVivLimInf, Double vlrVivLimSup, BigDecimal vlrVivOrdPre, Double vlrVivPto, Double vlrVivWoe, String vlrVivDesLar, Set<CliGol> cliGols) {
       this.vlrVivId = vlrVivId;
       this.calId = calId;
       this.vlrVivDes = vlrVivDes;
       this.vlrVivLimInf = vlrVivLimInf;
       this.vlrVivLimSup = vlrVivLimSup;
       this.vlrVivOrdPre = vlrVivOrdPre;
       this.vlrVivPto = vlrVivPto;
       this.vlrVivWoe = vlrVivWoe;
       this.vlrVivDesLar = vlrVivDesLar;
       this.cliGols = cliGols;
    }
   
    public BigDecimal getVlrVivId() {
        return this.vlrVivId;
    }
    
    public void setVlrVivId(BigDecimal vlrVivId) {
        this.vlrVivId = vlrVivId;
    }
    public BigDecimal getCalId() {
        return this.calId;
    }
    
    public void setCalId(BigDecimal calId) {
        this.calId = calId;
    }
    public String getVlrVivDes() {
        return this.vlrVivDes;
    }
    
    public void setVlrVivDes(String vlrVivDes) {
        this.vlrVivDes = vlrVivDes;
    }
    public Double getVlrVivLimInf() {
        return this.vlrVivLimInf;
    }
    
    public void setVlrVivLimInf(Double vlrVivLimInf) {
        this.vlrVivLimInf = vlrVivLimInf;
    }
    public Double getVlrVivLimSup() {
        return this.vlrVivLimSup;
    }
    
    public void setVlrVivLimSup(Double vlrVivLimSup) {
        this.vlrVivLimSup = vlrVivLimSup;
    }
    public BigDecimal getVlrVivOrdPre() {
        return this.vlrVivOrdPre;
    }
    
    public void setVlrVivOrdPre(BigDecimal vlrVivOrdPre) {
        this.vlrVivOrdPre = vlrVivOrdPre;
    }
    public Double getVlrVivPto() {
        return this.vlrVivPto;
    }
    
    public void setVlrVivPto(Double vlrVivPto) {
        this.vlrVivPto = vlrVivPto;
    }
    public Double getVlrVivWoe() {
        return this.vlrVivWoe;
    }
    
    public void setVlrVivWoe(Double vlrVivWoe) {
        this.vlrVivWoe = vlrVivWoe;
    }
    public String getVlrVivDesLar() {
        return this.vlrVivDesLar;
    }
    
    public void setVlrVivDesLar(String vlrVivDesLar) {
        this.vlrVivDesLar = vlrVivDesLar;
    }
    public Set<CliGol> getCliGols() {
        return this.cliGols;
    }
    
    public void setCliGols(Set<CliGol> cliGols) {
        this.cliGols = cliGols;
    }




}


